package com.kp.cms.bo.hostel;

// Generated Dec 18, 2009 3:48:30 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

import com.kp.cms.bo.admin.FeeGroup;
import com.kp.cms.bo.admin.HlHostel;
import com.kp.cms.bo.admin.HlRoomType;
/**
 * HlRoomType generated by hbm2java
 */
public class HlRoomTypeFees implements java.io.Serializable {

	private int id;
	private HlHostel hostelId;
	private HlRoomType roomTypeId;
	private FeeGroup feegroupId;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	
	public HlRoomTypeFees() {
	}

	public HlRoomTypeFees(int id) {
		this.id = id;
	}

	public HlRoomTypeFees(int id,HlHostel hostelId, HlRoomType roomTypeId,
			FeeGroup feegroupId,String createdBy,
			Date createdDate, String modifiedBy, Date lastModifiedDate,Boolean isActive) {
		this.id = id;
		this.hostelId = hostelId;
		this.roomTypeId = roomTypeId;
		this.feegroupId = feegroupId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public HlHostel getHostelId() {
		return hostelId;
	}

	public void setHostelId(HlHostel hostelId) {
		this.hostelId = hostelId;
	}

	public HlRoomType getRoomTypeId() {
		return roomTypeId;
	}

	public void setRoomTypeId(HlRoomType roomTypeId) {
		this.roomTypeId = roomTypeId;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public FeeGroup getFeegroupId() {
		return feegroupId;
	}

	public void setFeegroupId(FeeGroup feegroupId) {
		this.feegroupId = feegroupId;
	}


}
