package com.kp.cms.bo.admin;

// Generated Jan 15, 2010 2:30:28 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;


/**
 * AcademicYear generated by hbm2java
 */
@SuppressWarnings("serial")
public class AcademicYear implements java.io.Serializable {

	private int id;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Integer year;
	private Boolean isCurrent;
	private Boolean isCurrentForAdmission;
	
	public AcademicYear() {
	}

	public AcademicYear(int id) {
		this.id = id;
	}

	public AcademicYear(int id, String createdBy, Date createdDate,
			String modifiedBy, Date lastModifiedDate, Boolean isActive,
			Integer year, Boolean isCurrent,Boolean isCurrentForAdmission) {
		this.id = id;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.year = year;
		this.isCurrent = isCurrent;
		this.isCurrentForAdmission = isCurrentForAdmission;
	}

	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}


	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}


	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}


	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}


	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Boolean getIsCurrent() {
		return this.isCurrent;
	}

	public void setIsCurrent(Boolean isCurrent) {
		this.isCurrent = isCurrent;
	}

	public void setIsCurrentForAdmission(Boolean isCurrentForAdmission) {
		this.isCurrentForAdmission = isCurrentForAdmission;
	}

	public Boolean getIsCurrentForAdmission() {
		return isCurrentForAdmission;
	}
	
}
