package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdmittedThrough generated by hbm2java
 */
public class AdmittedThrough implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private String name;
	private Date createdDate;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<FeeAccountAssignment> feeAccountAssignments = new HashSet<FeeAccountAssignment>(
			0);
	private Set<SeatAllocation> seatAllocations = new HashSet<SeatAllocation>(0);
	private Set<AdmAppln> admApplns = new HashSet<AdmAppln>(0);
	private Set<FeeCriteria> feeCriteriasAdm = new HashSet<FeeCriteria>();
	private String admittedThroughCode;
	
	public AdmittedThrough() {
	}

	public AdmittedThrough(int id) {
		this.id = id;
	}

	public AdmittedThrough(int id, String createdBy,
			String modifiedBy, String name, Date createdDate,
			Date lastModifiedDate,
			Set<FeeAccountAssignment> feeAccountAssignments,
			Set<SeatAllocation> seatAllocations, Set<AdmAppln> admApplns, Set<FeeCriteria> feeCriteriasAdm, String admittedThroughCode) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.name = name;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.feeAccountAssignments = feeAccountAssignments;
		this.seatAllocations = seatAllocations;
		this.admApplns = admApplns;
		this.feeCriteriasAdm = feeCriteriasAdm;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<FeeAccountAssignment> getFeeAccountAssignments() {
		return this.feeAccountAssignments;
	}

	public void setFeeAccountAssignments(
			Set<FeeAccountAssignment> feeAccountAssignments) {
		this.feeAccountAssignments = feeAccountAssignments;
	}

	public Set<SeatAllocation> getSeatAllocations() {
		return this.seatAllocations;
	}

	public void setSeatAllocations(Set<SeatAllocation> seatAllocations) {
		this.seatAllocations = seatAllocations;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
	public Set<AdmAppln> getAdmApplns() {
		return this.admApplns;
	}

	public void setAdmApplns(Set<AdmAppln> admApplns) {
		this.admApplns = admApplns;
	}

	public Set<FeeCriteria> getFeeCriteriasAdm() {
		return feeCriteriasAdm;
	}

	public void setFeeCriteriasAdm(Set<FeeCriteria> feeCriteriasAdm) {
		this.feeCriteriasAdm = feeCriteriasAdm;
	}

	public void setAdmittedThroughCode(String admittedThroughCode) {
		this.admittedThroughCode = admittedThroughCode;
	}

	public String getAdmittedThroughCode() {
		return admittedThroughCode;
	}

	
}
