package com.kp.cms.bo.admin;

// Generated Feb 5, 2009 12:58:29 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * ApplicantRecommendor generated by hbm2java
 */
public class ApplicantRecommendor implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private Recommendor recommendor;
	private String modifiedBy;
	private InterviewProgramCourse interviewProgramCourse;
	private AdmAppln admAppln;
	private Date createdDate;
	private Date lastModifiedDate;
	private Boolean isActive;

	public ApplicantRecommendor() {
	}

	public ApplicantRecommendor(int id) {
		this.id = id;
	}

	public ApplicantRecommendor(int id, String createdBy,
			Recommendor recommendor, String modifiedBy,
			InterviewProgramCourse interviewProgramCourse, AdmAppln admAppln,
			Date createdDate, Date lastModifiedDate, Boolean isActive) {
		this.id = id;
		this.createdBy = createdBy;
		this.recommendor = recommendor;
		this.modifiedBy = modifiedBy;
		this.interviewProgramCourse = interviewProgramCourse;
		this.admAppln = admAppln;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public Recommendor getRecommendor() {
		return this.recommendor;
	}

	public void setRecommendor(Recommendor recommendor) {
		this.recommendor = recommendor;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public InterviewProgramCourse getInterviewProgramCourse() {
		return this.interviewProgramCourse;
	}

	public void setInterviewProgramCourse(
			InterviewProgramCourse interviewProgramCourse) {
		this.interviewProgramCourse = interviewProgramCourse;
	}

	public AdmAppln getAdmAppln() {
		return this.admAppln;
	}

	public void setAdmAppln(AdmAppln admAppln) {
		this.admAppln = admAppln;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
}