package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * AttendanceMarks generated by hbm2java
 */
public class AttendanceMarks implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private Subject subject;
	private String modifiedBy;
	private Program program;
	private Course course;
	private Integer fromPercentage;
	private Integer toPercentage;
	private Integer marks;
	private Date createdDate;
	private Date lastModifiedDate;

	public AttendanceMarks() {
	}

	public AttendanceMarks(int id) {
		this.id = id;
	}

	public AttendanceMarks(int id, String createdBy,
			Subject subject, String modifiedBy, Program program,
			Course course, Integer fromPercentage, Integer toPercentage,
			Integer marks, Date createdDate, Date lastModifiedDate) {
		this.id = id;
		this.createdBy = createdBy;
		this.subject = subject;
		this.modifiedBy = modifiedBy;
		this.program = program;
		this.course = course;
		this.fromPercentage = fromPercentage;
		this.toPercentage = toPercentage;
		this.marks = marks;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Integer getFromPercentage() {
		return this.fromPercentage;
	}

	public void setFromPercentage(Integer fromPercentage) {
		this.fromPercentage = fromPercentage;
	}

	public Integer getToPercentage() {
		return this.toPercentage;
	}

	public void setToPercentage(Integer toPercentage) {
		this.toPercentage = toPercentage;
	}

	public Integer getMarks() {
		return this.marks;
	}

	public void setMarks(Integer marks) {
		this.marks = marks;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
