package com.kp.cms.bo.admin;

// Generated Apr 20, 2009 4:50:12 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AttendanceType generated by hbm2java
 */
public class AttendanceType implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean isDefault;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<AttendanceTypeMandatory> attendanceTypeMandatories = new HashSet<AttendanceTypeMandatory>(
			0);
	private Set<Activity> activities = new HashSet<Activity>(0);
	private Set<Attendance> attendances = new HashSet<Attendance>(0);
	private Set<StuCocurrLeave> stuCocurrLeaves = new HashSet<StuCocurrLeave>(0);
	
	public AttendanceType() {
	}

	public AttendanceType(int id) {
		this.id = id;
	}

	public AttendanceType(int id, String name, Boolean isDefault,
			String createdBy, Date createdDate, String modifiedBy,
			Date lastModifiedDate, Boolean isActive,Set<StuCocurrLeave> stuCocurrLeaves,
			Set<AttendanceTypeMandatory> attendanceTypeMandatories,
			Set<Activity> activities, Set<Attendance> attendances) {
		this.id = id;
		this.name = name;
		this.isDefault = isDefault;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.attendanceTypeMandatories = attendanceTypeMandatories;
		this.activities = activities;
		this.stuCocurrLeaves = stuCocurrLeaves;
		this.attendances = attendances;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<AttendanceTypeMandatory> getAttendanceTypeMandatories() {
		return this.attendanceTypeMandatories;
	}

	public void setAttendanceTypeMandatories(
			Set<AttendanceTypeMandatory> attendanceTypeMandatories) {
		this.attendanceTypeMandatories = attendanceTypeMandatories;
	}

	public Set<Activity> getActivities() {
		return this.activities;
	}

	public void setActivities(Set<Activity> activities) {
		this.activities = activities;
	}

	public Set<Attendance> getAttendances() {
		return this.attendances;
	}

	public void setAttendances(Set<Attendance> attendances) {
		this.attendances = attendances;
	}

	public Set<StuCocurrLeave> getStuCocurrLeaves() {
		return this.stuCocurrLeaves;
	}

	public void setStuCocurrLeaves(Set<StuCocurrLeave> stuCocurrLeaves) {
		this.stuCocurrLeaves = stuCocurrLeaves;
	}

}
