package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BankBranch generated by hbm2java
 */
public class BankBranch implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private Bank bank;
	private String name;
	private String ifscCode;
	private String micrCode;
	private String bankBranchCode;
	private Date createdDate;
	private Date lastModifiedDate;
	private Set<Account> accounts = new HashSet<Account>(0);
	private Set<FeeTransaction> feeTransactions = new HashSet<FeeTransaction>(0);

	public BankBranch() {
	}

	public BankBranch(int id) {
		this.id = id;
	}

	public BankBranch(int id, String createdBy,
			String modifiedBy, Bank bank, String name,
			String ifscCode, String micrCode, String bankBranchCode,
			Date createdDate, Date lastModifiedDate, Set<Account> accounts,
			Set<FeeTransaction> feeTransactions) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.bank = bank;
		this.name = name;
		this.ifscCode = ifscCode;
		this.micrCode = micrCode;
		this.bankBranchCode = bankBranchCode;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.accounts = accounts;
		this.feeTransactions = feeTransactions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Bank getBank() {
		return this.bank;
	}

	public void setBank(Bank bank) {
		this.bank = bank;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIfscCode() {
		return this.ifscCode;
	}

	public void setIfscCode(String ifscCode) {
		this.ifscCode = ifscCode;
	}

	public String getMicrCode() {
		return this.micrCode;
	}

	public void setMicrCode(String micrCode) {
		this.micrCode = micrCode;
	}

	public String getBankBranchCode() {
		return this.bankBranchCode;
	}

	public void setBankBranchCode(String bankBranchCode) {
		this.bankBranchCode = bankBranchCode;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

	public Set<FeeTransaction> getFeeTransactions() {
		return this.feeTransactions;
	}

	public void setFeeTransactions(Set<FeeTransaction> feeTransactions) {
		this.feeTransactions = feeTransactions;
	}

}
