package com.kp.cms.bo.admin;

// Generated Apr 24, 2009 5:46:46 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Batch generated by hbm2java
 */
public class Batch implements java.io.Serializable {

	private int id;
	private ClassSchemewise classSchemewise;
	private Subject subject;
	private String batchName;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<BatchStudent> batchStudents = new HashSet<BatchStudent>(0);
	private Activity activity;

	public Batch() {
	}

	public Batch(int id) {
		this.id = id;
	}

	public Batch(int id, ClassSchemewise classSchemewise, Subject subject,
			String batchName, String createdBy, Date createdDate,
			String modifiedBy, Date lastModifiedDate, Boolean isActive,
			Set<BatchStudent> batchStudents,Activity activity) {
		this.id = id;
		this.classSchemewise = classSchemewise;
		this.subject = subject;
		this.batchName = batchName;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.batchStudents = batchStudents;
		this.activity=activity;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ClassSchemewise getClassSchemewise() {
		return this.classSchemewise;
	}

	public void setClassSchemewise(ClassSchemewise classSchemewise) {
		this.classSchemewise = classSchemewise;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public String getBatchName() {
		return this.batchName;
	}

	public void setBatchName(String batchName) {
		this.batchName = batchName;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<BatchStudent> getBatchStudents() {
		return this.batchStudents;
	}

	public void setBatchStudents(Set<BatchStudent> batchStudents) {
		this.batchStudents = batchStudents;
	}

	public Activity getActivity() {
		return activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

}
