package com.kp.cms.bo.admin;
// Generated Feb 9, 2011 2:51:21 PM by Hibernate Tools 3.2.6.CR1

import java.util.Date;

/**
 * CertificateCourseTeacher generated by hbm2java
 */
public class CertificateCourseTeacher implements java.io.Serializable {

	private Integer id;
	private Users users;
	private CertificateCourse certificateCourse;
	private String startTime;
	private String endTime;
	private String venue;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;

	public CertificateCourseTeacher() {
	}

	public CertificateCourseTeacher(Users users,
			CertificateCourse certificateCourse, String startTime, String endTime,
			String venue, String createdBy, Date createdDate,
			String modifiedBy, Date lastModifiedDate, Boolean isActive) {
		this.users = users;
		this.certificateCourse = certificateCourse;
		this.startTime = startTime;
		this.endTime = endTime;
		this.venue = venue;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public CertificateCourse getCertificateCourse() {
		return this.certificateCourse;
	}

	public void setCertificateCourse(CertificateCourse certificateCourse) {
		this.certificateCourse = certificateCourse;
	}

	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getVenue() {
		return this.venue;
	}

	public void setVenue(String venue) {
		this.venue = venue;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
