package com.kp.cms.bo.admin;

// Generated Apr 20, 2009 4:50:12 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kp.cms.bo.exam.InternalMarkSupplementaryDetails;
import com.kp.cms.bo.exam.StudentFinalMarkDetails;

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Course course;
	private String name;
	private String sectionName;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Integer termNumber;
	private Boolean isActive;
	private Integer courseGroupCodeId;
	private Set<ClassSchemewise> classSchemewises = new HashSet<ClassSchemewise>(
			0);
	private Set<InternalMarkSupplementaryDetails> markSupplementaryDetails=new HashSet<InternalMarkSupplementaryDetails>();
	private Set<StudentFinalMarkDetails> finalMarkDetails=new HashSet<StudentFinalMarkDetails>();

	public Classes() {
	}

	public Classes(int id) {
		this.id = id;
	}

	public Classes(int id, Course course, String name, String sectionName,
			String createdBy, Date createdDate, String modifiedBy,
			Date lastModifiedDate, Integer termNumber, Boolean isActive,
			Set<ClassSchemewise> classSchemewises) {
		this.id = id;
		this.course = course;
		this.name = name;
		this.sectionName = sectionName;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.termNumber = termNumber;
		this.isActive = isActive;
		this.classSchemewises = classSchemewises;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSectionName() {
		return this.sectionName;
	}

	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Integer getTermNumber() {
		return this.termNumber;
	}

	public void setTermNumber(Integer termNumber) {
		this.termNumber = termNumber;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<ClassSchemewise> getClassSchemewises() {
		return this.classSchemewises;
	}

	public void setClassSchemewises(Set<ClassSchemewise> classSchemewises) {
		this.classSchemewises = classSchemewises;
	}

	public void setCourseGroupCodeId(Integer courseGroupCodeId) {
		this.courseGroupCodeId = courseGroupCodeId;
	}

	public Integer getCourseGroupCodeId() {
		return courseGroupCodeId;
	}

	public Set<InternalMarkSupplementaryDetails> getMarkSupplementaryDetails() {
		return markSupplementaryDetails;
	}

	public void setMarkSupplementaryDetails(
			Set<InternalMarkSupplementaryDetails> markSupplementaryDetails) {
		this.markSupplementaryDetails = markSupplementaryDetails;
	}

	public Set<StudentFinalMarkDetails> getFinalMarkDetails() {
		return finalMarkDetails;
	}

	public void setFinalMarkDetails(Set<StudentFinalMarkDetails> finalMarkDetails) {
		this.finalMarkDetails = finalMarkDetails;
	}
}
