package com.kp.cms.bo.admin;

// Generated Apr 15, 2009 5:41:48 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CombinedClass generated by hbm2java
 */
public class CombinedClass implements java.io.Serializable {

	private int id;
	private Subject subject;
	private Classes classes;
	private String name;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<CombinedClassStudents> combinedClassStudentses = new HashSet<CombinedClassStudents>(
			0);

	public CombinedClass() {
	}

	public CombinedClass(int id) {
		this.id = id;
	}

	public CombinedClass(int id, Subject subject, Classes classes, String name,
			String createdBy, Date createdDate, String modifiedBy,
			Date lastModifiedDate, Boolean isActive,
			Set<CombinedClassStudents> combinedClassStudentses) {
		this.id = id;
		this.subject = subject;
		this.classes = classes;
		this.name = name;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.combinedClassStudentses = combinedClassStudentses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<CombinedClassStudents> getCombinedClassStudentses() {
		return this.combinedClassStudentses;
	}

	public void setCombinedClassStudentses(
			Set<CombinedClassStudents> combinedClassStudentses) {
		this.combinedClassStudentses = combinedClassStudentses;
	}

}
