package com.kp.cms.bo.admin;

// Generated Apr 15, 2009 5:41:48 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * CombinedClassStudents generated by hbm2java
 */
public class CombinedClassStudents implements java.io.Serializable {

	private int id;
	private CombinedClass combinedClass;
	private String registerNo;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedBy;
	private Boolean isActive;

	public CombinedClassStudents() {
	}

	public CombinedClassStudents(int id) {
		this.id = id;
	}

	public CombinedClassStudents(int id, CombinedClass combinedClass,
			String registerNo, String createdBy, Date createdDate,
			String modifiedBy, Date lastModifiedBy, Boolean isActive) {
		this.id = id;
		this.combinedClass = combinedClass;
		this.registerNo = registerNo;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedBy = lastModifiedBy;
		this.isActive = isActive;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CombinedClass getCombinedClass() {
		return this.combinedClass;
	}

	public void setCombinedClass(CombinedClass combinedClass) {
		this.combinedClass = combinedClass;
	}

	public String getRegisterNo() {
		return this.registerNo;
	}

	public void setRegisterNo(String registerNo) {
		this.registerNo = registerNo;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Date lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
