package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;



/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private Program program;
	private String name;
	private String code;
	private Boolean isActive;
	private Date createdDate;
	private Date lastModifiedDate;
	private Boolean isAutonomous;
	private Integer maxIntake;
	private Boolean isWorkExperienceRequired;
	private String payCode;
	private BigDecimal amount;
	private Boolean isDetailMarksPrint;
	
	
	private Set<AdmAppln> admApplnsForSelectedCourseId = new HashSet<AdmAppln>(0);
	private Set<AdmAppln> admApplnsForCourseId = new HashSet<AdmAppln>(0);
	private Set<FeeConcession> feeConcessions = new HashSet<FeeConcession>(0);
	private Set<Preferences> preferencesesForPrefCourseId = new HashSet<Preferences>(
			0);
	private Set<DocChecklist> docChecklists = new HashSet<DocChecklist>(0);
	private Set<AttendanceMarks> attendanceMarkses = new HashSet<AttendanceMarks>(
			0);
	private Set<Weightage> weightages = new HashSet<Weightage>(0);
	private Set<ApplnType> applnTypes = new HashSet<ApplnType>(0);
	private Set<AdmAppln> admApplns = new HashSet<AdmAppln>(0);
	private Set<ProgCourseDoc> progCourseDocs = new HashSet<ProgCourseDoc>(0);
	private Set<CourseTerm> courseTerms = new HashSet<CourseTerm>(0);
	private Set<SeatAllocation> seatAllocations = new HashSet<SeatAllocation>(0);
	private Set<Fee> fees = new HashSet<Fee>(0);
	private Set<SubjectGroup> subjectGroups = new HashSet<SubjectGroup>(0);
	private Set<Preferences> preferencesesForCourseId = new HashSet<Preferences>(
			0);
	private Set<CoursePrerequisite> coursePrerequisites = new HashSet<CoursePrerequisite>(
			0);
	private Set<CurriculumScheme> curriculumSchemes = new HashSet<CurriculumScheme>(
			0);
	private Set<RegistrationNumberFormat> registrationNumberFormats = new HashSet<RegistrationNumberFormat>(
			0);
	private Set<TermsConditions> termsConditionses = new HashSet<TermsConditions>(
			0);
	private Set<SelectionProcess> selectionProcesses = new HashSet<SelectionProcess>(
			0);
	private Set<CandidatePreference> candidatePreferences = new HashSet<CandidatePreference>(
			0);
	
	private Set<ProgramCourseIntake> programCourseIntakes = new HashSet<ProgramCourseIntake>(
			0);
	private Set<GuidelinesDoc> guidelinesDocs = new HashSet<GuidelinesDoc>(0);
	private Set<EligibilityCriteria> eligibilityCriterias = new HashSet<EligibilityCriteria>(
			0);
	private Set<InterviewProgramCourse> interviewProgramCourses = new HashSet<InterviewProgramCourse>(
			0);
	private Set<CourseApplicationNumber> courseApplicationNumbers = new HashSet<CourseApplicationNumber>(
			0);
	private Set<DetailedSubjects> detailedSubjectses = new HashSet<DetailedSubjects>(
			0);
	private Set<TermsConditionChecklist> termsConditionChecklists = new HashSet<TermsConditionChecklist>(
			0);
	private Set<GroupTemplate> groupTemplates = new HashSet<GroupTemplate>(0);
	private Set<HonorsEntryBo> honorsSet=new HashSet<HonorsEntryBo>();
	private Set<Classes> classes=new HashSet<Classes>();
	private String certificateCourseName;
	private String bankName;
	private String bankNameFull;
	private Boolean bankIncludeSection;
	private Boolean isWorkExperienceMandatory;
	private Boolean isAppearInOnline;
	private Boolean isApplicationProcessSms;
	private Boolean onlyForApplication;
	private String courseMarksCard;
	private Date commencementDate;
	private BigDecimal applicationFees;
	private Currency currencyId;
	private EmployeeWorkLocationBO workLocation;
	private Integer noOfAttemtsMidSem;
	private String dateTime;
	private String generalFee;
	private String casteFee;
	private String communityDateTime;
	private String casteDateTime;
	private String chanceGenDateTime;
	private String chanceCommDateTime;
	private String chanceCasteDateTime;
	private Boolean isSelfFinancing;
	private Integer courseOrder;
	public String getDateTime() {
		return dateTime;
	}

	public void setDateTime(String dateTime) {
		this.dateTime = dateTime;
	}

	public String getGeneralFee() {
		return generalFee;
	}

	public void setGeneralFee(String generalFee) {
		this.generalFee = generalFee;
	}

	public String getCasteFee() {
		return casteFee;
	}

	public void setCasteFee(String casteFee) {
		this.casteFee = casteFee;
	}

	public Course() {
	}

	public Course(int id) {
		this.id = id;
	}

	public Course(int id, String createdBy,
			String modifiedBy, Program program, String name,
			String code, Boolean isActive, Date createdDate,
			Date lastModifiedDate, Boolean isAutonomous, Integer maxIntake,
			Set<AdmAppln> admApplnsForCourseId,
			Set<FeeConcession> feeConcessions,
			Set<Preferences> preferencesesForPrefCourseId,
			Set<DocChecklist> docChecklists,
			Set<TermsConditionChecklist> termsConditionChecklists,
			Set<AttendanceMarks> attendanceMarkses, Set<Weightage> weightages,
			Set<ApplnType> applnTypes, Set<AdmAppln> admApplns,
			Set<ProgCourseDoc> progCourseDocs, Set<CourseTerm> courseTerms,
			Set<SeatAllocation> seatAllocations, Set<Fee> fees,
			Set<SubjectGroup> subjectGroups,
			Set<Preferences> preferencesesForCourseId,
			Set<CoursePrerequisite> coursePrerequisites,
			Set<CurriculumScheme> curriculumSchemes,
			Set<RegistrationNumberFormat> registrationNumberFormats,
			Set<TermsConditions> termsConditionses,
			Set<SelectionProcess> selectionProcesses,
			Set<CandidatePreference> candidatePreferences,
			Set<DetailedSubjects> detailedSubjectses,
			Set<ProgramCourseIntake> programCourseIntakes,
			Set<GuidelinesDoc> guidelinesDocs,
			Set<EligibilityCriteria> eligibilityCriterias,
			Set<InterviewProgramCourse> interviewProgramCourses,
			Set<CourseApplicationNumber> courseApplicationNumbers,
			Set<GroupTemplate> groupTemplates, Boolean isDetailMarksPrint,
			String certificateCourseName, Boolean onlyForApplication,String courseMarksCard,Boolean bankIncludeSection,Date commencementDate,BigDecimal applicationFees
			,Currency currencyId,EmployeeWorkLocationBO workLocation,Integer noOfAttemtsMidSem,String generalFee,String casteFee,
			String dateTime,String communityDateTime,String casteDateTime, String chanceGenDateTime, String chanceCommDateTime, 
			String chanceCasteDateTime, Boolean isSelfFinancing,Integer courseOrder) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.program = program;
		this.name = name;
		this.code = code;
		this.isActive = isActive;
		this.createdDate = (Date)createdDate.clone();
		this.lastModifiedDate = (Date)lastModifiedDate.clone();
		this.isAutonomous = isAutonomous;
		this.maxIntake = maxIntake;
		this.admApplnsForCourseId = admApplnsForCourseId;
		this.feeConcessions = feeConcessions;
		this.preferencesesForPrefCourseId = preferencesesForPrefCourseId;
		this.docChecklists = docChecklists;
		this.termsConditionChecklists = termsConditionChecklists;
		this.attendanceMarkses = attendanceMarkses;
		this.weightages = weightages;
		this.applnTypes = applnTypes;
		this.admApplns = admApplns;
		this.coursePrerequisites = coursePrerequisites;
		this.progCourseDocs = progCourseDocs;
		this.courseTerms = courseTerms;
		this.seatAllocations = seatAllocations;
		this.fees = fees;
		this.subjectGroups = subjectGroups;
		this.preferencesesForCourseId = preferencesesForCourseId;
		this.curriculumSchemes = curriculumSchemes;
		this.registrationNumberFormats = registrationNumberFormats;
		this.termsConditionses = termsConditionses;
		this.selectionProcesses = selectionProcesses;
		this.candidatePreferences = candidatePreferences;
		this.detailedSubjectses=detailedSubjectses;
		this.programCourseIntakes = programCourseIntakes;
		this.guidelinesDocs = guidelinesDocs;
		this.eligibilityCriterias = eligibilityCriterias;
		this.interviewProgramCourses = interviewProgramCourses;
		this.courseApplicationNumbers = courseApplicationNumbers;
		this.groupTemplates = groupTemplates;
		this.isDetailMarksPrint = isDetailMarksPrint;
		this.certificateCourseName = certificateCourseName;
		this.onlyForApplication = onlyForApplication;
		this.courseMarksCard=courseMarksCard;
		this.bankIncludeSection=bankIncludeSection;
		this.commencementDate=(Date)commencementDate.clone();
		this.applicationFees=applicationFees;
		this.currencyId=currencyId;
		this.workLocation=workLocation;
		this.noOfAttemtsMidSem=noOfAttemtsMidSem;
		this.generalFee=generalFee;
		this.casteFee = casteFee;
		this.dateTime = dateTime;
		this.communityDateTime = communityDateTime;
		this.casteDateTime = casteDateTime;
		this.chanceGenDateTime = chanceGenDateTime;
		this.chanceCommDateTime = chanceCommDateTime;
		this.chanceCasteDateTime = chanceCasteDateTime;
		this.isSelfFinancing = isSelfFinancing;
		this.courseOrder = courseOrder;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsAutonomous() {
		return this.isAutonomous;
	}

	public void setIsAutonomous(Boolean isAutonomous) {
		this.isAutonomous = isAutonomous;
	}

	public Integer getMaxIntake() {
		return this.maxIntake;
	}

	public void setMaxIntake(Integer maxIntake) {
		this.maxIntake = maxIntake;
	}

	public Set<FeeConcession> getFeeConcessions() {
		return this.feeConcessions;
	}

	public void setFeeConcessions(Set<FeeConcession> feeConcessions) {
		this.feeConcessions = feeConcessions;
	}

	public Set<Preferences> getPreferencesesForPrefCourseId() {
		return this.preferencesesForPrefCourseId;
	}

	public void setPreferencesesForPrefCourseId(
			Set<Preferences> preferencesesForPrefCourseId) {
		this.preferencesesForPrefCourseId = preferencesesForPrefCourseId;
	}

	public Set<DocChecklist> getDocChecklists() {
		return this.docChecklists;
	}

	public void setDocChecklists(Set<DocChecklist> docChecklists) {
		this.docChecklists = docChecklists;
	}
	public Set<TermsConditionChecklist> getTermsConditionChecklists() {
		return this.termsConditionChecklists;
	}

	public void setTermsConditionChecklists(
			Set<TermsConditionChecklist> termsConditionChecklists) {
		this.termsConditionChecklists = termsConditionChecklists;
	}

	public Set<AttendanceMarks> getAttendanceMarkses() {
		return this.attendanceMarkses;
	}

	public void setAttendanceMarkses(Set<AttendanceMarks> attendanceMarkses) {
		this.attendanceMarkses = attendanceMarkses;
	}

	public Set<Weightage> getWeightages() {
		return this.weightages;
	}

	public void setWeightages(Set<Weightage> weightages) {
		this.weightages = weightages;
	}

	public Set<ApplnType> getApplnTypes() {
		return this.applnTypes;
	}

	public void setApplnTypes(Set<ApplnType> applnTypes) {
		this.applnTypes = applnTypes;
	}

	public Set<AdmAppln> getAdmApplns() {
		return this.admApplns;
	}

	public void setAdmApplns(Set<AdmAppln> admApplns) {
		this.admApplns = admApplns;
	}
	
	public Set<CoursePrerequisite> getCoursePrerequisites() {
		return this.coursePrerequisites;
	}

	public void setCoursePrerequisites(
			Set<CoursePrerequisite> coursePrerequisites) {
		this.coursePrerequisites = coursePrerequisites;
	}
	public Set<ProgCourseDoc> getProgCourseDocs() {
		return this.progCourseDocs;
	}

	public void setProgCourseDocs(Set<ProgCourseDoc> progCourseDocs) {
		this.progCourseDocs = progCourseDocs;
	}

	public Set<CourseTerm> getCourseTerms() {
		return this.courseTerms;
	}

	public void setCourseTerms(Set<CourseTerm> courseTerms) {
		this.courseTerms = courseTerms;
	}

	public Set<SeatAllocation> getSeatAllocations() {
		return this.seatAllocations;
	}

	public void setSeatAllocations(Set<SeatAllocation> seatAllocations) {
		this.seatAllocations = seatAllocations;
	}

	public Set<Fee> getFees() {
		return this.fees;
	}

	public void setFees(Set<Fee> fees) {
		this.fees = fees;
	}

	public Set<SubjectGroup> getSubjectGroups() {
		return this.subjectGroups;
	}

	public void setSubjectGroups(Set<SubjectGroup> subjectGroups) {
		this.subjectGroups = subjectGroups;
	}

	public Set<Preferences> getPreferencesesForCourseId() {
		return this.preferencesesForCourseId;
	}

	public void setPreferencesesForCourseId(
			Set<Preferences> preferencesesForCourseId) {
		this.preferencesesForCourseId = preferencesesForCourseId;
	}

	public Set<CurriculumScheme> getCurriculumSchemes() {
		return this.curriculumSchemes;
	}

	public void setCurriculumSchemes(Set<CurriculumScheme> curriculumSchemes) {
		this.curriculumSchemes = curriculumSchemes;
	}

	public Set<RegistrationNumberFormat> getRegistrationNumberFormats() {
		return this.registrationNumberFormats;
	}

	public void setRegistrationNumberFormats(
			Set<RegistrationNumberFormat> registrationNumberFormats) {
		this.registrationNumberFormats = registrationNumberFormats;
	}

	public Set<TermsConditions> getTermsConditionses() {
		return this.termsConditionses;
	}

	public void setTermsConditionses(Set<TermsConditions> termsConditionses) {
		this.termsConditionses = termsConditionses;
	}

	public Set<SelectionProcess> getSelectionProcesses() {
		return this.selectionProcesses;
	}

	public void setSelectionProcesses(Set<SelectionProcess> selectionProcesses) {
		this.selectionProcesses = selectionProcesses;
	}

	public Set<CandidatePreference> getCandidatePreferences() {
		return this.candidatePreferences;
	}

	public void setCandidatePreferences(
			Set<CandidatePreference> candidatePreferences) {
		this.candidatePreferences = candidatePreferences;
	}



	public Set<ProgramCourseIntake> getProgramCourseIntakes() {
		return this.programCourseIntakes;
	}

	public void setProgramCourseIntakes(
			Set<ProgramCourseIntake> programCourseIntakes) {
		this.programCourseIntakes = programCourseIntakes;
	}

	public Set<GuidelinesDoc> getGuidelinesDocs() {
		return this.guidelinesDocs;
	}

	public void setGuidelinesDocs(Set<GuidelinesDoc> guidelinesDocs) {
		this.guidelinesDocs = guidelinesDocs;
	}

	public Set<EligibilityCriteria> getEligibilityCriterias() {
		return this.eligibilityCriterias;
	}

	public void setEligibilityCriterias(
			Set<EligibilityCriteria> eligibilityCriterias) {
		this.eligibilityCriterias = eligibilityCriterias;
	}

	public Set<InterviewProgramCourse> getInterviewProgramCourses() {
		return this.interviewProgramCourses;
	}

	public void setInterviewProgramCourses(
			Set<InterviewProgramCourse> interviewProgramCourses) {
		this.interviewProgramCourses = interviewProgramCourses;
	}

	public Boolean getIsWorkExperienceRequired() {
		return isWorkExperienceRequired;
	}

	public void setIsWorkExperienceRequired(Boolean isWorkExperienceRequired) {
		this.isWorkExperienceRequired = isWorkExperienceRequired;
	}

	public String getPayCode() {
		return payCode;
	}

	public void setPayCode(String payCode) {
		this.payCode = payCode;
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public Set<CourseApplicationNumber> getCourseApplicationNumbers() {
		return this.courseApplicationNumbers;
	}

	public void setCourseApplicationNumbers(
			Set<CourseApplicationNumber> courseApplicationNumbers) {
		this.courseApplicationNumbers = courseApplicationNumbers;
	}

	public Set<AdmAppln> getAdmApplnsForCourseId() {
		return admApplnsForCourseId;
	}

	public void setAdmApplnsForCourseId(Set<AdmAppln> admApplnsForCourseId) {
		this.admApplnsForCourseId = admApplnsForCourseId;
	}

	public Set<AdmAppln> getAdmApplnsForSelectedCourseId() {
		return admApplnsForSelectedCourseId;
	}

	public void setAdmApplnsForSelectedCourseId(
			Set<AdmAppln> admApplnsForSelectedCourseId) {
		this.admApplnsForSelectedCourseId = admApplnsForSelectedCourseId;
	}

	public Set<DetailedSubjects> getDetailedSubjectses() {
		return detailedSubjectses;
	}

	public void setDetailedSubjectses(Set<DetailedSubjects> detailedSubjectses) {
		this.detailedSubjectses = detailedSubjectses;
	}

	public Set<GroupTemplate> getGroupTemplates() {
		return groupTemplates;
	}

	public void setGroupTemplates(Set<GroupTemplate> groupTemplates) {
		this.groupTemplates = groupTemplates;
	}

	public Boolean getIsDetailMarksPrint() {
		return isDetailMarksPrint;
	}

	public void setIsDetailMarksPrint(Boolean isDetailMarksPrint) {
		this.isDetailMarksPrint = isDetailMarksPrint;
	}

	public Set<HonorsEntryBo> getHonorsSet() {
		return honorsSet;
	}

	public void setHonorsSet(Set<HonorsEntryBo> honorsSet) {
		this.honorsSet = honorsSet;
	}

	public Set<Classes> getClasses() {
		return classes;
	}

	public void setClasses(Set<Classes> classes) {
		this.classes = classes;
	}

	public void setCertificateCourseName(String certificateCourseName) {
		this.certificateCourseName = certificateCourseName;
	}

	public String getCertificateCourseName() {
		return certificateCourseName;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankNameFull() {
		return bankNameFull;
	}

	public void setBankNameFull(String bankNameFull) {
		this.bankNameFull = bankNameFull;
	}

	public Boolean getIsWorkExperienceMandatory() {
		return isWorkExperienceMandatory;
	}

	public void setIsWorkExperienceMandatory(Boolean isWorkExperienceMandatory) {
		this.isWorkExperienceMandatory = isWorkExperienceMandatory;
	}

	public Boolean getIsAppearInOnline() {
		return isAppearInOnline;
	}

	public void setIsAppearInOnline(Boolean isAppearInOnline) {
		this.isAppearInOnline = isAppearInOnline;
	}

	public Boolean getBankIncludeSection() {
		return bankIncludeSection;
	}

	public void setBankIncludeSection(Boolean bankIncludeSection) {
		this.bankIncludeSection = bankIncludeSection;
	}

	public Boolean getIsApplicationProcessSms() {
		return isApplicationProcessSms;
	}

	public void setIsApplicationProcessSms(Boolean isApplicationProcessSms) {
		this.isApplicationProcessSms = isApplicationProcessSms;
	}

	public Boolean getOnlyForApplication() {
		return onlyForApplication;
	}

	public void setOnlyForApplication(Boolean onlyForApplication) {
		this.onlyForApplication = onlyForApplication;
	}

	public String getCourseMarksCard() {
		return courseMarksCard;
	}

	public void setCourseMarksCard(String courseMarksCard) {
		this.courseMarksCard = courseMarksCard;
	}

	public Date getCommencementDate() {
		return commencementDate;
	}

	public void setCommencementDate(Date commencementDate) {
		this.commencementDate = commencementDate;
	}

	public BigDecimal getApplicationFees() {
		return applicationFees;
	}

	public void setApplicationFees(BigDecimal applicationFees) {
		this.applicationFees = applicationFees;
	}

	public Currency getCurrencyId() {
		return currencyId;
	}

	public void setCurrencyId(Currency currencyId) {
		this.currencyId = currencyId;
	}

	public EmployeeWorkLocationBO getWorkLocation() {
		return workLocation;
	}

	public void setWorkLocation(EmployeeWorkLocationBO workLocation) {
		this.workLocation = workLocation;
	}

	public Integer getNoOfAttemtsMidSem() {
		return noOfAttemtsMidSem;
	}

	public void setNoOfAttemtsMidSem(Integer noOfAttemtsMidSem) {
		this.noOfAttemtsMidSem = noOfAttemtsMidSem;
	}

	public void setCommunityDateTime(String communityDateTime) {
		this.communityDateTime = communityDateTime;
	}

	public String getCommunityDateTime() {
		return communityDateTime;
	}

	public void setCasteDateTime(String casteDateTime) {
		this.casteDateTime = casteDateTime;
	}

	public String getCasteDateTime() {
		return casteDateTime;
	}

	public String getChanceGenDateTime() {
		return chanceGenDateTime;
	}

	public void setChanceGenDateTime(String chanceGenDateTime) {
		this.chanceGenDateTime = chanceGenDateTime;
	}

	public String getChanceCommDateTime() {
		return chanceCommDateTime;
	}

	public void setChanceCommDateTime(String chanceCommDateTime) {
		this.chanceCommDateTime = chanceCommDateTime;
	}

	public String getChanceCasteDateTime() {
		return chanceCasteDateTime;
	}

	public void setChanceCasteDateTime(String chanceCasteDateTime) {
		this.chanceCasteDateTime = chanceCasteDateTime;
	}

	public Boolean getIsSelfFinancing() {
		return isSelfFinancing;
	}

	public void setIsSelfFinancing(Boolean isSelfFinancing) {
		this.isSelfFinancing = isSelfFinancing;
	}

	public Integer getCourseOrder() {
		return courseOrder;
	}

	public void setCourseOrder(Integer courseOrder) {
		this.courseOrder = courseOrder;
	}
	
}
