package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CourseScheme generated by hbm2java
 */
public class CourseScheme implements java.io.Serializable {

	private int id;
	private String name;
	private boolean isActive;
	private Date createdDate;
	private Date lastModifiedDate;
	private String createdBy;;
	private String modifiedBy;
	
	private Set<CurriculumScheme> curriculumSchemes = new HashSet<CurriculumScheme>(
			0);
	private Set<ApplicantMarksDetails> applicantMarksDetailses = new HashSet<ApplicantMarksDetails>(
			0);
	public CourseScheme() {
	}

	public CourseScheme(int id) {
		this.id = id;
	}

	public CourseScheme(int id, String name,
			Set<ApplicantMarksDetails> applicantMarksDetailses,
			Set<CurriculumScheme> curriculumSchemes) {
		this.id = id;
		this.name = name;
		this.curriculumSchemes = curriculumSchemes;
		this.applicantMarksDetailses = applicantMarksDetailses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
	public boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set<CurriculumScheme> getCurriculumSchemes() {
		return this.curriculumSchemes;
	}

	public void setCurriculumSchemes(Set<CurriculumScheme> curriculumSchemes) {
		this.curriculumSchemes = curriculumSchemes;
	}
	public Set<ApplicantMarksDetails> getApplicantMarksDetailses() {
		return this.applicantMarksDetailses;
	}

	public void setApplicantMarksDetailses(
			Set<ApplicantMarksDetails> applicantMarksDetailses) {
		this.applicantMarksDetailses = applicantMarksDetailses;
	}
	public Date getCreatedDate() {
		return createdDate;
	}

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
}
