package com.kp.cms.bo.admin;

// Generated Apr 2, 2009 5:38:06 PM by Hibernate Tools 3.2.0.b9

/**
 * CourseApplicationNumber generated by hbm2java
 */
public class CourseApplicationNumber implements java.io.Serializable {

	private int id;
	private ApplicationNumber applicationNumber;
	private Course course;
	private Boolean isActive;

	public CourseApplicationNumber() {
	}

	public CourseApplicationNumber(int id) {
		this.id = id;
	}

	public CourseApplicationNumber(int id, ApplicationNumber applicationNumber,
			Course course) {
		this.id = id;
		this.applicationNumber = applicationNumber;
		this.course = course;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ApplicationNumber getApplicationNumber() {
		return this.applicationNumber;
	}

	public void setApplicationNumber(ApplicationNumber applicationNumber) {
		this.applicationNumber = applicationNumber;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
