package com.kp.cms.bo.admin;

// Generated Feb 11, 2009 12:21:20 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * CoursePrerequisite generated by hbm2java
 */
public class CoursePrerequisite implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private Course course;
	private Prerequisite prerequisite;
	private BigDecimal percentage;
	private Date createdDate;
	private Date lastModifiedDate;
	private Boolean isActive;

	private Weightage weightage;
	private BigDecimal weightagePercentage;
	private BigDecimal totalMark;
	
	public CoursePrerequisite() {
	}

	public CoursePrerequisite(int id) {
		this.id = id;
	}

	public CoursePrerequisite(int id, String createdBy,
			String modifiedBy, Course course,Weightage weightage,BigDecimal weightagePercentage,
			Prerequisite prerequisite, BigDecimal percentage, Date createdDate,
			Date lastModifiedDate, Boolean isActive, BigDecimal totalMark) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.course = course;
		this.prerequisite = prerequisite;
		this.percentage = percentage;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.weightage = weightage;
		this.weightagePercentage = weightagePercentage;
		this.totalMark = totalMark;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Prerequisite getPrerequisite() {
		return this.prerequisite;
	}

	public void setPrerequisite(Prerequisite prerequisite) {
		this.prerequisite = prerequisite;
	}

	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Weightage getWeightage() {
		return weightage;
	}

	public void setWeightage(Weightage weightage) {
		this.weightage = weightage;
	}

	public BigDecimal getWeightagePercentage() {
		return weightagePercentage;
	}

	public void setWeightagePercentage(BigDecimal weightagePercentage) {
		this.weightagePercentage = weightagePercentage;
	}
	
	

	public BigDecimal getTotalMark() {
		return totalMark;
	}

	public void setTotalMark(BigDecimal totalMark) {
		this.totalMark = totalMark;
	}

}
