package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CourseTermAcademicPeriod generated by hbm2java
 */
public class CourseTermAcademicPeriod implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private CourseTerm courseTerm;
	private String modifiedBy;
	private Date startDate;
	private Date endDate;
	private String status;
	private Date createdDate;
	private Date lastModifiedDate;
	private Set<Classes> classeses = new HashSet<Classes>(0);

	public CourseTermAcademicPeriod() {
	}

	public CourseTermAcademicPeriod(int id) {
		this.id = id;
	}

	public CourseTermAcademicPeriod(int id, String createdBy,
			CourseTerm courseTerm, String modifiedBy,
			Date startDate, Date endDate, String status, Date createdDate,
			Date lastModifiedDate, Set<Classes> classeses) {
		this.id = id;
		this.createdBy = createdBy;
		this.courseTerm = courseTerm;
		this.modifiedBy = modifiedBy;
		this.startDate = startDate;
		this.endDate = endDate;
		this.status = status;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.classeses = classeses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public CourseTerm getCourseTerm() {
		return this.courseTerm;
	}

	public void setCourseTerm(CourseTerm courseTerm) {
		this.courseTerm = courseTerm;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<Classes> getClasseses() {
		return this.classeses;
	}

	public void setClasseses(Set<Classes> classeses) {
		this.classeses = classeses;
	}

}
