package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import com.kp.cms.bo.admin.PersonalData;

/**
 * Currency generated by hbm2java
 */
public class Currency implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private String name;
	private String currencySubdivision;
	private String currencyCode;
	private Date createdDate;
	private Date lastModifiedDate;
	private Boolean isActive;
	private String symbol;
	private Set<FeeTransaction> feeTransactions = new HashSet<FeeTransaction>(0);
	private Set<FeeDetails> feeDetailses = new HashSet<FeeDetails>(0);
	private Set<Income> incomes = new HashSet<Income>(0);
	private Set<PersonalData> personalDatasForMotherIncomeCurrencyId = new HashSet<PersonalData>(
			0);
	private Set<PersonalData> personalDatasForFatherIncomeCurrencyId = new HashSet<PersonalData>(
			0);
	private Set<FeeAccountAssignment> feeAccountAssignmentsForCurrencyId = new HashSet<FeeAccountAssignment>(
			0);
	private Set<FeePayment> feePayments = new HashSet<FeePayment>(0);
	private Set<FeePaymentDetail> feePaymentDetails = new HashSet<FeePaymentDetail>(
			0);	
	public Currency() {
	}

	public Currency(int id, Boolean isActive) {
		this.id = id;
		this.isActive = isActive;
	}

	public Currency(int id, String createdBy,
			String modifiedBy, String name,
			String currencySubdivision, String currencyCode, Date createdDate,
			Date lastModifiedDate, Boolean isActive, String symbol,
			Set<FeeTransaction> feeTransactions, Set<FeeDetails> feeDetailses,
			Set<PersonalData> personalDatasForMotherIncomeCurrencyId,
			Set<PersonalData> personalDatasForFatherIncomeCurrencyId,
			Set<Income> incomes, Set<FeePayment> feePayments, Set<FeePaymentDetail> feePaymentDetails) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.name = name;
		this.currencySubdivision = currencySubdivision;
		this.currencyCode = currencyCode;
		this.createdDate = (Date)createdDate.clone();
		this.lastModifiedDate = (Date)lastModifiedDate.clone();
		this.isActive = isActive;
		this.symbol = symbol;
		this.feeTransactions = feeTransactions;
		this.feeDetailses = feeDetailses;
		this.personalDatasForMotherIncomeCurrencyId = personalDatasForMotherIncomeCurrencyId;
		this.personalDatasForFatherIncomeCurrencyId = personalDatasForFatherIncomeCurrencyId;
		this.incomes = incomes;
		this.feePayments = feePayments;
		this.feePaymentDetails = feePaymentDetails;
	}

	public Set<FeePaymentDetail> getFeePaymentDetails() {
		return feePaymentDetails;
	}

	public void setFeePaymentDetails(Set<FeePaymentDetail> feePaymentDetails) {
		this.feePaymentDetails = feePaymentDetails;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCurrencySubdivision() {
		return this.currencySubdivision;
	}

	public void setCurrencySubdivision(String currencySubdivision) {
		this.currencySubdivision = currencySubdivision;
	}

	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public Set<FeeTransaction> getFeeTransactions() {
		return this.feeTransactions;
	}

	public void setFeeTransactions(Set<FeeTransaction> feeTransactions) {
		this.feeTransactions = feeTransactions;
	}

	public Set<FeeDetails> getFeeDetailses() {
		return this.feeDetailses;
	}

	public void setFeeDetailses(Set<FeeDetails> feeDetailses) {
		this.feeDetailses = feeDetailses;
	}

	public Set<Income> getIncomes() {
		return this.incomes;
	}

	public void setIncomes(Set<Income> incomes) {
		this.incomes = incomes;
	}
	public Set<PersonalData> getPersonalDatasForMotherIncomeCurrencyId() {
		return this.personalDatasForMotherIncomeCurrencyId;
	}

	public void setPersonalDatasForMotherIncomeCurrencyId(
			Set<PersonalData> personalDatasForMotherIncomeCurrencyId) {
		this.personalDatasForMotherIncomeCurrencyId = personalDatasForMotherIncomeCurrencyId;
	}

	public Set<PersonalData> getPersonalDatasForFatherIncomeCurrencyId() {
		return this.personalDatasForFatherIncomeCurrencyId;
	}

	public void setPersonalDatasForFatherIncomeCurrencyId(
			Set<PersonalData> personalDatasForFatherIncomeCurrencyId) {
		this.personalDatasForFatherIncomeCurrencyId = personalDatasForFatherIncomeCurrencyId;
	}

	public Set<FeeAccountAssignment> getFeeAccountAssignmentsForCurrencyId() {
		return feeAccountAssignmentsForCurrencyId;
	}

	public void setFeeAccountAssignmentsForCurrencyId(
			Set<FeeAccountAssignment> feeAccountAssignmentsForCurrencyId) {
		this.feeAccountAssignmentsForCurrencyId = feeAccountAssignmentsForCurrencyId;
	}

	public Set<FeePayment> getFeePayments() {
		return feePayments;
	}

	public void setFeePayments(Set<FeePayment> feePayments) {
		this.feePayments = feePayments;
	}

	
}
