package com.kp.cms.bo.admin;

// Generated Mar 6, 2009 1:13:59 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kp.cms.bo.employee.EmpEventVacationDepartment;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private int id;
	private String createdBy;
	private String name;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Boolean isAcademic;
	private Set<EmpOnlineResume> empOnlineResumes = new HashSet<EmpOnlineResume>(
			0);
	private Set<Employee> employees = new HashSet<Employee>(0);
	private Set<EmpAppraisal> empAppraisals = new HashSet<EmpAppraisal>(0);
	private EmployeeStreamBO employeeStreamBO;
	//added for smart card data generation of employees
	private String code;
	private Integer webId;
	private String email;
	
	
	public Department() {
	}

	public Department(int id) {
		this.id = id;
	}

	public Department(int id, String name, String createdBy, Date createdDate,String modifiedBy,
			String lastModifiedBy, Date lastModifiedDate, Boolean isActive,Boolean isAcademic,
			Set<EmpOnlineResume> empOnlineResumes, Set<Employee> employees,
			Set<EmpAppraisal> empAppraisals,EmployeeStreamBO employeeStreamBO,Integer webId, String email) {
		this.id = id;
		this.name = name;
		this.createdBy = createdBy;
		this.createdDate = (Date)createdDate.clone();
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = (Date)lastModifiedDate.clone();
		this.isActive = isActive;
		this.isAcademic = isAcademic;
		this.empOnlineResumes = empOnlineResumes;
		this.employees = employees;
		this.empAppraisals = empAppraisals;
		this.employeeStreamBO = employeeStreamBO;
		this.webId=webId;
		this.email=email;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<EmpOnlineResume> getEmpOnlineResumes() {
		return empOnlineResumes;
	}

	public void setEmpOnlineResumes(Set<EmpOnlineResume> empOnlineResumes) {
		this.empOnlineResumes = empOnlineResumes;
	}

	public Set<Employee> getEmployees() {
		return employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	public Set<EmpAppraisal> getEmpAppraisals() {
		return empAppraisals;
	}

	public void setEmpAppraisals(Set<EmpAppraisal> empAppraisals) {
		this.empAppraisals = empAppraisals;
	}

	public void setEmployeeStreamBO(EmployeeStreamBO employeeStreamBO) {
		this.employeeStreamBO = employeeStreamBO;
	}

	public EmployeeStreamBO getEmployeeStreamBO() {
		return employeeStreamBO;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Boolean getIsAcademic() {
		return isAcademic;
	}

	public void setIsAcademic(Boolean isAcademic) {
		this.isAcademic = isAcademic;
	}

	public Integer getWebId() {
		return webId;
	}

	public void setWebId(Integer webId) {
		this.webId = webId;
	}
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}


}
