package com.kp.cms.bo.admin;

// Generated Feb 10, 2009 3:07:45 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GuidelinesDoc generated by hbm2java
 */
public class DetailedSubjects implements java.io.Serializable {

	private int id;
	private String createdBy;
	private String modifiedBy;
	private Course course;
	private String subjectName;
	private Boolean isActive;
	private Date createdDate;
	private Date lastModifiedDate;
	
	private Set<EligibleSubjects> eligibleSubjectses = new HashSet<EligibleSubjects>(
			0);
	public DetailedSubjects() {
	}

	public DetailedSubjects(int id) {
		this.id = id;
	}

	public DetailedSubjects(int id, String createdBy,
			String modifiedBy, Course course,String subjectName,
			Boolean isActive, Date createdDate, Date lastModifiedDate,
			Set<EligibleSubjects> eligibleSubjectses) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.course = course;
		this.subjectName = subjectName;
		this.isActive = isActive;
		this.createdDate = (Date)createdDate.clone();
		this.lastModifiedDate = (Date)lastModifiedDate.clone();
		
		this.eligibleSubjectses = eligibleSubjectses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Date getCreatedDate() {
		return (Date)this.createdDate.clone();
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = (Date)createdDate.clone();
	}

	public Date getLastModifiedDate() {
		return (Date)this.lastModifiedDate.clone();
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = (Date)lastModifiedDate.clone();
	}

	/**
	 * @return the subjectName
	 */
	public String getSubjectName() {
		return subjectName;
	}

	/**
	 * @param subjectName the subjectName to set
	 */
	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}
	
	public Set<EligibleSubjects> getEligibleSubjectses() {
		return this.eligibleSubjectses;
	}

	public void setEligibleSubjectses(Set<EligibleSubjects> eligibleSubjectses) {
		this.eligibleSubjectses = eligibleSubjectses;
	}
}
