package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * EdnSubjectMarks generated by hbm2java
 */
public class EdnSubjectMarks implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private EdnSemesterMarks ednSemesterMarks;
	private Integer subjectId;
	private Integer maxMarks;
	private Integer marksObtained;
	private String grade;
	private Byte percentage;
	private Byte percentile;
	private String status;
	private Date createdDate;
	private Date lastModifiedDate;

	public EdnSubjectMarks() {
	}

	public EdnSubjectMarks(int id) {
		this.id = id;
	}

	public EdnSubjectMarks(int id, String createdBy,
			String modifiedBy, EdnSemesterMarks ednSemesterMarks,
			Integer subjectId, Integer maxMarks, Integer marksObtained,
			String grade, Byte percentage, Byte percentile, String status,
			Date createdDate, Date lastModifiedDate) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.ednSemesterMarks = ednSemesterMarks;
		this.subjectId = subjectId;
		this.maxMarks = maxMarks;
		this.marksObtained = marksObtained;
		this.grade = grade;
		this.percentage = percentage;
		this.percentile = percentile;
		this.status = status;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public EdnSemesterMarks getEdnSemesterMarks() {
		return this.ednSemesterMarks;
	}

	public void setEdnSemesterMarks(EdnSemesterMarks ednSemesterMarks) {
		this.ednSemesterMarks = ednSemesterMarks;
	}

	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	public Integer getMaxMarks() {
		return this.maxMarks;
	}

	public void setMaxMarks(Integer maxMarks) {
		this.maxMarks = maxMarks;
	}

	public Integer getMarksObtained() {
		return this.marksObtained;
	}

	public void setMarksObtained(Integer marksObtained) {
		this.marksObtained = marksObtained;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public Byte getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Byte percentage) {
		this.percentage = percentage;
	}

	public Byte getPercentile() {
		return this.percentile;
	}

	public void setPercentile(Byte percentile) {
		this.percentile = percentile;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
