package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EdnSemesterMarks generated by hbm2java
 */
public class EdnSemesterMarks implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private EdnQualification ednQualification;
	private Integer schemeId;
	private Integer termNo;
	private Integer maxMarks;
	private Integer marksObtained;
	private String gradeObtained;
	private Byte percentage;
	private Byte percentile;
	private String status;
	private Date createdDate;
	private Date lastModifiedDate;
	private Set<EdnSubjectMarks> ednSubjectMarkses = new HashSet<EdnSubjectMarks>(
			0);

	public EdnSemesterMarks() {
	}

	public EdnSemesterMarks(int id) {
		this.id = id;
	}

	public EdnSemesterMarks(int id, String createdBy,
			String modifiedBy, EdnQualification ednQualification,
			Integer schemeId, Integer termNo, Integer maxMarks,
			Integer marksObtained, String gradeObtained, Byte percentage,
			Byte percentile, String status, Date createdDate,
			Date lastModifiedDate, Set<EdnSubjectMarks> ednSubjectMarkses) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.ednQualification = ednQualification;
		this.schemeId = schemeId;
		this.termNo = termNo;
		this.maxMarks = maxMarks;
		this.marksObtained = marksObtained;
		this.gradeObtained = gradeObtained;
		this.percentage = percentage;
		this.percentile = percentile;
		this.status = status;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.ednSubjectMarkses = ednSubjectMarkses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public EdnQualification getEdnQualification() {
		return this.ednQualification;
	}

	public void setEdnQualification(EdnQualification ednQualification) {
		this.ednQualification = ednQualification;
	}

	public Integer getSchemeId() {
		return this.schemeId;
	}

	public void setSchemeId(Integer schemeId) {
		this.schemeId = schemeId;
	}

	public Integer getTermNo() {
		return this.termNo;
	}

	public void setTermNo(Integer termNo) {
		this.termNo = termNo;
	}

	public Integer getMaxMarks() {
		return this.maxMarks;
	}

	public void setMaxMarks(Integer maxMarks) {
		this.maxMarks = maxMarks;
	}

	public Integer getMarksObtained() {
		return this.marksObtained;
	}

	public void setMarksObtained(Integer marksObtained) {
		this.marksObtained = marksObtained;
	}

	public String getGradeObtained() {
		return this.gradeObtained;
	}

	public void setGradeObtained(String gradeObtained) {
		this.gradeObtained = gradeObtained;
	}

	public Byte getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Byte percentage) {
		this.percentage = percentage;
	}

	public Byte getPercentile() {
		return this.percentile;
	}

	public void setPercentile(Byte percentile) {
		this.percentile = percentile;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<EdnSubjectMarks> getEdnSubjectMarkses() {
		return this.ednSubjectMarkses;
	}

	public void setEdnSubjectMarkses(Set<EdnSubjectMarks> ednSubjectMarkses) {
		this.ednSubjectMarkses = ednSubjectMarkses;
	}

}
