package com.kp.cms.bo.admin;

// Generated May 18, 2009 3:06:44 PM by Hibernate Tools 3.2.0.b9

/**
 * EligibilitySubjectGroupSubjects generated by hbm2java
 */
public class EligibilitySubjectGroupSubjects implements java.io.Serializable {

	private int id;
	private DetailedSubjects detailedSubjects;
	private EligibleSubjectsGroup eligibleSubjectsGroup;

	public EligibilitySubjectGroupSubjects() {
	}

	public EligibilitySubjectGroupSubjects(int id) {
		this.id = id;
	}

	public EligibilitySubjectGroupSubjects(int id,
			DetailedSubjects detailedSubjects,
			EligibleSubjectsGroup eligibleSubjectsGroup) {
		this.id = id;
		this.detailedSubjects = detailedSubjects;
		this.eligibleSubjectsGroup = eligibleSubjectsGroup;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public DetailedSubjects getDetailedSubjects() {
		return this.detailedSubjects;
	}

	public void setDetailedSubjects(DetailedSubjects detailedSubjects) {
		this.detailedSubjects = detailedSubjects;
	}

	public EligibleSubjectsGroup getEligibleSubjectsGroup() {
		return this.eligibleSubjectsGroup;
	}

	public void setEligibleSubjectsGroup(
			EligibleSubjectsGroup eligibleSubjectsGroup) {
		this.eligibleSubjectsGroup = eligibleSubjectsGroup;
	}

}
