package com.kp.cms.bo.admin;

// Generated Apr 22, 2009 12:53:16 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * EligibilityCriteria generated by hbm2java
 */
public class EligibilityCriteria implements java.io.Serializable {

	private int id;
	private Integer year;
	private Set<EligibleSubjects> eligibleSubjectses = new HashSet<EligibleSubjects>(
			0);
	private Course course;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private BigDecimal totalPercentage;
	private BigDecimal percentageWithoutLanguage;
	private Boolean isActive;

	public EligibilityCriteria() {
	}

	public EligibilityCriteria(int id) {
		this.id = id;
	}

	public EligibilityCriteria(int id,
			Integer year,
			Set<EligibleSubjects> eligibleSubjectses, Course course, String createdBy,
			Date createdDate, String modifiedBy, Date lastModifiedDate,
			BigDecimal totalPercentage, BigDecimal percentageWithoutLanguage) {
		this.id = id;
		this.year = year;
		this.eligibleSubjectses = eligibleSubjectses;
		this.course = course;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.totalPercentage = totalPercentage;
		this.percentageWithoutLanguage = percentageWithoutLanguage;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Set<EligibleSubjects> getEligibleSubjectses() {
		return this.eligibleSubjectses;
	}

	public void setEligibleSubjectses(Set<EligibleSubjects> eligibleSubjectses) {
		this.eligibleSubjectses = eligibleSubjectses;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public BigDecimal getTotalPercentage() {
		return this.totalPercentage;
	}

	public void setTotalPercentage(BigDecimal totalPercentage) {
		this.totalPercentage = totalPercentage;
	}

	public BigDecimal getPercentageWithoutLanguage() {
		return this.percentageWithoutLanguage;
	}

	public void setPercentageWithoutLanguage(
			BigDecimal percentageWithoutLanguage) {
		this.percentageWithoutLanguage = percentageWithoutLanguage;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	
}
