package com.kp.cms.bo.admin;

// Generated Apr 22, 2009 12:53:16 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;


/**
 * EligibleSubjects generated by hbm2java
 */
public class EligibleSubjects implements java.io.Serializable {

	private int id;
	private DetailedSubjects detailedSubjects;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private EligibilityCriteria eligibilityCriteria;
	private Boolean isActive;

	public EligibleSubjects() {
	}

	public EligibleSubjects(int id) {
		this.id = id;
	}

	public EligibleSubjects(int id, DetailedSubjects detailedSubjects,
			String createdBy, Date createdDate, String modifiedBy,
			Date lastModifiedDate, EligibilityCriteria eligibilityCriteria, Boolean isActive) {
		this.id = id;
		this.detailedSubjects = detailedSubjects;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.eligibilityCriteria = eligibilityCriteria;
		this.isActive = isActive; 
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public DetailedSubjects getDetailedSubjects() {
		return this.detailedSubjects;
	}

	public void setDetailedSubjects(DetailedSubjects detailedSubjects) {
		this.detailedSubjects = detailedSubjects;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public EligibilityCriteria getEligibilityCriteria() {
		return this.eligibilityCriteria;
	}

	public void setEligibilityCriteria(EligibilityCriteria eligibilityCriteria) {
		this.eligibilityCriteria = eligibilityCriteria;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	
}
