package com.kp.cms.bo.admin;

// Generated Oct 12, 2009 10:03:38 AM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * EmpDependents generated by hbm2java
 */
public class EmpDependents implements java.io.Serializable {

	private int id;
	private Employee employee;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private String dependentName;
	private String dependentRelationship;
	private Date dependantDOB;
	private String child1Name;
	private String child2Name;
	private Date child1DateOfBirth;
	private Date child2DateOfBirth;

	public EmpDependents() {
	}

	public EmpDependents(int id) {
		this.id = id;
	}

	public EmpDependents(int id, Employee employee, String createdBy,
			Date createdDate, String modifiedBy, Date lastModifiedDate,
			Boolean isActive, String dependentName,
			String dependentRelationship, String child1Name, String child2Name,
			Date child1DateOfBirth, Date child2DateOfBirth, Date dependantDOB ) {
		this.id = id;
		this.employee = employee;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.dependentName = dependentName;
		this.dependentRelationship = dependentRelationship;
		this.child1Name = child1Name;
		this.child2Name = child2Name;
		this.child1DateOfBirth = child1DateOfBirth;
		this.child2DateOfBirth = child2DateOfBirth;
		this.dependantDOB = dependantDOB;
	}

	public Date getDependantDOB() {
		return dependantDOB;
	}

	public void setDependantDOB(Date dependantDOB) {
		this.dependantDOB = dependantDOB;
	}
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getDependentName() {
		return this.dependentName;
	}

	public void setDependentName(String dependentName) {
		this.dependentName = dependentName;
	}

	public String getDependentRelationship() {
		return this.dependentRelationship;
	}

	public void setDependentRelationship(String dependentRelationship) {
		this.dependentRelationship = dependentRelationship;
	}

	public String getChild1Name() {
		return this.child1Name;
	}

	public void setChild1Name(String child1Name) {
		this.child1Name = child1Name;
	}

	public String getChild2Name() {
		return this.child2Name;
	}

	public void setChild2Name(String child2Name) {
		this.child2Name = child2Name;
	}

	public Date getChild1DateOfBirth() {
		return this.child1DateOfBirth;
	}

	public void setChild1DateOfBirth(Date child1DateOfBirth) {
		this.child1DateOfBirth = child1DateOfBirth;
	}

	public Date getChild2DateOfBirth() {
		return this.child2DateOfBirth;
	}

	public void setChild2DateOfBirth(Date child2DateOfBirth) {
		this.child2DateOfBirth = child2DateOfBirth;
	}

	@Override
	public boolean equals(Object obj) {
		EmpDependents depend=(EmpDependents)obj;
		boolean dob=false;
		boolean dName=false;
		boolean relation=false;
		if(this.dependentName==null && depend.getDependentName()==null)
			dName=true;
		else if(this.dependentName!=null && depend.getDependentName()!=null){
			if(this.dependentName.equalsIgnoreCase(depend.getDependentName()))
				dName=true;
		}
		if(this.dependentRelationship==null && depend.getDependentRelationship()==null)
			relation=true;
		else if(this.dependentRelationship!=null && depend.getDependentRelationship()!=null){
			if(this.dependentRelationship.equalsIgnoreCase(depend.getDependentRelationship()))
				relation=true;
		}
		if(this.dependantDOB==null && depend.getDependantDOB()==null)
			dob=true;
		else if(this.dependantDOB!=null && depend.getDependantDOB()!=null){
			if(this.dependantDOB.toString().equalsIgnoreCase(depend.getDependantDOB().toString()))
				dob=true;
		}
		if(dob && dName && relation && this.employee.getId()==depend.getEmployee().getId()){
			return true;
		}else
			return false;
	}
    
}