package com.kp.cms.bo.admin;

// Generated Oct 12, 2009 10:03:38 AM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EmpImmigration generated by hbm2java
 */
public class EmpImmigration implements java.io.Serializable {

	private int id;
	private Country countryByPassportCountryId;
	private Country countryByVisaCountryId;
	private Employee employee;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private String passportNo;
	private String passportStatus;
	private String passportReviewStatus;
	private Date passportIssueDate;
	private Date passportDateOfExpiry;
	private String passportComments;
	private String visaNo;
	private String visaStatus;
	private String visaReviewStatus;
	private Date visaIssueDate;
	private Date visaDateOfExpiry;
	private String visaComments;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public EmpImmigration() {
	}

	public EmpImmigration(int id) {
		this.id = id;
	}

	public EmpImmigration(int id, Country countryByPassportCountryId,
			Country countryByVisaCountryId, Employee employee,
			String createdBy, Date createdDate, String modifiedBy,
			Date lastModifiedDate, Boolean isActive, String passportNo,
			String passportStatus, String passportReviewStatus,
			Date passportIssueDate, Date passportDateOfExpiry,
			String passportComments, String visaNo, String visaStatus,
			String visaReviewStatus, Date visaIssueDate, Date visaDateOfExpiry,
			String visaComments, Set<Employee> employees) {
		this.id = id;
		this.countryByPassportCountryId = countryByPassportCountryId;
		this.countryByVisaCountryId = countryByVisaCountryId;
		this.employee = employee;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.passportNo = passportNo;
		this.passportStatus = passportStatus;
		this.passportReviewStatus = passportReviewStatus;
		this.passportIssueDate = passportIssueDate;
		this.passportDateOfExpiry = passportDateOfExpiry;
		this.passportComments = passportComments;
		this.visaNo = visaNo;
		this.visaStatus = visaStatus;
		this.visaReviewStatus = visaReviewStatus;
		this.visaIssueDate = visaIssueDate;
		this.visaDateOfExpiry = visaDateOfExpiry;
		this.visaComments = visaComments;
		this.employees = employees;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Country getCountryByPassportCountryId() {
		return this.countryByPassportCountryId;
	}

	public void setCountryByPassportCountryId(Country countryByPassportCountryId) {
		this.countryByPassportCountryId = countryByPassportCountryId;
	}

	public Country getCountryByVisaCountryId() {
		return this.countryByVisaCountryId;
	}

	public void setCountryByVisaCountryId(Country countryByVisaCountryId) {
		this.countryByVisaCountryId = countryByVisaCountryId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getPassportNo() {
		return this.passportNo;
	}

	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}

	public String getPassportStatus() {
		return this.passportStatus;
	}

	public void setPassportStatus(String passportStatus) {
		this.passportStatus = passportStatus;
	}

	public String getPassportReviewStatus() {
		return this.passportReviewStatus;
	}

	public void setPassportReviewStatus(String passportReviewStatus) {
		this.passportReviewStatus = passportReviewStatus;
	}

	public Date getPassportIssueDate() {
		return this.passportIssueDate;
	}

	public void setPassportIssueDate(Date passportIssueDate) {
		this.passportIssueDate = passportIssueDate;
	}

	public Date getPassportDateOfExpiry() {
		return this.passportDateOfExpiry;
	}

	public void setPassportDateOfExpiry(Date passportDateOfExpiry) {
		this.passportDateOfExpiry = passportDateOfExpiry;
	}

	public String getPassportComments() {
		return this.passportComments;
	}

	public void setPassportComments(String passportComments) {
		this.passportComments = passportComments;
	}

	public String getVisaNo() {
		return this.visaNo;
	}

	public void setVisaNo(String visaNo) {
		this.visaNo = visaNo;
	}

	public String getVisaStatus() {
		return this.visaStatus;
	}

	public void setVisaStatus(String visaStatus) {
		this.visaStatus = visaStatus;
	}

	public String getVisaReviewStatus() {
		return this.visaReviewStatus;
	}

	public void setVisaReviewStatus(String visaReviewStatus) {
		this.visaReviewStatus = visaReviewStatus;
	}

	public Date getVisaIssueDate() {
		return this.visaIssueDate;
	}

	public void setVisaIssueDate(Date visaIssueDate) {
		this.visaIssueDate = visaIssueDate;
	}

	public Date getVisaDateOfExpiry() {
		return this.visaDateOfExpiry;
	}

	public void setVisaDateOfExpiry(Date visaDateOfExpiry) {
		this.visaDateOfExpiry = visaDateOfExpiry;
	}

	public String getVisaComments() {
		return this.visaComments;
	}

	public void setVisaComments(String visaComments) {
		this.visaComments = visaComments;
	}

	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@Override
	public boolean equals(Object obj) {
		EmpImmigration immigration=(EmpImmigration)obj;
		boolean countryPassport=false;
		boolean countryVisa=false;
		boolean pComents=false;
		boolean pDateExpire=false;
		boolean pIssueDate=false;
		boolean passportNo=false;
		boolean pReviewStatus=false;
		boolean pStatus=false;
		boolean vComents=false;
		boolean vDateExpire=false;
		boolean vIssueDate=false;
		boolean visaNo=false;
		boolean vStatus=false;
		boolean vReviewStatus=false;
		if(this.countryByPassportCountryId==null && immigration.getCountryByPassportCountryId()==null)
			countryPassport=true;
		else if(this.countryByPassportCountryId!=null && immigration.getCountryByPassportCountryId()!=null){
			if(this.countryByPassportCountryId.getId()==immigration.getCountryByPassportCountryId().getId())
				countryPassport=true;
		}
		if(this.countryByVisaCountryId==null && immigration.getCountryByVisaCountryId()==null)
			countryVisa=true;
		else if(this.countryByVisaCountryId!=null && immigration.getCountryByVisaCountryId()!=null){
			if(this.countryByVisaCountryId.getId()==immigration.getCountryByVisaCountryId().getId())
				countryVisa=true;
		}
		if(this.passportComments==null && immigration.getPassportComments()==null)
			pComents=true;
		else if(this.passportComments!=null && immigration.getPassportComments()!=null){
			if(this.passportComments.equalsIgnoreCase(immigration.getPassportComments()))
				pComents=true;
		}
		if(this.passportNo==null && immigration.getPassportNo()==null)
			passportNo=true;
		else if(this.passportNo!=null && immigration.getPassportNo()!=null){
			if(this.passportNo.equalsIgnoreCase(immigration.getPassportNo()))
				passportNo=true;
		}
		if(this.passportStatus==null && immigration.getPassportStatus()==null)
			pStatus=true;
		else if(this.passportStatus!=null && immigration.getPassportStatus()!=null){
			if(this.passportStatus.equalsIgnoreCase(immigration.getPassportStatus()))
				pStatus=true;
		}
		if(this.passportReviewStatus==null && immigration.getPassportReviewStatus()==null)
			pReviewStatus=true;
		else if(this.passportReviewStatus!=null && immigration.getPassportReviewStatus()!=null){
			if(this.passportReviewStatus.equalsIgnoreCase(immigration.getPassportReviewStatus()))
				pReviewStatus=true;
		}
		if(this.passportDateOfExpiry==null && immigration.getPassportDateOfExpiry()==null)
			pDateExpire=true;
		else if(this.passportDateOfExpiry!=null && immigration.getPassportDateOfExpiry()!=null){
			if(this.passportDateOfExpiry.toString().equalsIgnoreCase(immigration.getPassportDateOfExpiry().toString()))
				pDateExpire=true;
		}
		if(this.passportIssueDate==null && immigration.getPassportIssueDate()==null)
			pIssueDate=true;
		else if(this.passportIssueDate!=null && immigration.getPassportIssueDate()!=null){
			if(this.passportIssueDate.toString().equalsIgnoreCase(immigration.getPassportIssueDate().toString()))
				pIssueDate=true;
		}
		if(this.visaComments==null && immigration.getVisaComments()==null)
			vComents=true;
		else if(this.visaComments!=null && immigration.getVisaComments()!=null){
			if(this.visaComments.equalsIgnoreCase(immigration.getVisaComments()))
				vComents=true;
		}
		if(this.visaStatus==null && immigration.getVisaStatus()==null)
			vStatus=true;
		else if(this.visaStatus!=null && immigration.getVisaStatus()!=null){
			if(this.visaStatus.equalsIgnoreCase(immigration.getVisaStatus()))
				vStatus=true;
		}
		if(this.visaReviewStatus==null && immigration.getVisaReviewStatus()==null)
			vReviewStatus=true;
		else if(this.visaReviewStatus!=null && immigration.getVisaReviewStatus()!=null){
			if(this.visaReviewStatus.equalsIgnoreCase(immigration.getVisaReviewStatus()))
				vReviewStatus=true;
		}
		if(this.visaNo==null && immigration.getVisaNo()==null)
			visaNo=true;
		else if(this.visaNo!=null && immigration.getVisaNo()!=null){
			if(this.visaNo.equalsIgnoreCase(immigration.getVisaNo()))
				visaNo=true;
		}
		if(this.visaDateOfExpiry==null && immigration.getVisaDateOfExpiry()==null)
			vDateExpire=true;
		else if(this.visaDateOfExpiry!=null && immigration.getVisaDateOfExpiry()!=null){
			if(this.visaDateOfExpiry.toString().equalsIgnoreCase(immigration.getVisaDateOfExpiry().toString()))
				vDateExpire=true;
		}
		if(this.visaIssueDate==null && immigration.getVisaIssueDate()==null)
			vIssueDate=true;
		else if(this.visaIssueDate!=null && immigration.getVisaIssueDate()!=null){
			if(this.visaIssueDate.toString().equalsIgnoreCase(immigration.getVisaIssueDate().toString()))
				vIssueDate=true;
		}
		if(this.employee.getId()==immigration.getEmployee().getId() && countryPassport && countryVisa && pComents && passportNo && pStatus && pReviewStatus && pDateExpire && pIssueDate && vComents && vStatus && vReviewStatus && visaNo && vDateExpire && vIssueDate){
		    return true;	
		}else
		    return false;
	}
    
}