package com.kp.cms.bo.admin;

// Generated Sep 25, 2009 3:08:41 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * EmpLeave generated by hbm2java
 */
public class EmpLeave implements java.io.Serializable {

	private int id;
	private EmpLeaveType empLeaveType;
	private Employee employee;
	private Double leavesAllocated;
	private Double leavesSanctioned;
	private Double leavesRemaining;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Integer year;
	private String month;
	
	public EmpLeave() {
	
	}
	public EmpLeave(int id, EmpLeaveType empLeaveType, Employee employee,
			Double leavesAllocated, Double leavesSanctioned,
			Double leavesRemaining, String createdBy, Date createdDate,
			String modifiedBy, Date lastModifiedDate, Boolean isActive,
			Integer year, String month) {
		super();
		this.id = id;
		this.empLeaveType = empLeaveType;
		this.employee = employee;
		this.leavesAllocated = leavesAllocated;
		this.leavesSanctioned = leavesSanctioned;
		this.leavesRemaining = leavesRemaining;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.year = year;
		this.month = month;
	}

	public EmpLeave(int id) {
		this.id = id;
	}
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public EmpLeaveType getEmpLeaveType() {
		return this.empLeaveType;
	}

	public void setEmpLeaveType(EmpLeaveType empLeaveType) {
		this.empLeaveType = empLeaveType;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}
	public Double getLeavesAllocated() {
		return leavesAllocated;
	}
	public void setLeavesAllocated(Double leavesAllocated) {
		this.leavesAllocated = leavesAllocated;
	}
	public Double getLeavesSanctioned() {
		return leavesSanctioned;
	}
	public void setLeavesSanctioned(Double leavesSanctioned) {
		this.leavesSanctioned = leavesSanctioned;
	}
	public Double getLeavesRemaining() {
		return leavesRemaining;
	}
	public void setLeavesRemaining(Double leavesRemaining) {
		this.leavesRemaining = leavesRemaining;
	}
	@Override
	public boolean equals(Object obj) {
		EmpLeave leave=(EmpLeave)obj;
		boolean empType=false;
		boolean lAllocate=false;
		boolean lRemain=false;
		boolean lSanction=false;
		boolean month=false;
		boolean year=false;
		if(this.empLeaveType==null && leave.getEmpLeaveType()==null)
			empType=true;
		else if(this.empLeaveType!=null && leave.getEmpLeaveType()!=null){
			if(this.empLeaveType.getId()==leave.getEmpLeaveType().getId()){
				empType=true;
			}
		}
		if(this.leavesAllocated==null && leave.getLeavesAllocated()==null)
			lAllocate=true;
		else if(this.leavesAllocated!=null && leave.getLeavesAllocated()!=null){
			if(this.leavesAllocated==leave.getLeavesAllocated().doubleValue())
				lAllocate=true;
		}
		if(this.leavesSanctioned==null && leave.getLeavesSanctioned()==null)
			lSanction=true;
		else if(this.leavesSanctioned!=null && leave.getLeavesSanctioned()!=null){
			if(this.leavesSanctioned==leave.getLeavesSanctioned().doubleValue())
				lSanction=true;
		}
		if(this.leavesRemaining==null && leave.getLeavesRemaining()==null)
			lRemain=true;
		else if(this.leavesRemaining!=null && leave.getLeavesRemaining()!=null){
			if(this.leavesRemaining==leave.getLeavesRemaining().doubleValue())
				lRemain=true;
		}
		if(this.month==null && leave.getMonth()==null)
			month=true;
		else if(this.month!=null && leave.getMonth()!=null){
			if(this.month.equalsIgnoreCase(leave.getMonth()))
				month=true;
		}
		if(this.year==null && leave.getYear()==null)
			year=true;
		else if(this.year!=null && leave.getYear()!=null){
			if(this.year==leave.getYear())
				year=true;
		}
		if(this.employee.getId()==leave.getEmployee().getId() && year && month && lRemain && lSanction && lAllocate && empType){
			return true;
		}else
			return false;
	}
	
}
