package com.kp.cms.bo.admin;

// Generated Mar 9, 2009 5:02:52 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kp.cms.bo.employee.EmpEducationalDetails;
import com.kp.cms.bo.employee.EmpFeeConcession;
import com.kp.cms.bo.employee.EmpFinancial;
import com.kp.cms.bo.employee.EmpImages;
import com.kp.cms.bo.employee.EmpIncentives;
import com.kp.cms.bo.employee.EmpJobTitle;
import com.kp.cms.bo.employee.EmpLoan;
import com.kp.cms.bo.employee.EmpPayAllowanceDetails;
import com.kp.cms.bo.employee.EmpPreviousExperience;
import com.kp.cms.bo.employee.EmpRemarks;
import com.kp.cms.bo.employee.EmpType;
import com.kp.cms.bo.employee.ShiftEntry;
import com.kp.cms.bo.exam.SubjectAreaBO;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Country country;
	//private EmpJobType empJobType;
	private State state;
	private EmpEducationMaster empEducationDetailses;
	private EmpAcheivement empAcheivement;
	private EmpDesiredPost empDesiredPost;
	private int id;
	private Employee employeeByReportToId;
	private Employee employeeByLeaveApproveAuthId;
	private Department department;
	private State stateByCommunicationAddressStateId;
	private State stateByPermanentAddressStateId;
	private Designation designation;
	private Designation albumDesignation;
	private Country countryByPermanentAddressCountryId;
	private Country countryByCommunicationAddressCountryId;
	private String firstName;
	private String middleName;
	private String lastName;
	private String fatherName;
	private String motherName;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Date dob;
	private Date doj;
	private String permanentAddressLine1;
	private String permanentAddressLine2;
	private String permanentAddressCity;
	private String permanentAddressZip;
	private String communicationAddressLine1;
	private String communicationAddressLine2;
	private String communicationAddressCity;
	private String communicationAddressZip;
	
	private String email;
	
	private String bloodGroup;
	private String communicationAddressStateOthers;
	private String permanentAddressStateOthers;
	private EmpImmigration empImmigration;
	private EmpWorkTime empWorkTime;
	private Nationality nationality;
	private String code;

	private String maritalStatus;
	private String gender;
	
	private String emergencyContName;
	private String relationship;
	private String emergencyMobile;
	private String emergencyHomeTelephone;
	private String emergencyWorkTelephone;
	private String workEmail;
	private String otherEmail;
	
	private String uid;
	private String panNo;
	private String currentAddressHomeTelephone1;
	private String currentAddressHomeTelephone2;
	private String currentAddressHomeTelephone3;
	private String currentAddressWorkTelephone1;
	private String currentAddressWorkTelephone2;
	private String currentAddressWorkTelephone3;
	
	private String currentAddressMobile1;
	
	private EmployeeStreamBO streamId;
	private EmployeeWorkLocationBO workLocationId;
	private Boolean isActive;
	private boolean active;
	private String fingerPrintId;
	
	
	// Mary additions
	private EmpType emptype;
	private String bankAccNo;
	private String pfNo;
	
	private String twoWheelerNo;
	private String fourWheelerNo;
	
	private String noOfPublicationsRefered;
	private String noOfPublicationsNotRefered;
	private String books;
	private String otherInfo;
	private SubjectAreaBO empSubjectArea;
	private Boolean currentlyWorking;
	private Designation currentDesignation;
	private String currentOrganization;
	private String totalExpYear;
	private String totalExpMonths;
	private QualificationLevelBO empQualificationLevel;
	private String reservationCategory;
	private Boolean teachingStaff;
	private String timeIn;
	private String timeInEnds;
	private String timeOut;
	private String saturdayTimeOut;
	private String halfDayStartTime;
	private String halfDayEndTime;
	private Date rejoinDate;
	private Date retirementDate;
	
	private String reasonOfLeaving;
	private Date dateOfResignation;
	private Date dateOfLeaving;
	private int payScale;
	private String scale;
	private String grossPay;
	//private EmpJobType emJobType;
	private PayScaleBO payScaleBo;
	private String desig;
	private String highQualifForAlbum;
	private String relevantExpMonths;
	private String relevantExpYears;
	private Religion religionId;
	private PayScaleBO payScaleId;
	private String designationName;
	private EmpJobTitle titleId;
	private String organistionName;
	private Boolean isSameAddress;
	private String smartCardNo;
	private Boolean isPunchingExcemption;
	
	//Mary additions ends
	// added for SmartCardData Generation requirement
	private Boolean isSCDataGenerated;
	private Boolean isSCDataDelivered;
	private String eligibilityTest;
	//added by smitha 
	private String eligibilityTestOther;
	private String industryFunctionalArea;
	private String handicappedDescription;
	private String emContactAddress;
	//private Employee approverId;
	private Boolean displayInWebsite;
	private String licGratuityNo;
    private Date licGratuityDate;
    private String nomineePfNo;
    private Date nomineePfDate;
    private Integer researchPapersRefereed;
	private Integer researchPapersNonRefereed;
	private Integer researchPapersProceedings;
	private Integer internationalBookPublications;
	private Integer nationalBookPublications;
	private Integer localBookPublications;
	private Integer chaptersEditedBooksInternational;
	private Integer chaptersEditedBooksNational;
	private Integer majorSponseredProjects;
	private Integer minorSponseredProjects;
	private Integer consultancy1SponseredProjects;
	private Integer consultancy2SponseredProjects;
	private Integer phdResearchGuidance;
	private Integer mphilResearchGuidance;
	private Integer trainingAttendedFdp2Weeks;
	private Integer trainingAttendedFdp1Weeks;
	private Integer internationalConferencePresentaion;
	private Integer nationalConferencePresentaion;
	private Integer regionalConferencePresentaion;
	private Integer localConferencePresentaion;
	private Department deputationToDepartmentId; 
	private Date appointmentLetterDate;
	private String referenceNumberForAppointment;
	private Date releavingOrderDate;
	private String referenceNubmerforReleaving;
	private String additionalRemarks;
	
	public Boolean getDisplayInWebsite() {
		return displayInWebsite;
	}

	public void setDisplayInWebsite(Boolean displayInWebsite) {
		this.displayInWebsite = displayInWebsite;
	}

	public PayScaleBO getPayScaleId() {
		return payScaleId;
	}

	public void setPayScaleId(PayScaleBO payScaleId) {
		this.payScaleId = payScaleId;
	}

	private Set<EmpWorkExperience> empWorkExperiences = new HashSet<EmpWorkExperience>(
			0);
	private Set<Employee> employeesForLeaveApproveAuthId = new HashSet<Employee>(0);
	private Set<StudentAppraisal> studentAppraisals = new HashSet<StudentAppraisal>(0);
	private Set<Employee> employeesForReportToId = new HashSet<Employee>(0);
	private Set<EmpSkills> empSkillses = new HashSet<EmpSkills>(0);
	private Set<EmpImmigration> empImmigrations = new HashSet<EmpImmigration>(0);
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<EmpAppraisal> empAppraisalsForAppraiserEmpId = new HashSet<EmpAppraisal>(0);
	private Set<EmpEducation> empEducations = new HashSet<EmpEducation>(0);
	private Set<EmpAcheivement> empAcheivements = new HashSet<EmpAcheivement>(0);
	private Set<EmpAppraisal> empAppraisalsForAppraiseEmpId = new HashSet<EmpAppraisal>(
			0);
	private Set<EmpAttendance> empAttendances = new HashSet<EmpAttendance>(0);
	private Set<EmpApplyLeave> empApplyLeaves = new HashSet<EmpApplyLeave>(0);
	//Mary additions
	private Set<EmpDependents> empDependentses = new HashSet<EmpDependents>(0);
	private Set<PfGratuityNominees> pfGratuityNominees = new HashSet<PfGratuityNominees>(0);
	private Set<InvLocation> invLocations = new HashSet<InvLocation>(0);
	private Set<EmpLanguage> empLanguages = new HashSet<EmpLanguage>(0);
	private Set<EmpLeave> empLeaves = new HashSet<EmpLeave>(0);
	private Set<EmpJob> empJobs = new HashSet<EmpJob>(0);

	
	//private Set<EmpEducationDetails> educationDetailsSet = new HashSet<EmpEducationDetails>();
	private Set<EmpEducationalDetails> educationalDetailsSet = new HashSet<EmpEducationalDetails>();
	private Set<EmpAcheivement> acheivementSet = new HashSet<EmpAcheivement>();
	private Set<EmpPreviousExperience> previousExpSet = new HashSet<EmpPreviousExperience>();
	//private Set<EmpPreviousOrg> previousOrgSet=new HashSet<EmpPreviousOrg>();
	private Set<EmpLoan> empLoan = new HashSet<EmpLoan>(0);
	private Set<EmpFinancial> empFinancial = new HashSet<EmpFinancial>(0);
	private Set<EmpIncentives> empIncentives = new HashSet<EmpIncentives>(0);
	private Set<EmpFeeConcession> empFeeConcession = new HashSet<EmpFeeConcession>(0);
	private Set<EmpRemarks> empRemarks = new HashSet<EmpRemarks>(0);
	private Set<EmpPayAllowanceDetails> empPayAllowance = new HashSet<EmpPayAllowanceDetails>();
	private Set<EmpImages> empImages = new HashSet<EmpImages>();
	private Set<ShiftEntry> staEntries = new HashSet<ShiftEntry>();
	// newly added by sudhir
	private String extensionNumber;
//	private Set<ExamValidationDetails> examValidationDetails = new HashSet<ExamValidationDetails>();
	//Mary additions ends.
	private Set<Employee> approverId = new HashSet<Employee>(
			0);
	
	public Employee() {
	}

	public Employee(int id) {
		this.id = id;
	}
		
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Employee(Country country, EmpJobType empJobType, State state,
			EmpEducationMaster empEducationDetailses,
			EmpAcheivement empAcheivement, EmpDesiredPost empDesiredPost,
			int id, Employee employeeByReportToId,
			Employee employeeByLeaveApproveAuthId, Department department,
			State stateByCommunicationAddressStateId,
			State stateByPermanentAddressStateId, Designation designation,
			Country countryByPermanentAddressCountryId,
			Country countryByCommunicationAddressCountryId, String firstName,
			String middleName, String lastName, String createdBy,
			Date createdDate, String modifiedBy, Date lastModifiedDate,
			Date dob, Date doj, String permanentAddressLine1,
			String permanentAddressLine2, String permanentAddressCity,
			String permanentAddressZip, String communicationAddressLine1,
			String communicationAddressLine2, String communicationAddressCity,
			String communicationAddressZip, String phone1, String phone2,
			String email, String fatherName, String bloodGroup,
			String communicationAddressStateOthers,
			String permanentAddressStateOthers, 
			EmpImmigration empImmigration, EmpWorkTime empWorkTime,
			Nationality nationality, String code, String nickName,
			String mobile, Boolean smoker, String maritalStatus,
			String gender, String drivingLicenseNo, Date licenseExpDate,
			String militaryService, String ethinicRace, String toTime,
			String city, String emergencyContName, String relationship,
			String emergencyMobile, String emergencyHomeTelephone,
			String emergencyWorkTelephone, String workEmail, String otherEmail,
			String approvalRemarks, String uid, String panNo, EmpJobTitle titleId, String relevantExpMonths,
			String relevantExpYears,
			String currentAddressHomeTelephone1,
			String currentAddressHomeTelephone2,
			String currentAddressHomeTelephone3,
			String currentAddressWorkTelephone1,
			String currentAddressWorkTelephone2,
			String currentAddressWorkTelephone3,
			String permanentAddressHomeTelephone1,
			String permanentAddressHomeTelephone2,
			String permanentAddressHomeTelephone3,
			String currentAddressMobile1, String currentAddressMobile2,
			String currentAddressMobile3, String permanentAddressMobile1,
			String permanentAddressMobile2, String permanentAddressMobile3,
			EmployeeStreamBO streamId, EmployeeWorkLocationBO workLocationId,
			Boolean isActive, boolean active, String fingerPrintId,
			String motherName, EmpType emptype, String bankAccNo, String pfNo,
			String vehicleNo, String twoWheelerNo, String fourWheelerNo,
			String panCardNo, String noOfPublicationsRefered,
			String noOfPublicationsNotRefered, String books, String otherInfo,
			SubjectAreaBO empSubjectArea, Boolean currentlyWorking,
			Designation currentDesignation, String currentOrganization,
			String totalExpYear, String totalExpMonths,
			QualificationLevelBO empQualificationLevel,
			String reservationCategory, Boolean teachingStaff, String timeIn,
			String timeInEnds, String timeOut, String saturdayTimeOut,
			String halfDayStartTime, String halfDayEndTime, Date rejoinDate,
			Date retirementDate, Date superAnnuationDate, String grade,
			String reasonOfLeaving, Date dateOfResignation,
			Date dateOfLeaving, int payScale, String scale,
			String basicPay, String hra, String da, String grossPay, String designationName, Religion religionId,
			EmpJobType emJobType, PayScaleBO payScaleBo,PayScaleBO payScaleId, String organistionName, Boolean isSameAddress,
			String smartCardNo,Boolean isPunchingExcemption,String eligibilityTest,
			Set<EmpWorkExperience> empWorkExperiences,
			Set<Employee> employeesForLeaveApproveAuthId,
			Set<StudentAppraisal> studentAppraisals,
			Set<Employee> employeesForReportToId, Set<EmpSkills> empSkillses,
			Set<EmpImmigration> empImmigrations, Set<Users> userses,
			Set<EmpAppraisal> empAppraisalsForAppraiserEmpId,
			Set<EmpEducation> empEducations,
			Set<EmpAcheivement> empAcheivements,
			Set<EmpAppraisal> empAppraisalsForAppraiseEmpId,
			Set<EmpAttendance> empAttendances,
			Set<EmpApplyLeave> empApplyLeaves,
			Set<EmpDependents> empDependentses, Set<InvLocation> invLocations,Set<PfGratuityNominees> pfGratuityNominees,
			Set<EmpLanguage> empLanguages, Set<EmpLeave> empLeaves,
			Set<EmpJob> empJobs,
			Set<EmpEducationalDetails> educationalDetailsSet,
			Set<EmpAcheivement> acheivementSet,
			Set<EmpPreviousExperience> previousExpSet,
			 Set<EmpLoan> empLoan,
			Set<EmpFinancial> empFinancial, Set<EmpIncentives> empIncentives,
			Set<EmpFeeConcession> empFeeConcession, Set<EmpRemarks> empRemarks,
			Set<EmpPayAllowanceDetails> empPayAllowance, Set<EmpImages> empImages, Set<ShiftEntry> staEntries,/* Set<ExamValidationDetails> examValidationDetails,*/
			String eligibilityTestOther, String industryFunctionalArea, String handicappedDescription, String emContactAddress, Set<Employee> approverId,String extensionNumber,
			String licGratuityNo,Date licGratuityDate,String nomineePfNo,Date nomineePfDate) {
		super();
		this.emContactAddress= emContactAddress;
		this.handicappedDescription=handicappedDescription;
		this.isPunchingExcemption=isPunchingExcemption;
		this.isSameAddress=isSameAddress;
		this.relevantExpMonths=relevantExpMonths;
		this.relevantExpYears=relevantExpYears;
		this.organistionName=organistionName;
		this.payScaleId=payScaleId;
		this.titleId=titleId;
		this.religionId=religionId;
		this.country = country;
		this.state = state;
		this.empEducationDetailses = empEducationDetailses;
		this.empAcheivement = empAcheivement;
		this.empDesiredPost = empDesiredPost;
		this.id = id;
		this.employeeByReportToId = employeeByReportToId;
		this.employeeByLeaveApproveAuthId = employeeByLeaveApproveAuthId;
		this.department = department;
		this.stateByCommunicationAddressStateId = stateByCommunicationAddressStateId;
		this.stateByPermanentAddressStateId = stateByPermanentAddressStateId;
		this.designation = designation;
		this.countryByPermanentAddressCountryId = countryByPermanentAddressCountryId;
		this.countryByCommunicationAddressCountryId = countryByCommunicationAddressCountryId;
		this.firstName = firstName;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.dob = dob;
		this.doj = doj;
		this.permanentAddressLine1 = permanentAddressLine1;
		this.permanentAddressLine2 = permanentAddressLine2;
		this.permanentAddressCity = permanentAddressCity;
		this.permanentAddressZip = permanentAddressZip;
		this.communicationAddressLine1 = communicationAddressLine1;
		this.communicationAddressLine2 = communicationAddressLine2;
		this.communicationAddressCity = communicationAddressCity;
		this.communicationAddressZip = communicationAddressZip;
		
		this.email = email;
		
		this.bloodGroup = bloodGroup;
		this.communicationAddressStateOthers = communicationAddressStateOthers;
		this.permanentAddressStateOthers = permanentAddressStateOthers;
		this.empImmigration = empImmigration;
		this.empWorkTime = empWorkTime;
		this.nationality = nationality;
		this.code = code;
		
	
		this.maritalStatus = maritalStatus;
		this.gender = gender;
		
		
		this.emergencyContName = emergencyContName;
		this.relationship = relationship;
		this.emergencyMobile = emergencyMobile;
		this.emergencyHomeTelephone = emergencyHomeTelephone;
		this.emergencyWorkTelephone = emergencyWorkTelephone;
		this.workEmail = workEmail;
		this.otherEmail = otherEmail;
		
		this.uid = uid;
		this.panNo = panNo;
		this.currentAddressHomeTelephone1 = currentAddressHomeTelephone1;
		this.currentAddressHomeTelephone2 = currentAddressHomeTelephone2;
		this.currentAddressHomeTelephone3 = currentAddressHomeTelephone3;
		this.currentAddressWorkTelephone1 = currentAddressWorkTelephone1;
		this.currentAddressWorkTelephone2 = currentAddressWorkTelephone2;
		this.currentAddressWorkTelephone3 = currentAddressWorkTelephone3;
		
		this.currentAddressMobile1 = currentAddressMobile1;
		
		this.streamId = streamId;
		this.workLocationId = workLocationId;
		this.isActive = isActive;
		this.active = active;
		this.fingerPrintId = fingerPrintId;
		
		this.emptype = emptype;
		this.bankAccNo = bankAccNo;
		this.pfNo = pfNo;
		this.twoWheelerNo = twoWheelerNo;
		this.fourWheelerNo = fourWheelerNo;
		this.noOfPublicationsRefered = noOfPublicationsRefered;
		this.noOfPublicationsNotRefered = noOfPublicationsNotRefered;
		this.books = books;
		this.otherInfo = otherInfo;
		this.empSubjectArea = empSubjectArea;
		this.currentlyWorking = currentlyWorking;
		this.currentDesignation = currentDesignation;
		this.currentOrganization = currentOrganization;
		this.totalExpYear = totalExpYear;
		this.totalExpMonths = totalExpMonths;
		this.empQualificationLevel = empQualificationLevel;
		this.reservationCategory = reservationCategory;
		this.teachingStaff = teachingStaff;
		this.timeIn = timeIn;
		this.timeInEnds = timeInEnds;
		this.timeOut = timeOut;
		this.saturdayTimeOut = saturdayTimeOut;
		this.halfDayStartTime = halfDayStartTime;
		this.halfDayEndTime = halfDayEndTime;
		this.rejoinDate = rejoinDate;
		this.retirementDate = retirementDate;
		this.reasonOfLeaving = reasonOfLeaving;
		this.dateOfResignation = dateOfResignation;
		this.dateOfLeaving = dateOfLeaving;
		this.payScale = payScale;
		this.scale = scale;
		this.grossPay = grossPay;
		
		this.payScaleBo = payScaleBo;
		this.empWorkExperiences = empWorkExperiences;
		this.employeesForLeaveApproveAuthId = employeesForLeaveApproveAuthId;
		this.studentAppraisals = studentAppraisals;
		this.employeesForReportToId = employeesForReportToId;
		this.empSkillses = empSkillses;
		this.empImmigrations = empImmigrations;
		this.userses = userses;
		this.empAppraisalsForAppraiserEmpId = empAppraisalsForAppraiserEmpId;
		this.empEducations = empEducations;
		this.empAcheivements = empAcheivements;
		this.empAppraisalsForAppraiseEmpId = empAppraisalsForAppraiseEmpId;
		this.empAttendances = empAttendances;
		this.empApplyLeaves = empApplyLeaves;
		this.empDependentses = empDependentses;
		this.invLocations = invLocations;
		this.empLanguages = empLanguages;
		this.empLeaves = empLeaves;
		this.empJobs = empJobs;
		
		this.educationalDetailsSet = educationalDetailsSet;
		this.acheivementSet = acheivementSet;
		this.previousExpSet = previousExpSet;
		
		this.empLoan = empLoan;
		this.empFinancial = empFinancial;
		this.empIncentives = empIncentives;
		this.empFeeConcession = empFeeConcession;
		this.empRemarks = empRemarks;
		this.empPayAllowance=empPayAllowance;
		this.smartCardNo=smartCardNo;
		this.empImages=empImages;
		this.staEntries=staEntries;
		this.eligibilityTest=eligibilityTest;
		this.eligibilityTestOther=eligibilityTestOther;
		this.industryFunctionalArea=industryFunctionalArea;
		this.approverId= approverId;
		this.extensionNumber = extensionNumber;
		this.licGratuityNo=licGratuityNo;
		this.licGratuityDate=licGratuityDate;
		this.nomineePfNo=nomineePfNo;
		this.nomineePfDate=nomineePfDate;
		this.pfGratuityNominees=pfGratuityNominees;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public State getStateByCommunicationAddressStateId() {
		return this.stateByCommunicationAddressStateId;
	}

	public void setStateByCommunicationAddressStateId(
			State stateByCommunicationAddressStateId) {
		this.stateByCommunicationAddressStateId = stateByCommunicationAddressStateId;
	}

	public State getStateByPermanentAddressStateId() {
		return this.stateByPermanentAddressStateId;
	}

	public void setStateByPermanentAddressStateId(
			State stateByPermanentAddressStateId) {
		this.stateByPermanentAddressStateId = stateByPermanentAddressStateId;
	}

	public Designation getDesignation() {
		return this.designation;
	}

	public void setDesignation(Designation designation) {
		this.designation = designation;
	}

	public Country getCountryByPermanentAddressCountryId() {
		return this.countryByPermanentAddressCountryId;
	}

	public void setCountryByPermanentAddressCountryId(
			Country countryByPermanentAddressCountryId) {
		this.countryByPermanentAddressCountryId = countryByPermanentAddressCountryId;
	}

	public Country getCountryByCommunicationAddressCountryId() {
		return this.countryByCommunicationAddressCountryId;
	}

	public void setCountryByCommunicationAddressCountryId(
			Country countryByCommunicationAddressCountryId) {
		this.countryByCommunicationAddressCountryId = countryByCommunicationAddressCountryId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public Date getDoj() {
		return this.doj;
	}

	public void setDoj(Date doj) {
		this.doj = doj;
	}

	public String getPermanentAddressLine1() {
		return this.permanentAddressLine1;
	}

	public void setPermanentAddressLine1(String permanentAddressLine1) {
		this.permanentAddressLine1 = permanentAddressLine1;
	}

	public String getPermanentAddressLine2() {
		return this.permanentAddressLine2;
	}

	public void setPermanentAddressLine2(String permanentAddressLine2) {
		this.permanentAddressLine2 = permanentAddressLine2;
	}

	public String getPermanentAddressCity() {
		return this.permanentAddressCity;
	}

	public void setPermanentAddressCity(String permanentAddressCity) {
		this.permanentAddressCity = permanentAddressCity;
	}

	public String getPermanentAddressZip() {
		return this.permanentAddressZip;
	}

	public void setPermanentAddressZip(String permanentAddressZip) {
		this.permanentAddressZip = permanentAddressZip;
	}

	public String getCommunicationAddressLine1() {
		return this.communicationAddressLine1;
	}

	public void setCommunicationAddressLine1(String communicationAddressLine1) {
		this.communicationAddressLine1 = communicationAddressLine1;
	}

	public String getCommunicationAddressLine2() {
		return this.communicationAddressLine2;
	}

	public void setCommunicationAddressLine2(String communicationAddressLine2) {
		this.communicationAddressLine2 = communicationAddressLine2;
	}

	public String getCommunicationAddressCity() {
		return this.communicationAddressCity;
	}

	public void setCommunicationAddressCity(String communicationAddressCity) {
		this.communicationAddressCity = communicationAddressCity;
	}

	public String getCommunicationAddressZip() {
		return this.communicationAddressZip;
	}

	public void setCommunicationAddressZip(String communicationAddressZip) {
		this.communicationAddressZip = communicationAddressZip;
	}


	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	

	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	public String getCommunicationAddressStateOthers() {
		return communicationAddressStateOthers;
	}

	public void setCommunicationAddressStateOthers(
			String communicationAddressStateOthers) {
		this.communicationAddressStateOthers = communicationAddressStateOthers;
	}

	public String getPermanentAddressStateOthers() {
		return permanentAddressStateOthers;
	}

	public void setPermanentAddressStateOthers(String permanentAddressStateOthers) {
		this.permanentAddressStateOthers = permanentAddressStateOthers;
	}


	public EmpImmigration getEmpImmigration() {
		return empImmigration;
	}

	public void setEmpImmigration(EmpImmigration empImmigration) {
		this.empImmigration = empImmigration;
	}

	public EmpWorkTime getEmpWorkTime() {
		return empWorkTime;
	}

	public void setEmpWorkTime(EmpWorkTime empWorkTime) {
		this.empWorkTime = empWorkTime;
	}

	public Nationality getNationality() {
		return nationality;
	}

	public void setNationality(Nationality nationality) {
		this.nationality = nationality;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}


	public String getMaritalStatus() {
		return maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}
	
	public String getEmergencyContName() {
		return emergencyContName;
	}

	public void setEmergencyContName(String emergencyContName) {
		this.emergencyContName = emergencyContName;
	}

	public String getRelationship() {
		return relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	public String getEmergencyMobile() {
		return emergencyMobile;
	}

	public void setEmergencyMobile(String emergencyMobile) {
		this.emergencyMobile = emergencyMobile;
	}

	public String getEmergencyHomeTelephone() {
		return emergencyHomeTelephone;
	}

	public void setEmergencyHomeTelephone(String emergencyHomeTelephone) {
		this.emergencyHomeTelephone = emergencyHomeTelephone;
	}

	public String getEmergencyWorkTelephone() {
		return emergencyWorkTelephone;
	}

	public void setEmergencyWorkTelephone(String emergencyWorkTelephone) {
		this.emergencyWorkTelephone = emergencyWorkTelephone;
	}

	public String getWorkEmail() {
		return workEmail;
	}

	public void setWorkEmail(String workEmail) {
		this.workEmail = workEmail;
	}

	public String getOtherEmail() {
		return otherEmail;
	}

	public void setOtherEmail(String otherEmail) {
		this.otherEmail = otherEmail;
	}

	public Set<EmpWorkExperience> getEmpWorkExperiences() {
		return empWorkExperiences;
	}

	public void setEmpWorkExperiences(Set<EmpWorkExperience> empWorkExperiences) {
		this.empWorkExperiences = empWorkExperiences;
	}

	public Set<StudentAppraisal> getStudentAppraisals() {
		return studentAppraisals;
	}

	public void setStudentAppraisals(Set<StudentAppraisal> studentAppraisals) {
		this.studentAppraisals = studentAppraisals;
	}

	public Set<EmpSkills> getEmpSkillses() {
		return empSkillses;
	}

	public void setEmpSkillses(Set<EmpSkills> empSkillses) {
		this.empSkillses = empSkillses;
	}

	public Set<EmpImmigration> getEmpImmigrations() {
		return empImmigrations;
	}

	public void setEmpImmigrations(Set<EmpImmigration> empImmigrations) {
		this.empImmigrations = empImmigrations;
	}

	public Set<Users> getUserses() {
		return userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	public Set<EmpAppraisal> getEmpAppraisalsForAppraiserEmpId() {
		return empAppraisalsForAppraiserEmpId;
	}

	public void setEmpAppraisalsForAppraiserEmpId(
			Set<EmpAppraisal> empAppraisalsForAppraiserEmpId) {
		this.empAppraisalsForAppraiserEmpId = empAppraisalsForAppraiserEmpId;
	}

	public Set<EmpEducation> getEmpEducations() {
		return empEducations;
	}

	public void setEmpEducations(Set<EmpEducation> empEducations) {
		this.empEducations = empEducations;
	}

	public Set<EmpAppraisal> getEmpAppraisalsForAppraiseEmpId() {
		return empAppraisalsForAppraiseEmpId;
	}

	public void setEmpAppraisalsForAppraiseEmpId(
			Set<EmpAppraisal> empAppraisalsForAppraiseEmpId) {
		this.empAppraisalsForAppraiseEmpId = empAppraisalsForAppraiseEmpId;
	}

	public Set<EmpAttendance> getEmpAttendances() {
		return empAttendances;
	}

	public void setEmpAttendances(Set<EmpAttendance> empAttendances) {
		this.empAttendances = empAttendances;
	}

	public Set<EmpApplyLeave> getEmpApplyLeaves() {
		return empApplyLeaves;
	}

	public void setEmpApplyLeaves(Set<EmpApplyLeave> empApplyLeaves) {
		this.empApplyLeaves = empApplyLeaves;
	}

	public Set<EmpDependents> getEmpDependentses() {
		return empDependentses;
	}

	public void setEmpDependentses(Set<EmpDependents> empDependentses) {
		this.empDependentses = empDependentses;
	}

	public Set<EmpLanguage> getEmpLanguages() {
		return empLanguages;
	}

	public void setEmpLanguages(Set<EmpLanguage> empLanguages) {
		this.empLanguages = empLanguages;
	}

	public Set<EmpJob> getEmpJobs() {
		return empJobs;
	}

	public void setEmpJobs(Set<EmpJob> empJobs) {
		this.empJobs = empJobs;
	}

	public Employee getEmployeeByReportToId() {
		return employeeByReportToId;
	}

	public void setEmployeeByReportToId(Employee employeeByReportToId) {
		this.employeeByReportToId = employeeByReportToId;
	}

	public Employee getEmployeeByLeaveApproveAuthId() {
		return employeeByLeaveApproveAuthId;
	}

	public void setEmployeeByLeaveApproveAuthId(
			Employee employeeByLeaveApproveAuthId) {
		this.employeeByLeaveApproveAuthId = employeeByLeaveApproveAuthId;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getPanNo() {
		return panNo;
	}

	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}

	public String getCurrentAddressHomeTelephone1() {
		return currentAddressHomeTelephone1;
	}

	public void setCurrentAddressHomeTelephone1(String currentAddressHomeTelephone1) {
		this.currentAddressHomeTelephone1 = currentAddressHomeTelephone1;
	}

	public String getCurrentAddressHomeTelephone2() {
		return currentAddressHomeTelephone2;
	}

	public void setCurrentAddressHomeTelephone2(String currentAddressHomeTelephone2) {
		this.currentAddressHomeTelephone2 = currentAddressHomeTelephone2;
	}

	public String getCurrentAddressHomeTelephone3() {
		return currentAddressHomeTelephone3;
	}

	public void setCurrentAddressHomeTelephone3(String currentAddressHomeTelephone3) {
		this.currentAddressHomeTelephone3 = currentAddressHomeTelephone3;
	}

	public String getCurrentAddressWorkTelephone1() {
		return currentAddressWorkTelephone1;
	}

	public void setCurrentAddressWorkTelephone1(String currentAddressWorkTelephone1) {
		this.currentAddressWorkTelephone1 = currentAddressWorkTelephone1;
	}

	public String getCurrentAddressWorkTelephone2() {
		return currentAddressWorkTelephone2;
	}

	public void setCurrentAddressWorkTelephone2(String currentAddressWorkTelephone2) {
		this.currentAddressWorkTelephone2 = currentAddressWorkTelephone2;
	}

	public String getCurrentAddressWorkTelephone3() {
		return currentAddressWorkTelephone3;
	}

	public void setCurrentAddressWorkTelephone3(String currentAddressWorkTelephone3) {
		this.currentAddressWorkTelephone3 = currentAddressWorkTelephone3;
	}

	public String getCurrentAddressMobile1() {
		return currentAddressMobile1;
	}

	public void setCurrentAddressMobile1(String currentAddressMobile1) {
		this.currentAddressMobile1 = currentAddressMobile1;
	}

	
	public Set<Employee> getEmployeesForLeaveApproveAuthId() {
		return employeesForLeaveApproveAuthId;
	}

	public void setEmployeesForLeaveApproveAuthId(
			Set<Employee> employeesForLeaveApproveAuthId) {
		this.employeesForLeaveApproveAuthId = employeesForLeaveApproveAuthId;
	}

	public Set<Employee> getEmployeesForReportToId() {
		return employeesForReportToId;
	}

	public void setEmployeesForReportToId(Set<Employee> employeesForReportToId) {
		this.employeesForReportToId = employeesForReportToId;
	}

	public Set<EmpLeave> getEmpLeaves() {
		return empLeaves;
	}

	public void setEmpLeaves(Set<EmpLeave> empLeaves) {
		this.empLeaves = empLeaves;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<EmpAcheivement> getEmpAcheivements() {
		return empAcheivements;
	}

	public void setEmpAcheivements(Set<EmpAcheivement> empAcheivements) {
		this.empAcheivements = empAcheivements;
	}

	public Set<InvLocation> getInvLocations() {
		return invLocations;
	}

	public void setInvLocations(Set<InvLocation> invLocations) {
		this.invLocations = invLocations;
	}

	public EmployeeStreamBO getStreamId() {
		return streamId;
	}

	public void setStreamId(EmployeeStreamBO streamId) {
		this.streamId = streamId;
	}

	public EmployeeWorkLocationBO getWorkLocationId() {
		return workLocationId;
	}

	public void setWorkLocationId(EmployeeWorkLocationBO workLocationId) {
		this.workLocationId = workLocationId;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public boolean getActive() {
		return active;
	}

	public void setFingerPrintId(String fingerPrintId) {
		this.fingerPrintId = fingerPrintId;
	}

	public String getFingerPrintId() {
		return fingerPrintId;
	}

	public EmpType getEmptype() {
		return emptype;
	}

	public void setEmptype(EmpType emptype) {
		this.emptype = emptype;
	}

	public String getBankAccNo() {
		return bankAccNo;
	}

	public void setBankAccNo(String bankAccNo) {
		this.bankAccNo = bankAccNo;
	}

	public String getPfNo() {
		return pfNo;
	}

	public void setPfNo(String pfNo) {
		this.pfNo = pfNo;
	}

	public String getTwoWheelerNo() {
		return twoWheelerNo;
	}

	public void setTwoWheelerNo(String twoWheelerNo) {
		this.twoWheelerNo = twoWheelerNo;
	}

	public String getFourWheelerNo() {
		return fourWheelerNo;
	}

	public void setFourWheelerNo(String fourWheelerNo) {
		this.fourWheelerNo = fourWheelerNo;
	}

	public String getNoOfPublicationsRefered() {
		return noOfPublicationsRefered;
	}

	public void setNoOfPublicationsRefered(String noOfPublicationsRefered) {
		this.noOfPublicationsRefered = noOfPublicationsRefered;
	}

	public String getNoOfPublicationsNotRefered() {
		return noOfPublicationsNotRefered;
	}

	public void setNoOfPublicationsNotRefered(String noOfPublicationsNotRefered) {
		this.noOfPublicationsNotRefered = noOfPublicationsNotRefered;
	}

	public String getBooks() {
		return books;
	}

	public void setBooks(String books) {
		this.books = books;
	}

	public String getOtherInfo() {
		return otherInfo;
	}

	public void setOtherInfo(String otherInfo) {
		this.otherInfo = otherInfo;
	}

	public SubjectAreaBO getEmpSubjectArea() {
		return empSubjectArea;
	}

	public void setEmpSubjectArea(SubjectAreaBO empSubjectArea) {
		this.empSubjectArea = empSubjectArea;
	}

	public Boolean isCurrentlyWorking() {
		return currentlyWorking;
	}

	public void setCurrentlyWorking(Boolean currentlyWorking) {
		this.currentlyWorking = currentlyWorking;
	}

	public Designation getCurrentDesignation() {
		return currentDesignation;
	}

	public void setCurrentDesignation(Designation currentDesignation) {
		this.currentDesignation = currentDesignation;
	}

	public String getCurrentOrganization() {
		return currentOrganization;
	}

	public void setCurrentOrganization(String currentOrganization) {
		this.currentOrganization = currentOrganization;
	}

	public String getTotalExpYear() {
		return totalExpYear;
	}

	public void setTotalExpYear(String totalExpYear) {
		this.totalExpYear = totalExpYear;
	}

	public String getTotalExpMonths() {
		return totalExpMonths;
	}

	public void setTotalExpMonths(String totalExpMonths) {
		this.totalExpMonths = totalExpMonths;
	}
	

	public Set<EmpEducationalDetails> getEducationalDetailsSet() {
		return educationalDetailsSet;
	}

	public void setEducationalDetailsSet(
			Set<EmpEducationalDetails> educationalDetailsSet) {
		this.educationalDetailsSet = educationalDetailsSet;
	}

	public Set<EmpAcheivement> getAcheivementSet() {
		return acheivementSet;
	}

	public void setAcheivementSet(Set<EmpAcheivement> acheivementSet) {
		this.acheivementSet = acheivementSet;
	}

	public Set<EmpPreviousExperience> getPreviousExpSet() {
		return previousExpSet;
	}

	public void setPreviousExpSet(Set<EmpPreviousExperience> previousExpSet) {
		this.previousExpSet = previousExpSet;
	}


	public QualificationLevelBO getEmpQualificationLevel() {
		return empQualificationLevel;
	}

	public void setEmpQualificationLevel(QualificationLevelBO empQualificationLevel) {
		this.empQualificationLevel = empQualificationLevel;
	}

	public String getReservationCategory() {
		return reservationCategory;
	}

	public void setReservationCategory(String reservationCategory) {
		this.reservationCategory = reservationCategory;
	}

	

	

	public Country getCountry() {
		return country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public EmpEducationMaster getEmpEducationDetailses() {
		return empEducationDetailses;
	}

	public void setEmpEducationDetailses(EmpEducationMaster empEducationDetailses) {
		this.empEducationDetailses = empEducationDetailses;
	}

	public EmpAcheivement getEmpAcheivement() {
		return empAcheivement;
	}

	public void setEmpAcheivement(EmpAcheivement empAcheivement) {
		this.empAcheivement = empAcheivement;
	}

	public EmpDesiredPost getEmpDesiredPost() {
		return empDesiredPost;
	}

	public void setEmpDesiredPost(EmpDesiredPost empDesiredPost) {
		this.empDesiredPost = empDesiredPost;
	}

	public String getTimeIn() {
		return timeIn;
	}

	public void setTimeIn(String timeIn) {
		this.timeIn = timeIn;
	}

	public String getTimeInEnds() {
		return timeInEnds;
	}

	public void setTimeInEnds(String timeInEnds) {
		this.timeInEnds = timeInEnds;
	}

	public String getTimeOut() {
		return timeOut;
	}

	public void setTimeOut(String timeOut) {
		this.timeOut = timeOut;
	}

	public String getSaturdayTimeOut() {
		return saturdayTimeOut;
	}

	public void setSaturdayTimeOut(String saturdayTimeOut) {
		this.saturdayTimeOut = saturdayTimeOut;
	}

	public String getHalfDayStartTime() {
		return halfDayStartTime;
	}

	public void setHalfDayStartTime(String halfDayStartTime) {
		this.halfDayStartTime = halfDayStartTime;
	}


	

	public String getHalfDayEndTime() {
		return halfDayEndTime;
	}

	public void setHalfDayEndTime(String halfDayEndTime) {
		this.halfDayEndTime = halfDayEndTime;
	}

	public Date getRejoinDate() {
		return rejoinDate;
	}

	public void setRejoinDate(Date rejoinDate) {
		this.rejoinDate = rejoinDate;
	}

	public Date getRetirementDate() {
		return retirementDate;
	}

	public void setRetirementDate(Date retirementDate) {
		this.retirementDate = retirementDate;
	}

	public String getReasonOfLeaving() {
		return reasonOfLeaving;
	}

	public void setReasonOfLeaving(String reasonOfLeaving) {
		this.reasonOfLeaving = reasonOfLeaving;
	}

	public Date getDateOfResignation() {
		return dateOfResignation;
	}

	public void setDateOfResignation(Date dateOfResignation) {
		this.dateOfResignation = dateOfResignation;
	}

	public Date getDateOfLeaving() {
		return dateOfLeaving;
	}

	public void setDateOfLeaving(Date dateOfLeaving) {
		this.dateOfLeaving = dateOfLeaving;
	}

	public Set<EmpLoan> getEmpLoan() {
		return empLoan;
	}

	public void setEmpLoan(Set<EmpLoan> empLoan) {
		this.empLoan = empLoan;
	}

	public Set<EmpFinancial> getEmpFinancial() {
		return empFinancial;
	}

	public void setEmpFinancial(Set<EmpFinancial> empFinancial) {
		this.empFinancial = empFinancial;
	}

	public Set<EmpIncentives> getEmpIncentives() {
		return empIncentives;
	}

	public void setEmpIncentives(Set<EmpIncentives> empIncentives) {
		this.empIncentives = empIncentives;
	}

	public Set<EmpFeeConcession> getEmpFeeConcession() {
		return empFeeConcession;
	}

	public void setEmpFeeConcession(Set<EmpFeeConcession> empFeeConcession) {
		this.empFeeConcession = empFeeConcession;
	}

	public Set<EmpRemarks> getEmpRemarks() {
		return empRemarks;
	}

	public void setEmpRemarks(Set<EmpRemarks> empRemarks) {
		this.empRemarks = empRemarks;
	}

	public String getScale() {
		return scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}
	
	public String getGrossPay() {
		return grossPay;
	}

	public void setGrossPay(String grossPay) {
		this.grossPay = grossPay;
	}
	
	public PayScaleBO getPayScaleBo() {
		return payScaleBo;
	}

	public void setPayScaleBo(PayScaleBO payScaleBo) {
		this.payScaleBo = payScaleBo;
	}

	public Boolean getTeachingStaff() {
		return teachingStaff;
	}

	public void setTeachingStaff(Boolean teachingStaff) {
		this.teachingStaff = teachingStaff;
	}

	public String getDesig() {
		return desig;
	}

	public void setDesig(String desig) {
		this.desig = desig;
	}

	public String getHighQualifForAlbum() {
		return highQualifForAlbum;
	}

	public void setHighQualifForAlbum(String highQualifForAlbum) {
		this.highQualifForAlbum = highQualifForAlbum;
	}

	public String getRelevantExpYears() {
		return relevantExpYears;
	}

	public void setRelevantExpYears(String relevantExpYears) {
		this.relevantExpYears = relevantExpYears;
	}

	public String getRelevantExpMonths() {
		return relevantExpMonths;
	}

	public void setRelevantExpMonths(String relevantExpMonths) {
		this.relevantExpMonths = relevantExpMonths;
	}

	

	public Set<EmpPayAllowanceDetails> getEmpPayAllowance() {
		return empPayAllowance;
	}

	public void setEmpPayAllowance(Set<EmpPayAllowanceDetails> empPayAllowance) {
		this.empPayAllowance = empPayAllowance;
	}

	public String getDesignationName() {
		return designationName;
	}

	public void setDesignationName(String designationName) {
		this.designationName = designationName;
	}

	public Religion getReligionId() {
		return religionId;
	}

	public void setReligionId(Religion religionId) {
		this.religionId = religionId;
	}

	public EmpJobTitle getTitleId() {
		return titleId;
	}

	public void setTitleId(EmpJobTitle titleId) {
		this.titleId = titleId;
	}

	public String getOrganistionName() {
		return organistionName;
	}

	public void setOrganistionName(String organistionName) {
		this.organistionName = organistionName;
	}

	public Boolean getIsSameAddress() {
		return isSameAddress;
	}

	public void setIsSameAddress(Boolean isSameAddress) {
		this.isSameAddress = isSameAddress;
	}

	public Boolean getCurrentlyWorking() {
		return currentlyWorking;
	}

	public Boolean getIsSCDataGenerated() {
		return isSCDataGenerated;
	}

	public void setIsSCDataGenerated(Boolean isSCDataGenerated) {
		this.isSCDataGenerated = isSCDataGenerated;
	}

	public Boolean getIsSCDataDelivered() {
		return isSCDataDelivered;
	}

	public void setIsSCDataDelivered(Boolean isSCDataDelivered) {
		this.isSCDataDelivered = isSCDataDelivered;
	}

	public String getSmartCardNo() {
		return smartCardNo;
	}

	public void setSmartCardNo(String smartCardNo) {
		this.smartCardNo = smartCardNo;
	}

	public int getPayScale() {
		return payScale;
	}

	public void setPayScale(int payScale) {
		this.payScale = payScale;
	}

	public Set<EmpImages> getEmpImages() {
		return empImages;
	}

	public void setEmpImages(Set<EmpImages> empImages) {
		this.empImages = empImages;
	}

	public Boolean getIsPunchingExcemption() {
		return isPunchingExcemption;
	}

	public void setIsPunchingExcemption(Boolean isPunchingExcemption) {
		this.isPunchingExcemption = isPunchingExcemption;
	}

	public Set<ShiftEntry> getStaEntries() {
		return staEntries;
	}

	public void setStaEntries(Set<ShiftEntry> staEntries) {
		this.staEntries = staEntries;
	}

	public String getEligibilityTest() {
		return eligibilityTest;
	}

	public void setEligibilityTest(String eligibilityTest) {
		this.eligibilityTest = eligibilityTest;
	}

	/*public Set<ExamValidationDetails> getExamValidationDetails() {
		return examValidationDetails;
	}

	public void setExamValidationDetails(
			Set<ExamValidationDetails> examValidationDetails) {
		this.examValidationDetails = examValidationDetails;
	}*/

	public String getMiddleName() {
		return middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getFatherName() {
		return fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public String getMotherName() {
		return motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	public String getEligibilityTestOther() {
		return eligibilityTestOther;
	}

	public void setEligibilityTestOther(String eligibilityTestOther) {
		this.eligibilityTestOther = eligibilityTestOther;
	}

	public String getIndustryFunctionalArea() {
		return industryFunctionalArea;
	}

	public void setIndustryFunctionalArea(String industryFunctionalArea) {
		this.industryFunctionalArea = industryFunctionalArea;
	}

	public String getHandicappedDescription() {
		return handicappedDescription;
	}

	public void setHandicappedDescription(String handicappedDescription) {
		this.handicappedDescription = handicappedDescription;
	}

	public String getEmContactAddress() {
		return emContactAddress;
	}

	public void setEmContactAddress(String emContactAddress) {
		this.emContactAddress = emContactAddress;
	}

	public Set<Employee> getApproverId() {
		return approverId;
	}

	public void setApproverId(Set<Employee> approverId) {
		this.approverId = approverId;
	}

	public Designation getAlbumDesignation() {
		return albumDesignation;
	}

	public void setAlbumDesignation(Designation albumDesignation) {
		this.albumDesignation = albumDesignation;
	}

	public String getExtensionNumber() {
		return extensionNumber;
	}

	public void setExtensionNumber(String extensionNumber) {
		this.extensionNumber = extensionNumber;
	}

	public String getLicGratuityNo() {
		return licGratuityNo;
	}

	public void setLicGratuityNo(String licGratuityNo) {
		this.licGratuityNo = licGratuityNo;
	}

	public Date getLicGratuityDate() {
		return licGratuityDate;
	}

	public void setLicGratuityDate(Date licGratuityDate) {
		this.licGratuityDate = licGratuityDate;
	}

	public String getNomineePfNo() {
		return nomineePfNo;
	}

	public void setNomineePfNo(String nomineePfNo) {
		this.nomineePfNo = nomineePfNo;
	}

	public Date getNomineePfDate() {
		return nomineePfDate;
	}

	public void setNomineePfDate(Date nomineePfDate) {
		this.nomineePfDate = nomineePfDate;
	}

	public Set<PfGratuityNominees> getPfGratuityNominees() {
		return pfGratuityNominees;
	}

	public void setPfGratuityNominees(Set<PfGratuityNominees> pfGratuityNominees) {
		this.pfGratuityNominees = pfGratuityNominees;
	}

	public Integer getResearchPapersRefereed() {
		return researchPapersRefereed;
	}

	public void setResearchPapersRefereed(Integer researchPapersRefereed) {
		this.researchPapersRefereed = researchPapersRefereed;
	}

	public Integer getResearchPapersNonRefereed() {
		return researchPapersNonRefereed;
	}

	public void setResearchPapersNonRefereed(Integer researchPapersNonRefereed) {
		this.researchPapersNonRefereed = researchPapersNonRefereed;
	}

	public Integer getResearchPapersProceedings() {
		return researchPapersProceedings;
	}

	public void setResearchPapersProceedings(Integer researchPapersProceedings) {
		this.researchPapersProceedings = researchPapersProceedings;
	}

	public Integer getInternationalBookPublications() {
		return internationalBookPublications;
	}

	public void setInternationalBookPublications(
			Integer internationalBookPublications) {
		this.internationalBookPublications = internationalBookPublications;
	}

	public Integer getNationalBookPublications() {
		return nationalBookPublications;
	}

	public void setNationalBookPublications(Integer nationalBookPublications) {
		this.nationalBookPublications = nationalBookPublications;
	}

	public Integer getLocalBookPublications() {
		return localBookPublications;
	}

	public void setLocalBookPublications(Integer localBookPublications) {
		this.localBookPublications = localBookPublications;
	}

	public Integer getChaptersEditedBooksInternational() {
		return chaptersEditedBooksInternational;
	}

	public void setChaptersEditedBooksInternational(
			Integer chaptersEditedBooksInternational) {
		this.chaptersEditedBooksInternational = chaptersEditedBooksInternational;
	}

	public Integer getChaptersEditedBooksNational() {
		return chaptersEditedBooksNational;
	}

	public void setChaptersEditedBooksNational(Integer chaptersEditedBooksNational) {
		this.chaptersEditedBooksNational = chaptersEditedBooksNational;
	}

	public Integer getMajorSponseredProjects() {
		return majorSponseredProjects;
	}

	public void setMajorSponseredProjects(Integer majorSponseredProjects) {
		this.majorSponseredProjects = majorSponseredProjects;
	}

	public Integer getMinorSponseredProjects() {
		return minorSponseredProjects;
	}

	public void setMinorSponseredProjects(Integer minorSponseredProjects) {
		this.minorSponseredProjects = minorSponseredProjects;
	}

	public Integer getConsultancy1SponseredProjects() {
		return consultancy1SponseredProjects;
	}

	public void setConsultancy1SponseredProjects(
			Integer consultancy1SponseredProjects) {
		this.consultancy1SponseredProjects = consultancy1SponseredProjects;
	}

	public Integer getConsultancy2SponseredProjects() {
		return consultancy2SponseredProjects;
	}

	public void setConsultancy2SponseredProjects(
			Integer consultancy2SponseredProjects) {
		this.consultancy2SponseredProjects = consultancy2SponseredProjects;
	}

	public Integer getPhdResearchGuidance() {
		return phdResearchGuidance;
	}

	public void setPhdResearchGuidance(Integer phdResearchGuidance) {
		this.phdResearchGuidance = phdResearchGuidance;
	}

	public Integer getMphilResearchGuidance() {
		return mphilResearchGuidance;
	}

	public void setMphilResearchGuidance(Integer mphilResearchGuidance) {
		this.mphilResearchGuidance = mphilResearchGuidance;
	}

	public Integer getTrainingAttendedFdp2Weeks() {
		return trainingAttendedFdp2Weeks;
	}

	public void setTrainingAttendedFdp2Weeks(Integer trainingAttendedFdp2Weeks) {
		this.trainingAttendedFdp2Weeks = trainingAttendedFdp2Weeks;
	}

	public Integer getTrainingAttendedFdp1Weeks() {
		return trainingAttendedFdp1Weeks;
	}

	public void setTrainingAttendedFdp1Weeks(Integer trainingAttendedFdp1Weeks) {
		this.trainingAttendedFdp1Weeks = trainingAttendedFdp1Weeks;
	}

	public Integer getInternationalConferencePresentaion() {
		return internationalConferencePresentaion;
	}

	public void setInternationalConferencePresentaion(
			Integer internationalConferencePresentaion) {
		this.internationalConferencePresentaion = internationalConferencePresentaion;
	}

	public Integer getNationalConferencePresentaion() {
		return nationalConferencePresentaion;
	}

	public void setNationalConferencePresentaion(
			Integer nationalConferencePresentaion) {
		this.nationalConferencePresentaion = nationalConferencePresentaion;
	}

	public Integer getRegionalConferencePresentaion() {
		return regionalConferencePresentaion;
	}

	public void setRegionalConferencePresentaion(
			Integer regionalConferencePresentaion) {
		this.regionalConferencePresentaion = regionalConferencePresentaion;
	}

	public Integer getLocalConferencePresentaion() {
		return localConferencePresentaion;
	}

	public void setLocalConferencePresentaion(Integer localConferencePresentaion) {
		this.localConferencePresentaion = localConferencePresentaion;
	}

	public Department getDeputationToDepartmentId() {
		return deputationToDepartmentId;
	}

	public void setDeputationToDepartmentId(Department deputationToDepartmentId) {
		this.deputationToDepartmentId = deputationToDepartmentId;
	}

	public Date getAppointmentLetterDate() {
		return appointmentLetterDate;
	}

	public void setAppointmentLetterDate(Date appointmentLetterDate) {
		this.appointmentLetterDate = appointmentLetterDate;
	}

	public String getReferenceNumberForAppointment() {
		return referenceNumberForAppointment;
	}

	public void setReferenceNumberForAppointment(
			String referenceNumberForAppointment) {
		this.referenceNumberForAppointment = referenceNumberForAppointment;
	}

	public Date getReleavingOrderDate() {
		return releavingOrderDate;
	}

	public void setReleavingOrderDate(Date releavingOrderDate) {
		this.releavingOrderDate = releavingOrderDate;
	}

	public String getReferenceNubmerforReleaving() {
		return referenceNubmerforReleaving;
	}

	public void setReferenceNubmerforReleaving(String referenceNubmerforReleaving) {
		this.referenceNubmerforReleaving = referenceNubmerforReleaving;
	}

	public String getAdditionalRemarks() {
		return additionalRemarks;
	}

	public void setAdditionalRemarks(String additionalRemarks) {
		this.additionalRemarks = additionalRemarks;
	}

	

	

	
	
}
