package com.kp.cms.bo.admin;

// Generated Sep 25, 2009 3:08:41 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

import com.kp.cms.bo.employee.EmpOnlineEducationalDetails;
import com.kp.cms.bo.employee.EmpOnlinePreviousExperience;
import com.kp.cms.bo.employee.EmployeeSubject;
import com.kp.cms.bo.exam.SubjectAreaBO;

/**
 * EmpOnlineResume generated by hbm2java
 */
@SuppressWarnings("serial")
public class EmpOnlineResume implements java.io.Serializable {

	

	private Integer id;

	private Nationality nationality;
	private Country country;
	private String empJobType;
	private Department department;
	private State state;
	private EmpEducationMaster empEducationDetailses;
	private EmpAcheivement empAcheivement;
	private EmpDesiredPost empDesiredPost;
	private String postAppliedDesig;
	private String name;
	private String addressLine1;
	private String addressLine2;
	private String addressLine3;
	private String code;
	private String gender;
	private String maritalStatus;
	private String city;
	private Date dateOfBirth;
	private String phNo1;
	private String phNo2;
	private String phNo3;
	private String workPhNo1;
	private String workPhNo2;
	private String workPhNo3;
	private Integer age;
	private String mobileNo1;
	private String mobileNo2;
	private String mobileNo3;
	private String email;
	private String employmentStatus;
	private Integer expectedSalaryLakhs;
	private Integer expectedSalaryThousands;
	private String desiredPost;
	private Date dateOfJoining;
	private String informationKnown;
	private String recommendedBy;
	private byte[] empPhoto;
	
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private String applicationNo;
	private Set<EmpEducationDetails> educationDetailsSet = new HashSet<EmpEducationDetails>();
	private Set<EmpOnlineEducationalDetails> educationalDetailsSet = new HashSet<EmpOnlineEducationalDetails>();
	private Set<EmpAcheivement> acheivementSet = new HashSet<EmpAcheivement>();
	private Set<EmpOnlinePreviousExperience> previousExpSet = new HashSet<EmpOnlinePreviousExperience>();
	private Set<EmpPreviousOrg> previousOrgSet=new HashSet<EmpPreviousOrg>();
	private String status;
	
	private String vacancyInformation;
	private Designation designation;
	private String jobCode;
	
	private String currentAddressLine1;
	private String currentAddressLine2;
	private String currentAddressLine3;
	private String currentCity;
	private State currentState;
	private Country currentCountry;
	private String permanentZipCode;
	private String currentZipCode;
	private String reservationCategory;
	private QualificationLevelBO empQualificationLevel;
	private EmpJobType emJobType;
	private String eligibilityTest;
	private Integer noOfPublicationsRefered;
	private Integer noOfPublicationsNotRefered;
	private Integer books;
	private String otherInfo; 
	private SubjectAreaBO empSubjectArea;
	private Boolean currentlyWorking;
	private String currentDesignation;
	private String currentOrganization;
	private Integer totalExpYear;
	private Integer totalExpMonths;
	private Date dateOfSubmission;
	private EmpEducationDetails empEducationDetails;
	private String currentStateOther;
	private String permanentStateOther;
	private Boolean isSameAddress;
	//added by smitha
	private String bloodGroup;
	private Religion religion;
	private String eligibilityTestOther;
	private String industryFunctionalArea;
	private String handicappedDescription;
	private Date statusDate;
	private Integer researchPapersRefereed;
	private Integer researchPapersNonRefereed;
	private Integer researchPapersProceedings;
	private Integer internationalBookPublications;
	private Integer nationalBookPublications;
	private Integer localBookPublications;
	private Integer chaptersEditedBooksInternational;
	private Integer chaptersEditedBooksNational;
	private Integer majorSponseredProjects;
	private Integer minorSponseredProjects;
	private Integer consultancy1SponseredProjects;
	private Integer consultancy2SponseredProjects;
	private Integer phdResearchGuidance;
	private Integer mphilResearchGuidance;
	private Integer trainingAttendedFdp2Weeks;
	private Integer trainingAttendedFdp1Weeks;
	private Integer internationalConferencePresentaion;
	private Integer nationalConferencePresentaion;
	private Integer regionalConferencePresentaion;
	private Integer localConferencePresentaion;
	private String fatherName;
	private String motherName;
	private String alternateMobile;
	private EmployeeSubject empSubject;
	
	public Boolean getIsSameAddress() {
		return isSameAddress;
	}
	public void setIsSameAddress(Boolean isSameAddress) {
		this.isSameAddress = isSameAddress;
	}
	public EmpOnlineResume(Integer id, Nationality nationality, Country country,
			EmpJobType emJobType, Department department,
			EmpEducationMaster empEducationDetailses,
			EmpAcheivement empAcheivement, EmpDesiredPost empDesiredPost,
			String name, String addressLine1, String addressLine2,
			String addressLine3, String code, String gender,
			String maritalStatus, String city, Date dateOfBirth, String phNo1,
			String phNo2, String phNo3, Integer age, String mobileNo1,
			String mobileNo2, String mobileNo3, String email,
			String employmentStatus, Integer expectedSalaryLakhs,
			Integer expectedSalaryThousands, String desiredPost,
			Date dateOfJoining, String informationKnown, String recommendedBy,
			byte[] empPhoto, String createdBy, Date createdDate,
			String modifiedBy, Date lastModifiedDate, Boolean isActive,String status,State state,
			String vacancyInformation,Designation designation,
			String jobCode,String currentAddressLine1,String currentAddressLine2,String currentAddressLine3,
			String currentCity,State currentState,Country currentCountry,String permanentZipCode,
			String currentZipCode,String reservationCategory,QualificationLevelBO empQualificationLevel,
			String empJobType,String eligibilityTest,Integer noOfPublicationsRefered,Integer noOfPublicationsNotRefered,
			Integer books,String otherInfo,SubjectAreaBO empSubjectArea,String applicationNo,
			Boolean currentlyWorking,String currentDesignation,String currentOrganization,
			Integer totalExpYear,Integer totalExpMonths,Date dateOfSubmission,EmpEducationDetails empEducationDetails,
			String currentStateOther, String permanentStateOther, String workPhNo1, String workPhNo2, String workPhNo3, Boolean isSameAddress
			,String bloodGroup,Religion religion,String eligibilityTestOther,String industryFunctionalArea, String handicappedDescription) {
		super();
		this.handicappedDescription=handicappedDescription;
		this.isSameAddress=isSameAddress;
		this.workPhNo1=workPhNo1;
		this.workPhNo2=workPhNo2;
		this.workPhNo3=workPhNo3;
		this.id = id;
		this.nationality = nationality;
		this.country = country;
		this.empJobType = empJobType;
		this.department = department;
		this.empEducationDetailses = empEducationDetailses;
		this.empAcheivement = empAcheivement;
		this.empDesiredPost = empDesiredPost;
		this.name = name;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressLine3 = addressLine3;
		this.code = code;
		this.gender = gender;
		this.maritalStatus = maritalStatus;
		this.city = city;
		this.dateOfBirth = dateOfBirth;
		this.phNo1 = phNo1;
		this.phNo2 = phNo2;
		this.phNo3 = phNo3;
		this.age = age;
		this.mobileNo1 = mobileNo1;
		this.mobileNo2 = mobileNo2;
		this.mobileNo3 = mobileNo3;
		this.email = email;
		this.employmentStatus = employmentStatus;
		this.expectedSalaryLakhs = expectedSalaryLakhs;
		this.expectedSalaryThousands = expectedSalaryThousands;
		this.desiredPost = desiredPost;
		this.dateOfJoining = dateOfJoining;
		this.informationKnown = informationKnown;
		this.recommendedBy = recommendedBy;
		this.empPhoto = empPhoto;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.status=status;
		this.state=state;
		this.vacancyInformation=vacancyInformation;
		this.designation=designation;
		this.jobCode=jobCode;
		this.currentAddressLine1=currentAddressLine1;
		this.currentAddressLine2=currentAddressLine2;
		this.currentAddressLine3=currentAddressLine3;
		this.currentCity=currentCity;
		this.currentState=currentState;
		this.currentCountry=currentCountry;
		this.permanentZipCode=permanentZipCode;
		this.currentZipCode=currentZipCode;
		this.reservationCategory=reservationCategory;
		this.empQualificationLevel=empQualificationLevel;
		this.emJobType=emJobType;
		this.eligibilityTest=eligibilityTest;
		this.noOfPublicationsRefered=noOfPublicationsRefered;
		this.noOfPublicationsNotRefered=noOfPublicationsNotRefered;
		this.books=books;
		this.otherInfo=otherInfo; 
		this.empSubjectArea=empSubjectArea;
		this.applicationNo=applicationNo;
		this.currentlyWorking=currentlyWorking;
		this.currentDesignation=currentDesignation;
		this.totalExpYear=totalExpYear;
		this.totalExpMonths=totalExpMonths;
		this.currentOrganization=currentOrganization;
		this.dateOfSubmission=dateOfSubmission;
		this.empEducationDetails=empEducationDetails;
		this.currentStateOther=currentStateOther;
		this.permanentStateOther=permanentStateOther;
		this.bloodGroup=bloodGroup;
		this.religion=religion;
		this.eligibilityTestOther=eligibilityTestOther;
		this.industryFunctionalArea=industryFunctionalArea;
	}
	public EmpOnlineResume() {
	}

	public EmpOnlineResume(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Nationality getNationality() {
		return this.nationality;
	}

	public void setNationality(Nationality nationality) {
		this.nationality = nationality;
	}

	

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public EmpAcheivement getEmpAcheivement() {
		return this.empAcheivement;
	}

	public void setEmpAcheivement(EmpAcheivement empAcheivement) {
		this.empAcheivement = empAcheivement;
	}

	public EmpDesiredPost getEmpDesiredPost() {
		return this.empDesiredPost;
	}

	public void setEmpDesiredPost(EmpDesiredPost empDesiredPost) {
		this.empDesiredPost = empDesiredPost;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getAddressLine3() {
		return this.addressLine3;
	}

	public void setAddressLine3(String addressLine3) {
		this.addressLine3 = addressLine3;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhNo1() {
		return this.phNo1;
	}

	public void setPhNo1(String phNo1) {
		this.phNo1 = phNo1;
	}

	public String getPhNo2() {
		return this.phNo2;
	}

	public void setPhNo2(String phNo2) {
		this.phNo2 = phNo2;
	}

	public String getPhNo3() {
		return this.phNo3;
	}

	public void setPhNo3(String phNo3) {
		this.phNo3 = phNo3;
	}

	public String getMobileNo1() {
		return this.mobileNo1;
	}

	public void setMobileNo1(String mobileNo1) {
		this.mobileNo1 = mobileNo1;
	}

	public String getMobileNo2() {
		return this.mobileNo2;
	}

	public void setMobileNo2(String mobileNo2) {
		this.mobileNo2 = mobileNo2;
	}

	public String getMobileNo3() {
		return this.mobileNo3;
	}

	public void setMobileNo3(String mobileNo3) {
		this.mobileNo3 = mobileNo3;
	}

	public String getEmploymentStatus() {
		return this.employmentStatus;
	}

	public void setEmploymentStatus(String employmentStatus) {
		this.employmentStatus = employmentStatus;
	}

	public Integer getExpectedSalaryLakhs() {
		return this.expectedSalaryLakhs;
	}

	public void setExpectedSalaryLakhs(Integer expectedSalaryLakhs) {
		this.expectedSalaryLakhs = expectedSalaryLakhs;
	}

	public Integer getExpectedSalaryThousands() {
		return this.expectedSalaryThousands;
	}

	public void setExpectedSalaryThousands(Integer expectedSalaryThousands) {
		this.expectedSalaryThousands = expectedSalaryThousands;
	}

	public String getDesiredPost() {
		return this.desiredPost;
	}

	public void setDesiredPost(String desiredPost) {
		this.desiredPost = desiredPost;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getRecommendedBy() {
		return this.recommendedBy;
	}

	public void setRecommendedBy(String recommendedBy) {
		this.recommendedBy = recommendedBy;
	}

	public String getInformationKnown() {
		return this.informationKnown;
	}

	public void setInformationKnown(String informationKnown) {
		this.informationKnown = informationKnown;
	}

	public String getEmpJobType() {
		return empJobType;
	}

	public void setEmpJobType(String empJobType) {
		this.empJobType = empJobType;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	

	public void setEmpEducationDetailses(EmpEducationMaster empEducationDetailses) {
		this.empEducationDetailses = empEducationDetailses;
	}

	public EmpEducationMaster getEmpEducationDetailses() {
		return empEducationDetailses;
	}

	public void setEmpPhoto(byte[] empPhoto) {
		this.empPhoto = empPhoto;
	}

	public byte[] getEmpPhoto() {
		return empPhoto;
	}
	public void setDateOfJoining(Date dateOfJoining) {
		this.dateOfJoining = dateOfJoining;
	}
	public Date getDateOfJoining() {
		return dateOfJoining;
	}
	public void setEducationalDetailsSet(Set<EmpOnlineEducationalDetails> educationalDetailsSet) {
		this.educationalDetailsSet = educationalDetailsSet;
	}
	public Set<EmpOnlineEducationalDetails> getEducationalDetailsSet() {
		return educationalDetailsSet;
	}
	public void setAcheivementSet(Set<EmpAcheivement> acheivementSet) {
		this.acheivementSet = acheivementSet;
	}
	public Set<EmpAcheivement> getAcheivementSet() {
		return acheivementSet;
	}
	public void setPreviousExpSet(Set<EmpOnlinePreviousExperience> previousExpSet) {
		this.previousExpSet = previousExpSet;
	}
	public Set<EmpOnlinePreviousExperience> getPreviousExpSet() {
		return previousExpSet;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public State getState() {
		return state;
	}
	public void setState(State state) {
		this.state = state;
	}
	public String getVacancyInformation() {
		return vacancyInformation;
	}
	
	public Designation getDesignation() {
		return designation;
	}
	public String getJobCode() {
		return jobCode;
	}
	public String getCurrentAddressLine1() {
		return currentAddressLine1;
	}
	public String getCurrentAddressLine2() {
		return currentAddressLine2;
	}
	public String getCurrentAddressLine3() {
		return currentAddressLine3;
	}
	public String getCurrentCity() {
		return currentCity;
	}
	public State getCurrentState() {
		return currentState;
	}
	public Country getCurrentCountry() {
		return currentCountry;
	}
	public String getPermanentZipCode() {
		return permanentZipCode;
	}
	public String getCurrentZipCode() {
		return currentZipCode;
	}
	public String getReservationCategory() {
		return reservationCategory;
	}
	public QualificationLevelBO getEmpQualificationLevel() {
		return empQualificationLevel;
	}
	public EmpJobType getEmJobType() {
		return emJobType;
	}
	public String getEligibilityTest() {
		return eligibilityTest;
	}
	public Integer getNoOfPublicationsRefered() {
		return noOfPublicationsRefered;
	}
	public Integer getNoOfPublicationsNotRefered() {
		return noOfPublicationsNotRefered;
	}
	public Integer getBooks() {
		return books;
	}
	public String getOtherInfo() {
		return otherInfo;
	}
	public void setVacancyInformation(String vacancyInformation) {
		this.vacancyInformation = vacancyInformation;
	}
	
	public void setDesignation(Designation designation) {
		this.designation = designation;
	}
	public void setJobCode(String jobCode) {
		this.jobCode = jobCode;
	}
	public void setCurrentAddressLine1(String currentAddressLine1) {
		this.currentAddressLine1 = currentAddressLine1;
	}
	public void setCurrentAddressLine2(String currentAddressLine2) {
		this.currentAddressLine2 = currentAddressLine2;
	}
	public void setCurrentAddressLine3(String currentAddressLine3) {
		this.currentAddressLine3 = currentAddressLine3;
	}
	public void setCurrentCity(String currentCity) {
		this.currentCity = currentCity;
	}
	public void setCurrentState(State currentState) {
		this.currentState = currentState;
	}
	public void setCurrentCountry(Country currentCountry) {
		this.currentCountry = currentCountry;
	}
	public void setPermanentZipCode(String permanentZipCode) {
		this.permanentZipCode = permanentZipCode;
	}
	public void setCurrentZipCode(String currentZipCode) {
		this.currentZipCode = currentZipCode;
	}
	public void setReservationCategory(String reservationCategory) {
		this.reservationCategory = reservationCategory;
	}
	public void setEmpQualificationLevel(QualificationLevelBO empQualificationLevel) {
		this.empQualificationLevel = empQualificationLevel;
	}
	public void setEmJobType(EmpJobType emJobType) {
		this.emJobType = emJobType;
	}
	public void setEligibilityTest(String eligibilityTest) {
		this.eligibilityTest = eligibilityTest;
	}
	public void setNoOfPublicationsRefered(Integer noOfPublicationsRefered) {
		this.noOfPublicationsRefered = noOfPublicationsRefered;
	}
	public void setNoOfPublicationsNotRefered(Integer noOfPublicationsNotRefered) {
		this.noOfPublicationsNotRefered = noOfPublicationsNotRefered;
	}
	public void setBooks(Integer books) {
		this.books = books;
	}
	public void setOtherInfo(String otherInfo) {
		this.otherInfo = otherInfo;
	}
	public SubjectAreaBO getEmpSubjectArea() {
		return empSubjectArea;
	}
	public void setEmpSubjectArea(SubjectAreaBO empSubjectArea) {
		this.empSubjectArea = empSubjectArea;
	}
	public String getApplicationNo() {
		return applicationNo;
	}
	public void setApplicationNo(String applicationNo) {
		this.applicationNo = applicationNo;
	}
	public Boolean isCurrentlyWorking() {
		return currentlyWorking;
	}
	public String getCurrentDesignation() {
		return currentDesignation;
	}
	public String getCurrentOrganization() {
		return currentOrganization;
	}
	public Integer getTotalExpYear() {
		return totalExpYear;
	}
	public Integer getTotalExpMonths() {
		return totalExpMonths;
	}
	public void setCurrentlyWorking(Boolean currentlyWorking) {
		this.currentlyWorking = currentlyWorking;
	}
	public void setCurrentDesignation(String currentDesignation) {
		this.currentDesignation = currentDesignation;
	}
	public void setCurrentOrganization(String currentOrganization) {
		this.currentOrganization = currentOrganization;
	}
	public void setTotalExpYear(Integer totalExpYear) {
		this.totalExpYear = totalExpYear;
	}
	public void setTotalExpMonths(Integer totalExpMonths) {
		this.totalExpMonths = totalExpMonths;
	}
	public Date getDateOfSubmission() {
		return dateOfSubmission;
	}
	public void setDateOfSubmission(Date dateOfSubmission) {
		this.dateOfSubmission = dateOfSubmission;
	}
	public Set<EmpEducationDetails> getEducationDetailsSet() {
		return educationDetailsSet;
	}
	public void setEducationDetailsSet(Set<EmpEducationDetails> educationDetailsSet) {
		this.educationDetailsSet = educationDetailsSet;
	}
	public Set<EmpPreviousOrg> getPreviousOrgSet() {
		return previousOrgSet;
	}
	public void setPreviousOrgSet(Set<EmpPreviousOrg> previousOrgSet) {
		this.previousOrgSet = previousOrgSet;
	}
	public EmpEducationDetails getEmpEducationDetails() {
		return empEducationDetails;
	}
	public void setEmpEducationDetails(EmpEducationDetails empEducationDetails) {
		this.empEducationDetails = empEducationDetails;
	}
	public String getCurrentStateOther() {
		return currentStateOther;
	}
	public String getPermanentStateOther() {
		return permanentStateOther;
	}
	public void setCurrentStateOther(String currentStateOther) {
		this.currentStateOther = currentStateOther;
	}
	public void setPermanentStateOther(String permanentStateOther) {
		this.permanentStateOther = permanentStateOther;
	}
	public String getWorkPhNo1() {
		return workPhNo1;
	}
	public void setWorkPhNo1(String workPhNo1) {
		this.workPhNo1 = workPhNo1;
	}
	public String getWorkPhNo2() {
		return workPhNo2;
	}
	public void setWorkPhNo2(String workPhNo2) {
		this.workPhNo2 = workPhNo2;
	}
	public String getWorkPhNo3() {
		return workPhNo3;
	}
	public void setWorkPhNo3(String workPhNo3) {
		this.workPhNo3 = workPhNo3;
	}
	public String getPostAppliedDesig() {
		return postAppliedDesig;
	}
	public void setPostAppliedDesig(String postAppliedDesig) {
		this.postAppliedDesig = postAppliedDesig;
	}
	public String getBloodGroup() {
		return bloodGroup;
	}
	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}
	public Religion getReligion() {
		return religion;
	}
	public void setReligion(Religion religion) {
		this.religion = religion;
	}
	public String getEligibilityTestOther() {
		return eligibilityTestOther;
	}
	public void setEligibilityTestOther(String eligibilityTestOther) {
		this.eligibilityTestOther = eligibilityTestOther;
	}
	public String getIndustryFunctionalArea() {
		return industryFunctionalArea;
	}
	public void setIndustryFunctionalArea(String industryFunctionalArea) {
		this.industryFunctionalArea = industryFunctionalArea;
	}
	public String getHandicappedDescription() {
		return handicappedDescription;
	}
	public void setHandicappedDescription(String handicappedDescription) {
		this.handicappedDescription = handicappedDescription;
	}
	public Date getStatusDate() {
		return statusDate;
	}
	public void setStatusDate(Date statusDate) {
		this.statusDate = statusDate;
	}
	public Integer getResearchPapersRefereed() {
		return researchPapersRefereed;
	}
	public void setResearchPapersRefereed(Integer researchPapersRefereed) {
		this.researchPapersRefereed = researchPapersRefereed;
	}
	public Integer getResearchPapersNonRefereed() {
		return researchPapersNonRefereed;
	}
	public void setResearchPapersNonRefereed(Integer researchPapersNonRefereed) {
		this.researchPapersNonRefereed = researchPapersNonRefereed;
	}
	public Integer getResearchPapersProceedings() {
		return researchPapersProceedings;
	}
	public void setResearchPapersProceedings(Integer researchPapersProceedings) {
		this.researchPapersProceedings = researchPapersProceedings;
	}
	public Integer getInternationalBookPublications() {
		return internationalBookPublications;
	}
	public void setInternationalBookPublications(
			Integer internationalBookPublications) {
		this.internationalBookPublications = internationalBookPublications;
	}
	public Integer getNationalBookPublications() {
		return nationalBookPublications;
	}
	public void setNationalBookPublications(Integer nationalBookPublications) {
		this.nationalBookPublications = nationalBookPublications;
	}
	public Integer getLocalBookPublications() {
		return localBookPublications;
	}
	public void setLocalBookPublications(Integer localBookPublications) {
		this.localBookPublications = localBookPublications;
	}
	public Integer getChaptersEditedBooksInternational() {
		return chaptersEditedBooksInternational;
	}
	public void setChaptersEditedBooksInternational(
			Integer chaptersEditedBooksInternational) {
		this.chaptersEditedBooksInternational = chaptersEditedBooksInternational;
	}
	public Integer getChaptersEditedBooksNational() {
		return chaptersEditedBooksNational;
	}
	public void setChaptersEditedBooksNational(Integer chaptersEditedBooksNational) {
		this.chaptersEditedBooksNational = chaptersEditedBooksNational;
	}
	public Integer getMajorSponseredProjects() {
		return majorSponseredProjects;
	}
	public void setMajorSponseredProjects(Integer majorSponseredProjects) {
		this.majorSponseredProjects = majorSponseredProjects;
	}
	public Integer getMinorSponseredProjects() {
		return minorSponseredProjects;
	}
	public void setMinorSponseredProjects(Integer minorSponseredProjects) {
		this.minorSponseredProjects = minorSponseredProjects;
	}
	public Integer getConsultancy1SponseredProjects() {
		return consultancy1SponseredProjects;
	}
	public void setConsultancy1SponseredProjects(
			Integer consultancy1SponseredProjects) {
		this.consultancy1SponseredProjects = consultancy1SponseredProjects;
	}
	public Integer getConsultancy2SponseredProjects() {
		return consultancy2SponseredProjects;
	}
	public void setConsultancy2SponseredProjects(
			Integer consultancy2SponseredProjects) {
		this.consultancy2SponseredProjects = consultancy2SponseredProjects;
	}
	public Integer getPhdResearchGuidance() {
		return phdResearchGuidance;
	}
	public void setPhdResearchGuidance(Integer phdResearchGuidance) {
		this.phdResearchGuidance = phdResearchGuidance;
	}
	public Integer getMphilResearchGuidance() {
		return mphilResearchGuidance;
	}
	public void setMphilResearchGuidance(Integer mphilResearchGuidance) {
		this.mphilResearchGuidance = mphilResearchGuidance;
	}
	public Integer getTrainingAttendedFdp2Weeks() {
		return trainingAttendedFdp2Weeks;
	}
	public void setTrainingAttendedFdp2Weeks(Integer trainingAttendedFdp2Weeks) {
		this.trainingAttendedFdp2Weeks = trainingAttendedFdp2Weeks;
	}
	public Integer getTrainingAttendedFdp1Weeks() {
		return trainingAttendedFdp1Weeks;
	}
	public void setTrainingAttendedFdp1Weeks(Integer trainingAttendedFdp1Weeks) {
		this.trainingAttendedFdp1Weeks = trainingAttendedFdp1Weeks;
	}
	public Integer getInternationalConferencePresentaion() {
		return internationalConferencePresentaion;
	}
	public void setInternationalConferencePresentaion(
			Integer internationalConferencePresentaion) {
		this.internationalConferencePresentaion = internationalConferencePresentaion;
	}
	public Integer getNationalConferencePresentaion() {
		return nationalConferencePresentaion;
	}
	public void setNationalConferencePresentaion(
			Integer nationalConferencePresentaion) {
		this.nationalConferencePresentaion = nationalConferencePresentaion;
	}
	public Integer getRegionalConferencePresentaion() {
		return regionalConferencePresentaion;
	}
	public void setRegionalConferencePresentaion(
			Integer regionalConferencePresentaion) {
		this.regionalConferencePresentaion = regionalConferencePresentaion;
	}
	public Integer getLocalConferencePresentaion() {
		return localConferencePresentaion;
	}
	public void setLocalConferencePresentaion(Integer localConferencePresentaion) {
		this.localConferencePresentaion = localConferencePresentaion;
	}
	public Boolean getCurrentlyWorking() {
		return currentlyWorking;
	}
	public String getFatherName() {
		return fatherName;
	}
	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}
	public String getMotherName() {
		return motherName;
	}
	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}
	public String getAlternateMobile() {
		return alternateMobile;
	}
	public void setAlternateMobile(String alternateMobile) {
		this.alternateMobile = alternateMobile;
	}
	public EmployeeSubject getEmpSubject() {
		return empSubject;
	}
	public void setEmpSubject(EmployeeSubject empSubject) {
		this.empSubject = empSubject;
	}

}