package com.kp.cms.bo.admin;

// Generated Mar 30, 2009 5:15:10 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * ExtracurricularActivity generated by hbm2java
 */
public class ExtracurricularActivity implements java.io.Serializable {

	private int id;
	private Organisation organisation;
	private String name;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<StudentExtracurricular> studentExtracurriculars = new HashSet<StudentExtracurricular>(
			0);
	
	public ExtracurricularActivity() {
	}

	public ExtracurricularActivity(int id) {
		this.id = id;
	}

	public ExtracurricularActivity(int id, Organisation organisation,
			String name, String createdBy, Date createdDate, String modifiedBy,
			Date lastModifiedDate, Boolean isActive,Set<StudentExtracurricular> studentExtracurriculars) {
		this.id = id;
		this.organisation = organisation;
		this.name = name;
		this.createdBy = createdBy;
		this.createdDate = (Date)createdDate.clone();
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = (Date)lastModifiedDate.clone();
		this.isActive = isActive;
		this.studentExtracurriculars = studentExtracurriculars;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
	public Set<StudentExtracurricular> getStudentExtracurriculars() {
		return this.studentExtracurriculars;
	}

	public void setStudentExtracurriculars(
			Set<StudentExtracurricular> studentExtracurriculars) {
		this.studentExtracurriculars = studentExtracurriculars;
	}
}
