package com.kp.cms.bo.admin;
// default package

import java.util.Date;

/**
 * FeeCriteria generated by hbm2java
 */
public class FeeCriteria implements java.io.Serializable {

	private Integer id;
	private College college;
	private Nationality nationality;
	private University university;
	private ResidentCategory residentCategory;
	private String secLanguage;
	private AdmittedThrough admittedThrough;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private FeeAdditional feeAdditional1;
	private FeeAdditional feeAdditional2;
	private FeeAdditional feeAdditional3;

	public FeeCriteria() {
	}

	public FeeCriteria(College college,	University university, ResidentCategory residentCategory,
			String secLanguage, AdmittedThrough admittedThrough, String createdBy,
			Date createdDate, String modifiedBy, Date lastModifiedDate, Nationality nationality,
			FeeAdditional feeAdditional1, FeeAdditional feeAdditional2, FeeAdditional feeAdditional3) {
		this.college = college;
		this.nationality = nationality;
		this.university = university;
		this.residentCategory = residentCategory;
		this.secLanguage = secLanguage;
		this.admittedThrough = admittedThrough;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.feeAdditional1 = feeAdditional1;
		this.feeAdditional2 = feeAdditional2;
		this.feeAdditional3 = feeAdditional3;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public College getCollege() {
		return college;
	}

	public void setCollege(College college) {
		this.college = college;
	}

	public Nationality getNationality() {
		return nationality;
	}

	public void setNationality(Nationality nationality) {
		this.nationality = nationality;
	}

	public University getUniversity() {
		return university;
	}

	public void setUniversity(University university) {
		this.university = university;
	}

	public ResidentCategory getResidentCategory() {
		return residentCategory;
	}

	public void setResidentCategory(ResidentCategory residentCategory) {
		this.residentCategory = residentCategory;
	}

	public String getSecLanguage() {
		return secLanguage;
	}

	public void setSecLanguage(String secLanguage) {
		this.secLanguage = secLanguage;
	}

	public AdmittedThrough getAdmittedThrough() {
		return admittedThrough;
	}

	public void setAdmittedThrough(AdmittedThrough admittedThrough) {
		this.admittedThrough = admittedThrough;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public FeeAdditional getFeeAdditional1() {
		return feeAdditional1;
	}

	public void setFeeAdditional1(FeeAdditional feeAdditional1) {
		this.feeAdditional1 = feeAdditional1;
	}

	public FeeAdditional getFeeAdditional2() {
		return feeAdditional2;
	}

	public void setFeeAdditional2(FeeAdditional feeAdditional2) {
		this.feeAdditional2 = feeAdditional2;
	}

	public FeeAdditional getFeeAdditional3() {
		return feeAdditional3;
	}

	public void setFeeAdditional3(FeeAdditional feeAdditional3) {
		this.feeAdditional3 = feeAdditional3;
	}

	
}
