package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FeeDetails generated by hbm2java
 */
public class FeeDetails implements java.io.Serializable {

	private int id;
	private Currency currency;
	private String createdBy;;
	private String modifiedBy;
	private Account account;
	private SubjectGroup subjectGroup;
	private Fee fee;
	private String name;
	private BigDecimal amount;
	private Date createdDate;
	private Date lastModifiedDate;
	private Set<FeeExcemption> feeExcemptions = new HashSet<FeeExcemption>(0);

	public FeeDetails() {
	}

	public FeeDetails(int id) {
		this.id = id;
	}

	public FeeDetails(int id, Currency currency, String createdBy,
			String modifiedBy, Account account,
			SubjectGroup subjectGroup, Fee fee, String name, BigDecimal amount,
			Date createdDate, Date lastModifiedDate,
			Set<FeeExcemption> feeExcemptions) {
		this.id = id;
		this.currency = currency;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.account = account;
		this.subjectGroup = subjectGroup;
		this.fee = fee;
		this.name = name;
		this.amount = amount;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.feeExcemptions = feeExcemptions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public SubjectGroup getSubjectGroup() {
		return this.subjectGroup;
	}

	public void setSubjectGroup(SubjectGroup subjectGroup) {
		this.subjectGroup = subjectGroup;
	}

	public Fee getFee() {
		return this.fee;
	}

	public void setFee(Fee fee) {
		this.fee = fee;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<FeeExcemption> getFeeExcemptions() {
		return this.feeExcemptions;
	}

	public void setFeeExcemptions(Set<FeeExcemption> feeExcemptions) {
		this.feeExcemptions = feeExcemptions;
	}

}
