package com.kp.cms.bo.admin;

// Generated Nov 19, 2009 6:03:43 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FeeFinancialYear generated by hbm2java
 */

public class FeeFinancialYear implements java.io.Serializable {

	private int id;
	private Boolean isCurrent;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private String year;
	private Set<FeePaymentDetail> feePaymentDetails = new HashSet<FeePaymentDetail>(
			0);
	private Set<FeeVoucher> feeVouchers = new HashSet<FeeVoucher>(0);
	private Set<FeeBillNumber> feeBillNumbers = new HashSet<FeeBillNumber>(0);
	private Set<FeePayment> feePayment = new HashSet<FeePayment>(
			0);

	public FeeFinancialYear() {
	}

	public FeeFinancialYear(int id) {
		this.id = id;
	}

	public FeeFinancialYear(int id, Boolean isCurrent, String createdBy,
			Date createdDate, String modifiedBy, Date lastModifiedDate,
			Boolean isActive, String year,
			Set<FeePaymentDetail> feePaymentDetails, Set<FeeVoucher> feeVouchers,
			Set<FeeBillNumber> feeBillNumbers) {
		this.id = id;
		this.isCurrent = isCurrent;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.year = year;
		this.feePaymentDetails = feePaymentDetails;
		this.feeVouchers = feeVouchers;
		this.feeBillNumbers = feeBillNumbers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Boolean getIsCurrent() {
		return this.isCurrent;
	}

	public void setIsCurrent(Boolean isCurrent) {
		this.isCurrent = isCurrent;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public Set<FeePaymentDetail> getFeePaymentDetails() {
		return this.feePaymentDetails;
	}

	public void setFeePaymentDetails(Set<FeePaymentDetail> feePaymentDetails) {
		this.feePaymentDetails = feePaymentDetails;
	}

	public Set<FeeVoucher> getFeeVouchers() {
		return this.feeVouchers;
	}

	public void setFeeVouchers(Set<FeeVoucher> feeVouchers) {
		this.feeVouchers = feeVouchers;
	}
	
	public Set<FeeBillNumber> getFeeBillNumbers() {
		return this.feeBillNumbers;
	}

	public void setFeeBillNumbers(Set<FeeBillNumber> feeBillNumbers) {
		this.feeBillNumbers = feeBillNumbers;
	}

	public Set<FeePayment> getFeePayment() {
		return feePayment;
	}

	public void setFeePayment(Set<FeePayment> feePayment) {
		this.feePayment = feePayment;
	}
}