package com.kp.cms.bo.admin;

// Generated Feb 5, 2009 12:58:29 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grade generated by hbm2java
 */
public class Grade implements java.io.Serializable {

	private int id;
	private String grade;
	private Integer marks;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private boolean isActive;
	private Set<InterviewResultDetail> interviewResultDetails = new HashSet<InterviewResultDetail>(
			0);
	private Set<InterviewResult> interviewResults = new HashSet<InterviewResult>(
			0);

	public Grade() {
	}

	public Grade(int id, boolean isActive) {
		this.id = id;
		this.isActive = isActive;
	}

	public Grade(int id, String grade, Integer marks, String createdBy,
			Date createdDate, String modifiedBy, Date lastModifiedDate,
			boolean isActive,
			Set<InterviewResultDetail> interviewResultDetails,
			Set<InterviewResult> interviewResults) {
		this.id = id;
		this.grade = grade;
		this.marks = marks;
		this.createdBy = createdBy;
		this.createdDate = (Date)createdDate.clone();
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = (Date)lastModifiedDate.clone();
		this.isActive = isActive;
		this.interviewResultDetails = interviewResultDetails;
		this.interviewResults = interviewResults;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public Integer getMarks() {
		return this.marks;
	}

	public void setMarks(Integer marks) {
		this.marks = marks;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set<InterviewResultDetail> getInterviewResultDetails() {
		return this.interviewResultDetails;
	}

	public void setInterviewResultDetails(
			Set<InterviewResultDetail> interviewResultDetails) {
		this.interviewResultDetails = interviewResultDetails;
	}

	public Set<InterviewResult> getInterviewResults() {
		return this.interviewResults;
	}

	public void setInterviewResults(Set<InterviewResult> interviewResults) {
		this.interviewResults = interviewResults;
	}

}
