package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private String name;
	private String description;
	private Date createdDate;
	private Date lastModifiedDate;
	private Set<GroupStudent> groupStudents = new HashSet<GroupStudent>(0);
	private Set<GroupInstructor> groupInstructors = new HashSet<GroupInstructor>(
			0);
	private Set<SessionAttendee> sessionAttendees = new HashSet<SessionAttendee>(
			0);
	private Set<SessionIncharge> sessionIncharges = new HashSet<SessionIncharge>(
			0);

	public Group() {
	}

	public Group(int id) {
		this.id = id;
	}

	public Group(int id, String createdBy,
			String modifiedBy, String name, String description,
			Date createdDate, Date lastModifiedDate,
			Set<GroupStudent> groupStudents,
			Set<GroupInstructor> groupInstructors,
			Set<SessionAttendee> sessionAttendees,
			Set<SessionIncharge> sessionIncharges) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.name = name;
		this.description = description;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.groupStudents = groupStudents;
		this.groupInstructors = groupInstructors;
		this.sessionAttendees = sessionAttendees;
		this.sessionIncharges = sessionIncharges;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<GroupStudent> getGroupStudents() {
		return this.groupStudents;
	}

	public void setGroupStudents(Set<GroupStudent> groupStudents) {
		this.groupStudents = groupStudents;
	}

	public Set<GroupInstructor> getGroupInstructors() {
		return this.groupInstructors;
	}

	public void setGroupInstructors(Set<GroupInstructor> groupInstructors) {
		this.groupInstructors = groupInstructors;
	}

	public Set<SessionAttendee> getSessionAttendees() {
		return this.sessionAttendees;
	}

	public void setSessionAttendees(Set<SessionAttendee> sessionAttendees) {
		this.sessionAttendees = sessionAttendees;
	}

	public Set<SessionIncharge> getSessionIncharges() {
		return this.sessionIncharges;
	}

	public void setSessionIncharges(Set<SessionIncharge> sessionIncharges) {
		this.sessionIncharges = sessionIncharges;
	}

}
