package com.kp.cms.bo.admin;

// Generated Dec 18, 2009 3:48:30 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * HlComplaint generated by hbm2java
 */
public class HlComplaint implements java.io.Serializable {

	private int id;
	private HlComplaintType hlComplaintType;
	private HlHostel hlHostel;
	private HlStatus hlStatus;
	private HlApplicationForm hlApplicationForm;
	private Employee employee;
	private Date date;
	private String subject;
	private String description;
	private String actionTaken;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Date approvedDate;
	private String approvedBy;
	public HlComplaint() {
	}

	public HlComplaint(int id) {
		this.id = id;
	}

	public HlComplaint(int id, HlComplaintType hlComplaintType,
			HlHostel hlHostel, HlStatus hlStatus,
			HlApplicationForm hlApplicationForm, Employee employee, Date date,
			String subject, String description, String actionTaken,
			String createdBy, Date createdDate, String modifiedBy,
			Date lastModifiedDate, Boolean isActive) {
		this.id = id;
		this.hlComplaintType = hlComplaintType;
		this.hlHostel = hlHostel;
		this.hlStatus = hlStatus;
		this.hlApplicationForm = hlApplicationForm;
		this.employee = employee;
		this.date = date;
		this.subject = subject;
		this.description = description;
		this.actionTaken = actionTaken;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public HlComplaintType getHlComplaintType() {
		return this.hlComplaintType;
	}

	public void setHlComplaintType(HlComplaintType hlComplaintType) {
		this.hlComplaintType = hlComplaintType;
	}

	public HlHostel getHlHostel() {
		return this.hlHostel;
	}

	public void setHlHostel(HlHostel hlHostel) {
		this.hlHostel = hlHostel;
	}

	public HlStatus getHlStatus() {
		return this.hlStatus;
	}

	public void setHlStatus(HlStatus hlStatus) {
		this.hlStatus = hlStatus;
	}

	public HlApplicationForm getHlApplicationForm() {
		return this.hlApplicationForm;
	}

	public void setHlApplicationForm(HlApplicationForm hlApplicationForm) {
		this.hlApplicationForm = hlApplicationForm;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getActionTaken() {
		return this.actionTaken;
	}

	public void setActionTaken(String actionTaken) {
		this.actionTaken = actionTaken;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Date getApprovedDate() {
		return approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	public String getApprovedBy() {
		return approvedBy;
	}

	public void setApprovedBy(String approvedBy) {
		this.approvedBy = approvedBy;
	}
	
}
