package com.kp.cms.bo.admin;

// Generated Dec 18, 2009 3:48:30 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * HlFloorRoom generated by hbm2java
 */
public class HlFloorRoom implements java.io.Serializable {

	private int id;
	private HlHostel hlHostel;
	private HlRoomType hlRoomType;
	private String floorNo;
	private Integer noOfRooms;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;

	public HlFloorRoom() {
	}

	public HlFloorRoom(int id) {
		this.id = id;
	}

	public HlFloorRoom(int id, HlHostel hlHostel, HlRoomType hlRoomType,
			String floorNo, Integer noOfRooms, String createdBy,
			Date createdDate, String modifiedBy, Date lastModifiedDate,
			Boolean isActive) {
		this.id = id;
		this.hlHostel = hlHostel;
		this.hlRoomType = hlRoomType;
		this.floorNo = floorNo;
		this.noOfRooms = noOfRooms;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public HlHostel getHlHostel() {
		return this.hlHostel;
	}

	public void setHlHostel(HlHostel hlHostel) {
		this.hlHostel = hlHostel;
	}

	public HlRoomType getHlRoomType() {
		return this.hlRoomType;
	}

	public void setHlRoomType(HlRoomType hlRoomType) {
		this.hlRoomType = hlRoomType;
	}

	public String getFloorNo() {
		return this.floorNo;
	}

	public void setFloorNo(String floorNo) {
		this.floorNo = floorNo;
	}

	public Integer getNoOfRooms() {
		return this.noOfRooms;
	}

	public void setNoOfRooms(Integer noOfRooms) {
		this.noOfRooms = noOfRooms;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
