package com.kp.cms.bo.admin;

// Generated Dec 18, 2009 3:48:30 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HlRoomTransaction generated by hbm2java
 */
public class HlRoomTransaction implements java.io.Serializable {

	private int id;
	private HlStatus hlStatus;
	private HlRoom hlRoom;
	private HlApplicationForm hlApplicationForm;
	private AdmAppln admAppln;
	private Employee employee;
	private Date txnDate;
	private Integer currentOccupantsCount;
	private Integer bedNo;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private String comments;
	private String remarks;
	private Set<HlCheckinCheckoutFacility> hlCheckinCheckoutFacilities = new HashSet<HlCheckinCheckoutFacility>(
			0);
	private Integer currentReservationCount;

	public HlRoomTransaction() {
	}

	public HlRoomTransaction(int id) {
		this.id = id;
	}

	public HlRoomTransaction(int id, HlStatus hlStatus, HlRoom hlRoom,
			HlApplicationForm hlApplicationForm, AdmAppln admAppln,
			Employee employee, Date txnDate, Integer currentOccupantsCount,
			Integer bedNo, String createdBy, Date createdDate,
			String modifiedBy, Date lastModifiedDate, Boolean isActive,
			String comments, String remarks,
			Set<HlCheckinCheckoutFacility> hlCheckinCheckoutFacilities,Integer currentReservationCount) {
		this.id = id;
		this.hlStatus = hlStatus;
		this.hlRoom = hlRoom;
		this.hlApplicationForm = hlApplicationForm;
		this.admAppln = admAppln;
		this.employee = employee;
		this.txnDate = txnDate;
		this.currentOccupantsCount = currentOccupantsCount;
		this.bedNo = bedNo;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.comments = comments;
		this.remarks = remarks;
		this.hlCheckinCheckoutFacilities = hlCheckinCheckoutFacilities;
		this.currentReservationCount=currentReservationCount;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public HlStatus getHlStatus() {
		return this.hlStatus;
	}

	public void setHlStatus(HlStatus hlStatus) {
		this.hlStatus = hlStatus;
	}

	public HlRoom getHlRoom() {
		return this.hlRoom;
	}

	public void setHlRoom(HlRoom hlRoom) {
		this.hlRoom = hlRoom;
	}

	public HlApplicationForm getHlApplicationForm() {
		return this.hlApplicationForm;
	}

	public void setHlApplicationForm(HlApplicationForm hlApplicationForm) {
		this.hlApplicationForm = hlApplicationForm;
	}

	public AdmAppln getAdmAppln() {
		return this.admAppln;
	}

	public void setAdmAppln(AdmAppln admAppln) {
		this.admAppln = admAppln;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Date getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	public Integer getCurrentOccupantsCount() {
		return this.currentOccupantsCount;
	}

	public void setCurrentOccupantsCount(Integer currentOccupantsCount) {
		this.currentOccupantsCount = currentOccupantsCount;
	}

	public Integer getBedNo() {
		return this.bedNo;
	}

	public void setBedNo(Integer bedNo) {
		this.bedNo = bedNo;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Set<HlCheckinCheckoutFacility> getHlCheckinCheckoutFacilities() {
		return this.hlCheckinCheckoutFacilities;
	}

	public void setHlCheckinCheckoutFacilities(
			Set<HlCheckinCheckoutFacility> hlCheckinCheckoutFacilities) {
		this.hlCheckinCheckoutFacilities = hlCheckinCheckoutFacilities;
	}

	public Integer getCurrentReservationCount() {
		return currentReservationCount;
	}

	public void setCurrentReservationCount(Integer currentReservationCount) {
		this.currentReservationCount = currentReservationCount;
	}

}
