package com.kp.cms.bo.admin;

// Generated Dec 18, 2009 3:48:30 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HlRoom generated by hbm2java
 */
public class HlRoom implements java.io.Serializable{

	private int id;
	private HlHostel hlHostel;
	private HlRoomType hlRoomType;
	private String name;
	private String floorNo;
	private String roomStatus;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<HlRoomTransaction> hlRoomTransactions = new HashSet<HlRoomTransaction>(0);
	private Set<HlBeds> hlBeds = new HashSet<HlBeds>();
	private HlBlocks hlBlock;
	private HlUnits hlUnit;
	public HlRoom() {
	}
	
	
	public HlRoom(int id, HlHostel hlHostel, HlRoomType hlRoomType,
			String name, String floorNo, String roomStatus, String createdBy,
			Date createdDate, String modifiedBy, Date lastModifiedDate,
			Boolean isActive, Set<HlRoomTransaction> hlRoomTransactions,
			HlBlocks hlBlock, HlUnits hlUnit) {
		super();
		this.id = id;
		this.hlHostel = hlHostel;
		this.hlRoomType = hlRoomType;
		this.name = name;
		this.floorNo = floorNo;
		this.roomStatus = roomStatus;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.hlRoomTransactions = hlRoomTransactions;
		this.hlBlock = hlBlock;
		this.hlUnit = hlUnit;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public HlHostel getHlHostel() {
		return hlHostel;
	}

	public void setHlHostel(HlHostel hlHostel) {
		this.hlHostel = hlHostel;
	}

	public HlRoomType getHlRoomType() {
		return hlRoomType;
	}

	public void setHlRoomType(HlRoomType hlRoomType) {
		this.hlRoomType = hlRoomType;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFloorNo() {
		return floorNo;
	}

	public void setFloorNo(String floorNo) {
		this.floorNo = floorNo;
	}

	public String getRoomStatus() {
		return roomStatus;
	}

	public void setRoomStatus(String roomStatus) {
		this.roomStatus = roomStatus;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<HlRoomTransaction> getHlRoomTransactions() {
		return hlRoomTransactions;
	}

	public void setHlRoomTransactions(Set<HlRoomTransaction> hlRoomTransactions) {
		this.hlRoomTransactions = hlRoomTransactions;
	}

	public Set<HlBeds> getHlBeds() {
		return hlBeds;
	}

	public void setHlBeds(Set<HlBeds> hlBeds) {
		this.hlBeds = hlBeds;
	}

	public HlBlocks getHlBlock() {
		return hlBlock;
	}

	public void setHlBlock(HlBlocks hlBlock) {
		this.hlBlock = hlBlock;
	}

	public HlUnits getHlUnit() {
		return hlUnit;
	}

	public void setHlUnit(HlUnits hlUnit) {
		this.hlUnit = hlUnit;
	}
	
}
