package com.kp.cms.bo.admin;

// Generated Dec 18, 2009 3:48:30 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * HlLeave generated by hbm2java
 */
public class HostelOnlineApplication implements java.io.Serializable {

	private int id;
	private Student student;
	private HlHostel hlHostel;
	private HlRoomType roomType;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private int academicYear;
	private String applicationNo;
	private Boolean isSelected;
	private HlRoomType selectedRoomType;
	
	public HostelOnlineApplication() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public HlHostel getHlHostel() {
		return hlHostel;
	}

	public void setHlHostel(HlHostel hlHostel) {
		this.hlHostel = hlHostel;
	}

	public HlRoomType getRoomType() {
		return roomType;
	}

	public void setRoomType(HlRoomType roomType) {
		this.roomType = roomType;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public int getAcademicYear() {
		return academicYear;
	}

	public void setAcademicYear(int academicYear) {
		this.academicYear = academicYear;
	}

	public String getApplicationNo() {
		return applicationNo;
	}

	public void setApplicationNo(String applicationNo) {
		this.applicationNo = applicationNo;
	}

	public Boolean getIsSelected() {
		return isSelected;
	}

	public void setIsSelected(Boolean isSelected) {
		this.isSelected = isSelected;
	}

	public HlRoomType getSelectedRoomType() {
		return selectedRoomType;
	}

	public void setSelectedRoomType(HlRoomType selectedRoomType) {
		this.selectedRoomType = selectedRoomType;
	}


   
}
