package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kp.cms.bo.admission.InterviewSelectionSchedule;

/**
 * InterviewSchedule generated by hbm2java
 */
public class InterviewScheduleHistory implements java.io.Serializable {

	private int id;
	private Interview interview;
	private Date date;
	private String startTime;
	private String endTime;
	private Integer createdBy;
	private Date createdDate;
	private Date lastModifiedDate;
	private String timeInterval;
	private String venue;
	private String modifiedBy;
	private InterviewSelectionSchedule selectionScheduleId;
	private Set<InterviewCardHistory> interviewCards = new HashSet<InterviewCardHistory>(0);
	public InterviewScheduleHistory() {
	}

	public InterviewScheduleHistory(int id) {
		this.id = id;
	}
	
	
	

	public InterviewScheduleHistory(int id, Interview interview, Date date,
			String startTime, String endTime, Integer createdBy,
			Date createdDate, Date lastModifiedDate, String timeInterval,
			String venue, Set<InterviewCardHistory> interviewCards, String modifiedBy, InterviewSelectionSchedule selectionScheduleId) {
		super();
		this.id = id;
		this.interview = interview;
		this.date = date;
		this.startTime = startTime;
		this.endTime = endTime;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.timeInterval = timeInterval;
		this.venue = venue;
		this.interviewCards = interviewCards;
		this.modifiedBy = modifiedBy;
		this.selectionScheduleId=selectionScheduleId;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Interview getInterview() {
		return interview;
	}

	public void setInterview(Interview interview) {
		this.interview = interview;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public String getTimeInterval() {
		return timeInterval;
	}

	public void setTimeInterval(String timeInterval) {
		this.timeInterval = timeInterval;
	}

	public String getVenue() {
		return venue;
	}

	public void setVenue(String venue) {
		this.venue = venue;
	}

	public Set<InterviewCardHistory> getInterviewCards() {
		return interviewCards;
	}

	public void setInterviewCards(Set<InterviewCardHistory> interviewCards) {
		this.interviewCards = interviewCards;
	}

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public InterviewSelectionSchedule getSelectionScheduleId() {
		return selectionScheduleId;
	}

	public void setSelectionScheduleId(
			InterviewSelectionSchedule selectionScheduleId) {
		this.selectionScheduleId = selectionScheduleId;
	}
	
	
	
}
