package com.kp.cms.bo.admin;

// Generated Jan 16, 2009 1:32:28 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Interview generated by hbm2java
 */
public class Interview implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private InterviewProgramCourse interviewProgramCourse;
	private Date createdDate;
	private Date lastModifiedDate;
	private int year;
	private Integer noOfCandidates;
	private Integer noOfInterviewers;
	private Boolean isGroupInterview;
	private Integer noOfPersonsPerPanel;
	private Integer noOfCandidatesPerPanel;
	private Integer noOfPanelsPerDay;
	private Set<InterviewSchedule> interviewSchedules = new HashSet<InterviewSchedule>(
			0);
	private Set<InterviewCard> interviewCards = new HashSet<InterviewCard>(0);

	public Interview() {
	}

	public Interview(int id) {
		this.id = id;
	}

	public Interview(int id, String createdBy,
			String modifiedBy,
			InterviewProgramCourse interviewProgramCourse,
			Date interviewDuration, Date createdDate, Date lastModifiedDate,
			int year, Integer noOfCandidates, Integer noOfInterviewers,Boolean isGroupInterview,
			Integer noOfPersonsPerPanel,Integer noOfCandidatesPerPanel,Integer noOfPanelsPerDay,
			Set<InterviewSchedule> interviewSchedules,
			Set<InterviewCard> interviewCards) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.interviewProgramCourse = interviewProgramCourse;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.year = year;
		this.noOfCandidates = noOfCandidates;
		this.noOfInterviewers = noOfInterviewers;
		this.isGroupInterview = isGroupInterview;
		this.noOfPersonsPerPanel = noOfPersonsPerPanel;
		this.noOfCandidatesPerPanel = noOfCandidatesPerPanel;
		this.noOfPanelsPerDay = noOfPanelsPerDay;
		this.interviewSchedules = interviewSchedules;
		this.interviewCards = interviewCards;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public InterviewProgramCourse getInterviewProgramCourse() {
		return this.interviewProgramCourse;
	}

	public void setInterviewProgramCourse(
			InterviewProgramCourse interviewProgramCourse) {
		this.interviewProgramCourse = interviewProgramCourse;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}


	public int getYear() {
		return year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public Integer getNoOfCandidates() {
		return this.noOfCandidates;
	}

	public void setNoOfCandidates(Integer noOfCandidates) {
		this.noOfCandidates = noOfCandidates;
	}

	public Integer getNoOfInterviewers() {
		return this.noOfInterviewers;
	}

	public void setNoOfInterviewers(Integer noOfInterviewers) {
		this.noOfInterviewers = noOfInterviewers;
	}
	
	public Boolean getIsGroupInterview() {
		return isGroupInterview;
	}

	public void setIsGroupInterview(Boolean isGroupInterview) {
		this.isGroupInterview = isGroupInterview;
	}

	public Integer getNoOfPersonsPerPanel() {
		return noOfPersonsPerPanel;
	}

	public void setNoOfPersonsPerPanel(Integer noOfPersonsPerPanel) {
		this.noOfPersonsPerPanel = noOfPersonsPerPanel;
	}

	public Integer getNoOfCandidatesPerPanel() {
		return noOfCandidatesPerPanel;
	}

	public void setNoOfCandidatesPerPanel(Integer noOfCandidatesPerPanel) {
		this.noOfCandidatesPerPanel = noOfCandidatesPerPanel;
	}

	public Integer getNoOfPanelsPerDay() {
		return noOfPanelsPerDay;
	}

	public void setNoOfPanelsPerDay(Integer noOfPanelsPerDay) {
		this.noOfPanelsPerDay = noOfPanelsPerDay;
	}

	public Set<InterviewSchedule> getInterviewSchedules() {
		return this.interviewSchedules;
	}

	public void setInterviewSchedules(Set<InterviewSchedule> interviewSchedules) {
		this.interviewSchedules = interviewSchedules;
	}

	public Set<InterviewCard> getInterviewCards() {
		return this.interviewCards;
	}

	public void setInterviewCards(Set<InterviewCard> interviewCards) {
		this.interviewCards = interviewCards;
	}

}
