package com.kp.cms.bo.admin;

// Generated Aug 27, 2009 2:58:28 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvCashPurchase generated by hbm2java
 */
public class InvCashPurchase implements java.io.Serializable {

	private int id;
	private InvLocation invLocation;
	private InvVendor invVendor;
	private Date cashPurchaseDate;
	private String vendorName;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<InvCashPurchaseItem> invCashPurchaseItems = new HashSet<InvCashPurchaseItem>(
			0);

	public InvCashPurchase() {
	}

	public InvCashPurchase(int id) {
		this.id = id;
	}

	public InvCashPurchase(int id, InvLocation invLocation,
			InvVendor invVendor, Date cashPurchaseDate, String createdBy, Date createdDate,
			String modifiedBy, Date lastModifiedDate, Boolean isActive,String vendorName,
			Set<InvCashPurchaseItem> invCashPurchaseItems) {
		this.id = id;
		this.invLocation = invLocation;
		this.invVendor = invVendor;
		this.cashPurchaseDate = cashPurchaseDate;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.vendorName = vendorName;
		this.invCashPurchaseItems = invCashPurchaseItems;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public InvLocation getInvLocation() {
		return this.invLocation;
	}

	public void setInvLocation(InvLocation invLocation) {
		this.invLocation = invLocation;
	}

	public InvVendor getInvVendor() {
		return this.invVendor;
	}

	public void setInvVendor(InvVendor invVendor) {
		this.invVendor = invVendor;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<InvCashPurchaseItem> getInvCashPurchaseItems() {
		return this.invCashPurchaseItems;
	}

	public void setInvCashPurchaseItems(
			Set<InvCashPurchaseItem> invCashPurchaseItems) {
		this.invCashPurchaseItems = invCashPurchaseItems;
	}

	public Date getCashPurchaseDate() {
		return cashPurchaseDate;
	}

	public void setCashPurchaseDate(Date cashPurchaseDate) {
		this.cashPurchaseDate = cashPurchaseDate;
	}

	public String getVendorName() {
		return vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

}
