package com.kp.cms.bo.admin;

// Generated Aug 27, 2009 2:58:28 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvLocation generated by hbm2java
 */
public class InvLocation implements java.io.Serializable {

	private int id;
	private Employee employee;
	private InvCampus invCampusId;
	private String name;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<InvTx> invTxes = new HashSet<InvTx>(0);
	private Set<InvStockReceipt> invStockReceipts = new HashSet<InvStockReceipt>(
			0);
	private Set<InvIssue> invIssues = new HashSet<InvIssue>(0);
	private Set<InvCashPurchase> invCashPurchases = new HashSet<InvCashPurchase>(
			0);
	private Set<InvSalvage> invSalvages = new HashSet<InvSalvage>(0);
	private Set<InvItemStock> invItemStocks = new HashSet<InvItemStock>(0);
	private Set<InvRequest> invRequests = new HashSet<InvRequest>(0);
	private Set<InvStockTransfer> invStockTransfersForInvLocationToId = new HashSet<InvStockTransfer>(
			0);
	private Set<InvStockTransfer> invStockTransfersForInvLocationFromId = new HashSet<InvStockTransfer>(
			0);

	public InvLocation() {
	}

	public InvLocation(int id) {
		this.id = id;
	}

	public InvLocation(int id, Employee employee, String name, String createdBy, Date createdDate,
			String modifiedBy, Date lastModifiedDate, Boolean isActive,Set<InvTx> invTxes,
			Set<InvStockReceipt> invStockReceipts, Set<InvIssue> invIssues,
			Set<InvCashPurchase> invCashPurchases, Set<InvSalvage> invSalvages,
			Set<InvItemStock> invItemStocks, Set<InvRequest> invRequests,
			Set<InvStockTransfer> invStockTransfersForInvLocationToId,
			Set<InvStockTransfer> invStockTransfersForInvLocationFromId,InvCampus invCampusId) {
		this.id = id;
		this.employee = employee;
		this.name = name;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.invTxes = invTxes;
		this.invStockReceipts = invStockReceipts;
		this.invIssues = invIssues;
		this.invCashPurchases = invCashPurchases;
		this.invSalvages = invSalvages;
		this.invItemStocks = invItemStocks;
		this.invRequests = invRequests;
		this.invStockTransfersForInvLocationToId = invStockTransfersForInvLocationToId;
		this.invStockTransfersForInvLocationFromId = invStockTransfersForInvLocationFromId;
		this.invCampusId=invCampusId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<InvStockReceipt> getInvStockReceipts() {
		return this.invStockReceipts;
	}

	public void setInvStockReceipts(Set<InvStockReceipt> invStockReceipts) {
		this.invStockReceipts = invStockReceipts;
	}

	public Set<InvIssue> getInvIssues() {
		return this.invIssues;
	}

	public void setInvIssues(Set<InvIssue> invIssues) {
		this.invIssues = invIssues;
	}

	public Set<InvCashPurchase> getInvCashPurchases() {
		return this.invCashPurchases;
	}

	public void setInvCashPurchases(Set<InvCashPurchase> invCashPurchases) {
		this.invCashPurchases = invCashPurchases;
	}

	public Set<InvSalvage> getInvSalvages() {
		return this.invSalvages;
	}

	public void setInvSalvages(Set<InvSalvage> invSalvages) {
		this.invSalvages = invSalvages;
	}

	public Set<InvItemStock> getInvItemStocks() {
		return this.invItemStocks;
	}

	public void setInvItemStocks(Set<InvItemStock> invItemStocks) {
		this.invItemStocks = invItemStocks;
	}

	public Set<InvRequest> getInvRequests() {
		return this.invRequests;
	}

	public void setInvRequests(Set<InvRequest> invRequests) {
		this.invRequests = invRequests;
	}

	public Set<InvStockTransfer> getInvStockTransfersForInvLocationToId() {
		return this.invStockTransfersForInvLocationToId;
	}

	public void setInvStockTransfersForInvLocationToId(
			Set<InvStockTransfer> invStockTransfersForInvLocationToId) {
		this.invStockTransfersForInvLocationToId = invStockTransfersForInvLocationToId;
	}

	public Set<InvStockTransfer> getInvStockTransfersForInvLocationFromId() {
		return this.invStockTransfersForInvLocationFromId;
	}

	public void setInvStockTransfersForInvLocationFromId(
			Set<InvStockTransfer> invStockTransfersForInvLocationFromId) {
		this.invStockTransfersForInvLocationFromId = invStockTransfersForInvLocationFromId;
	}

	public Set<InvTx> getInvTxes() {
		return invTxes;
	}

	public void setInvTxes(Set<InvTx> invTxes) {
		this.invTxes = invTxes;
	}

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public InvCampus getInvCampusId() {
		return invCampusId;
	}

	public void setInvCampusId(InvCampus invCampusId) {
		this.invCampusId = invCampusId;
	}

}
