package com.kp.cms.bo.admin;

// Generated Aug 27, 2009 2:58:28 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvVendor generated by hbm2java
 */
public class InvVendor implements java.io.Serializable {

	private int id;
	private State state;
	private Country country;
	private String name;
	private String contactPerson;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private Integer zipCode;
	private String phone;
	private String phone1;
	private String phone2;
	private String mobile;
	private String mobile1;
	private String email;
	private String faxNo;
	private String panNo;
	private String tanNo;
	private String pin;
	private String vat;
	private String bankAccountNo;
	private String bankBranch;
	private Boolean isAuthorized;
	private String paymentTerms;
	private String deliverySchedule;
	private String paymentMode;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private String stateOthers;
	private String remarks;
	private Set<InvPurchaseOrder> invPurchaseOrders = new HashSet<InvPurchaseOrder>(
			0);
	private Set<InvVendorItemCategory> invVendorItemCategories = new HashSet<InvVendorItemCategory>(
			0);
	private Set<InvQuotation> invQuotations = new HashSet<InvQuotation>(0);
	
	public InvVendor() {
	}

	public InvVendor(int id) {
		this.id = id;
	}

	public InvVendor(int id, State state, Country country, String name,
			String contactPerson, String addressLine1, String addressLine2,
			String city, Integer zipCode, String phone, String mobile,
			String email, String faxNo, String panNo, String tanNo, String pin,
			String vat, String bankAccountNo, String bankBranch,
			Boolean isAuthorized, String paymentTerms, String deliverySchedule,
			String paymentMode, String createdBy, Date createdDate,String remarks,
			String modifiedBy, Date lastModifiedDate, Boolean isActive, String stateOthers,
			Set<InvPurchaseOrder> invPurchaseOrders, Set<InvQuotation> invQuotations,
			Set<InvVendorItemCategory> invVendorItemCategories,String phone1,String phone2,String mobile1) {
		this.id = id;
		this.state = state;
		this.country = country;
		this.name = name;
		this.contactPerson = contactPerson;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.zipCode = zipCode;
		this.phone = phone;
		this.phone1=phone1;
		this.phone2= phone2;
		this.mobile = mobile;
		this.mobile1=mobile1;
		this.email = email;
		this.faxNo = faxNo;
		this.panNo = panNo;
		this.tanNo = tanNo;
		this.pin = pin;
		this.vat = vat;
		this.bankAccountNo = bankAccountNo;
		this.bankBranch = bankBranch;
		this.isAuthorized = isAuthorized;
		this.paymentTerms = paymentTerms;
		this.deliverySchedule = deliverySchedule;
		this.paymentMode = paymentMode;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.invPurchaseOrders = invPurchaseOrders;
		this.invVendorItemCategories = invVendorItemCategories;
		this.stateOthers = stateOthers;
		this.invQuotations = invQuotations; 
		this.remarks = remarks;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Integer getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(Integer zipCode) {
		this.zipCode = zipCode;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFaxNo() {
		return this.faxNo;
	}

	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}

	public String getPanNo() {
		return this.panNo;
	}

	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}

	public String getTanNo() {
		return this.tanNo;
	}

	public void setTanNo(String tanNo) {
		this.tanNo = tanNo;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getVat() {
		return this.vat;
	}

	public void setVat(String vat) {
		this.vat = vat;
	}

	public String getBankAccountNo() {
		return this.bankAccountNo;
	}

	public void setBankAccountNo(String bankAccountNo) {
		this.bankAccountNo = bankAccountNo;
	}

	public String getBankBranch() {
		return this.bankBranch;
	}

	public void setBankBranch(String bankBranch) {
		this.bankBranch = bankBranch;
	}

	public Boolean getIsAuthorized() {
		return this.isAuthorized;
	}

	public void setIsAuthorized(Boolean isAuthorized) {
		this.isAuthorized = isAuthorized;
	}

	public String getPaymentTerms() {
		return this.paymentTerms;
	}

	public void setPaymentTerms(String paymentTerms) {
		this.paymentTerms = paymentTerms;
	}

	public String getDeliverySchedule() {
		return this.deliverySchedule;
	}

	public void setDeliverySchedule(String deliverySchedule) {
		this.deliverySchedule = deliverySchedule;
	}

	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<InvPurchaseOrder> getInvPurchaseOrders() {
		return this.invPurchaseOrders;
	}

	public void setInvPurchaseOrders(Set<InvPurchaseOrder> invPurchaseOrders) {
		this.invPurchaseOrders = invPurchaseOrders;
	}

	public Set<InvVendorItemCategory> getInvVendorItemCategories() {
		return this.invVendorItemCategories;
	}

	public void setInvVendorItemCategories(
			Set<InvVendorItemCategory> invVendorItemCategories) {
		this.invVendorItemCategories = invVendorItemCategories;
	}

	public String getStateOthers() {
		return stateOthers;
	}

	public void setStateOthers(String stateOthers) {
		this.stateOthers = stateOthers;
	}

	public Set<InvQuotation> getInvQuotations() {
		return invQuotations;
	}

	public void setInvQuotations(Set<InvQuotation> invQuotations) {
		this.invQuotations = invQuotations;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getPhone1() {
		return phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone2() {
		return phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public String getMobile1() {
		return mobile1;
	}

	public void setMobile1(String mobile1) {
		this.mobile1 = mobile1;
	}

}
