package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LeaveType generated by hbm2java
 */
public class LeaveType implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private String name;
	private String description;
	private Date createdDate;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<StudentLeave> studentLeaves = new HashSet<StudentLeave>(0);

	public LeaveType() {
	}

	public LeaveType(int id) {
		this.id = id;
	}

	public LeaveType(int id, String createdBy,
			String modifiedBy, String name, String description,Boolean isActive,
			Date createdDate, Date lastModifiedDate,
			Set<StudentLeave> studentLeaves) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.name = name;
		this.description = description;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.studentLeaves = studentLeaves;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<StudentLeave> getStudentLeaves() {
		return this.studentLeaves;
	}

	public void setStudentLeaves(Set<StudentLeave> studentLeaves) {
		this.studentLeaves = studentLeaves;
	}
	
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
