package com.kp.cms.bo.admin;

// Generated Apr 27, 2009 4:03:37 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * NewsEvents generated by hbm2java
 */
public class NewsEvents implements java.io.Serializable {

	private int id;
	private String description;
	private String createdBy;
	private Date createdDate;
	private String required;
	private String modifiedBy;
	private Date lastModifiedDate;

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public NewsEvents() {
	}

	public NewsEvents(int id) {
		this.id = id;
	}

	public NewsEvents(int id, String description, String createdBy,
			Date createdDate,String required) {
		this.id = id;
		this.description = description;
		this.createdBy = createdBy;
		this.createdDate = (Date)createdDate.clone();
		this.required=required;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getRequired() {
		return required;
	}

	public void setRequired(String required) {
		this.required = required;
	}

}
