package com.kp.cms.bo.admin;

// Generated Nov 3, 2009 6:48:19 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PcAccountHead generated by hbm2java
 */
public class PcAccountHead implements java.io.Serializable {

	private int id;
	private PcBankAccNumber pcBankAccNumber;
	private PcAccHeadGroup pcAccHeadGroup;
	private String accCode;
	private String accName;
	private String bankAccNo;
	private Boolean isFixedAmount;
	private BigDecimal amount;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<PcReceipts> pcReceiptses = new HashSet<PcReceipts>(0);
	private String details;
	private Program programId;
	
	public PcAccountHead() {
	}

	public PcAccountHead(int id) {
		this.id = id;
	}

	public PcAccountHead(int id, PcBankAccNumber pcBankAccNumber,
			PcAccHeadGroup pcAccHeadGroup, String accCode, String accName,Program programId,
			String bankAccNo, Boolean isFixedAmount, BigDecimal amount,
			String createdBy, Date createdDate, String modifiedBy,
			Date lastModifiedDate, Boolean isActive,
			Set<PcReceipts> pcReceiptses) {
		this.id = id;
		this.pcBankAccNumber = pcBankAccNumber;
		this.pcAccHeadGroup = pcAccHeadGroup;
		this.accCode = accCode;
		this.accName = accName;
		this.bankAccNo = bankAccNo;
		this.isFixedAmount = isFixedAmount;
		this.amount = amount;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.pcReceiptses = pcReceiptses;
		this.programId=programId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public PcBankAccNumber getPcBankAccNumber() {
		return this.pcBankAccNumber;
	}

	public void setPcBankAccNumber(PcBankAccNumber pcBankAccNumber) {
		this.pcBankAccNumber = pcBankAccNumber;
	}

	public PcAccHeadGroup getPcAccHeadGroup() {
		return this.pcAccHeadGroup;
	}

	public void setPcAccHeadGroup(PcAccHeadGroup pcAccHeadGroup) {
		this.pcAccHeadGroup = pcAccHeadGroup;
	}

	public String getAccCode() {
		return this.accCode;
	}

	public void setAccCode(String accCode) {
		this.accCode = accCode;
	}

	public String getAccName() {
		return this.accName;
	}

	public void setAccName(String accName) {
		this.accName = accName;
	}

	public String getBankAccNo() {
		return this.bankAccNo;
	}

	public void setBankAccNo(String bankAccNo) {
		this.bankAccNo = bankAccNo;
	}

	public Boolean getIsFixedAmount() {
		return this.isFixedAmount;
	}

	public void setIsFixedAmount(Boolean isFixedAmount) {
		this.isFixedAmount = isFixedAmount;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<PcReceipts> getPcReceiptses() {
		return this.pcReceiptses;
	}

	public void setPcReceiptses(Set<PcReceipts> pcReceiptses) {
		this.pcReceiptses = pcReceiptses;
	}

	public String getDetails() {
		return details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public Program getProgramId() {
		return programId;
	}

	public void setProgramId(Program programId) {
		this.programId = programId;
	}

}
