package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReligionSection generated by hbm2java
 */
public class ReligionSection implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private Religion religion;
	private String name;
	private Date createdDate;
	private Date lastModifiedDate;
	private Boolean isActive;
	private String order;
	private Set<WeightageDefinition> weightageDefinitions = new HashSet<WeightageDefinition>(
			0);
	private Set<PersonalData> personalDatas = new HashSet<PersonalData>(0);
	private boolean isAppearOnline;

	public ReligionSection() {
	}

	public ReligionSection(int id) {
		this.id = id;
	}

	public ReligionSection(int id, String createdBy,
			String modifiedBy, Religion religion, String name,
			Date createdDate, Date lastModifiedDate,
			Set<WeightageDefinition> weightageDefinitions,
			Set<PersonalData> personalDatas, boolean isAppearOnline,String order) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.religion = religion;
		this.name = name;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.weightageDefinitions = weightageDefinitions;
		this.personalDatas = personalDatas;
		this.isAppearOnline = isAppearOnline;
		this.order = order;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Religion getReligion() {
		return this.religion;
	}

	public void setReligion(Religion religion) {
		this.religion = religion;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<WeightageDefinition> getWeightageDefinitions() {
		return this.weightageDefinitions;
	}

	public void setWeightageDefinitions(
			Set<WeightageDefinition> weightageDefinitions) {
		this.weightageDefinitions = weightageDefinitions;
	}

	public Set<PersonalData> getPersonalDatas() {
		return this.personalDatas;
	}

	public void setPersonalDatas(Set<PersonalData> personalDatas) {
		this.personalDatas = personalDatas;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public boolean getIsAppearOnline() {
		return isAppearOnline;
	}

	public void setIsAppearOnline(boolean isAppearOnline) {
		this.isAppearOnline = isAppearOnline;
	}

	public String getOrder() {
		return order;
	}

	public void setOrder(String order) {
		this.order = order;
	}

}
