package com.kp.cms.bo.admin;

// Generated Mar 9, 2009 5:02:52 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;


/**
 * AccessPrivileges generated by hbm2java
 */
public class ReportAccessPrivileges implements java.io.Serializable {

	private int id;
	private ReportModules modules;
	private ReportsMenus menus;
	private Roles roles;
	private String name;
	private Boolean allowAccess;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;

	public ReportAccessPrivileges() {
	}

	public ReportAccessPrivileges(int id) {
		this.id = id;
	}

	public ReportAccessPrivileges(int id, ReportModules modules, ReportsMenus menus, Roles roles,
			String name, Boolean allowAccess, String createdBy,
			Date createdDate, String modifiedBy, Date lastModifiedDate,
			Boolean isActive) {
		this.id = id;
		this.setModules(modules);
		this.setMenus(menus);
		this.roles = roles;
		this.name = name;
		this.allowAccess = allowAccess;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getAllowAccess() {
		return this.allowAccess;
	}

	public void setAllowAccess(Boolean allowAccess) {
		this.allowAccess = allowAccess;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public void setModules(ReportModules modules) {
		this.modules = modules;
	}

	public ReportModules getModules() {
		return modules;
	}

	public void setMenus(ReportsMenus menus) {
		this.menus = menus;
	}

	public ReportsMenus getMenus() {
		return menus;
	}

}
