package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ResidentCategory generated by hbm2java
 */
public class ResidentCategory implements java.io.Serializable {

	private int id;
	private Employee employee;
	private String name;
	private String createdBy;
	private String modifiedBy;
	private Date createdDate;
	private Date lastModifiedDate;
	private Integer residentOrder;
	private boolean isActive;
	private Set<PersonalData> personalDatas = new HashSet<PersonalData>(0);
	private Set<WeightageDefinition> weightageDefinitions = new HashSet<WeightageDefinition>(
			0);
	private Set<FeeCriteria> feeCriteriasRes = new HashSet<FeeCriteria>(
			0);	

	public ResidentCategory() {
	}

	public ResidentCategory(int id) {
		this.id = id;
	}

	public ResidentCategory(int id, Employee employee, String name,
			String createdBy, Date createdDate, Date lastModifiedDate,
			Set<PersonalData> personalDatas,
			Set<WeightageDefinition> weightageDefinitions, Set<FeeCriteria> feeCriteriasRes,Integer residentOrder) {
		this.id = id;
		this.employee = employee;
		this.name = name;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.personalDatas = personalDatas;
		this.weightageDefinitions = weightageDefinitions;
		this.feeCriteriasRes = feeCriteriasRes;
		this.residentOrder = residentOrder;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<PersonalData> getPersonalDatas() {
		return this.personalDatas;
	}

	public void setPersonalDatas(Set<PersonalData> personalDatas) {
		this.personalDatas = personalDatas;
	}

	public Set<WeightageDefinition> getWeightageDefinitions() {
		return this.weightageDefinitions;
	}

	public void setWeightageDefinitions(
			Set<WeightageDefinition> weightageDefinitions) {
		this.weightageDefinitions = weightageDefinitions;
	}
	public boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<FeeCriteria> getFeeCriteriasRes() {
		return feeCriteriasRes;
	}

	public void setFeeCriteriasRes(Set<FeeCriteria> feeCriteriasRes) {
		this.feeCriteriasRes = feeCriteriasRes;
	}

	public void setActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Integer getResidentOrder() {
		return residentOrder;
	}

	public void setResidentOrder(Integer residentOrder) {
		this.residentOrder = residentOrder;
	}

	
	
}
