package com.kp.cms.bo.admin;

// Generated May 20, 2009 11:04:46 AM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * StudentQualifyexamDetail generated by hbm2java
 */
public class StudentQualifyexamDetail implements java.io.Serializable {

	private int id;
	private AdmAppln admAppln;
	private String optionalSubjects;
	private String secondLanguage;
	private BigDecimal totalMarks;
	private BigDecimal obtainedMarks;
	private BigDecimal percentage;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private BigDecimal coreSubjectsTotalMarks;
	private BigDecimal coreSubjectsObtainedMarks;
	private BigDecimal coreSubjectsPercentage;

	public StudentQualifyexamDetail() {
	}

	public StudentQualifyexamDetail(int id) {
		this.id = id;
	}

	public StudentQualifyexamDetail(int id, AdmAppln admAppln,
			String optionalSubjects, String secondLanguage,
			BigDecimal totalMarks, BigDecimal obtainedMarks,
			BigDecimal percentage, String createdBy, Date createdDate,
			String modifiedBy, Date lastModifiedDate) {
		this.id = id;
		this.admAppln = admAppln;
		this.optionalSubjects = optionalSubjects;
		this.secondLanguage = secondLanguage;
		this.totalMarks = totalMarks;
		this.obtainedMarks = obtainedMarks;
		this.percentage = percentage;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public AdmAppln getAdmAppln() {
		return this.admAppln;
	}

	public void setAdmAppln(AdmAppln admAppln) {
		this.admAppln = admAppln;
	}

	public String getOptionalSubjects() {
		return this.optionalSubjects;
	}

	public void setOptionalSubjects(String optionalSubjects) {
		this.optionalSubjects = optionalSubjects;
	}

	public String getSecondLanguage() {
		return this.secondLanguage;
	}

	public void setSecondLanguage(String secondLanguage) {
		this.secondLanguage = secondLanguage;
	}

	public BigDecimal getTotalMarks() {
		return this.totalMarks;
	}

	public void setTotalMarks(BigDecimal totalMarks) {
		this.totalMarks = totalMarks;
	}

	public BigDecimal getObtainedMarks() {
		return this.obtainedMarks;
	}

	public void setObtainedMarks(BigDecimal obtainedMarks) {
		this.obtainedMarks = obtainedMarks;
	}

	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public BigDecimal getCoreSubjectsTotalMarks() {
		return coreSubjectsTotalMarks;
	}

	public void setCoreSubjectsTotalMarks(BigDecimal coreSubjectsTotalMarks) {
		this.coreSubjectsTotalMarks = coreSubjectsTotalMarks;
	}

	public BigDecimal getCoreSubjectsObtainedMarks() {
		return coreSubjectsObtainedMarks;
	}

	public void setCoreSubjectsObtainedMarks(BigDecimal coreSubjectsObtainedMarks) {
		this.coreSubjectsObtainedMarks = coreSubjectsObtainedMarks;
	}

	public BigDecimal getCoreSubjectsPercentage() {
		return coreSubjectsPercentage;
	}

	public void setCoreSubjectsPercentage(BigDecimal coreSubjectsPercentage) {
		this.coreSubjectsPercentage = coreSubjectsPercentage;
	}

}
