package com.kp.cms.bo.admin;

import java.util.Date;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

/**
 * CandidatePreference generated by hbm2java
 */
public class StudentCourseChanceMemo implements java.io.Serializable {

	private int id;
	private AdmAppln admAppln;
	
	private Double indexMark;
	private Course course;
	private String createdBy;
	private String modifiedBy;
	private Date createdDate;
	private Date lastModifiedDate;
	private boolean isActive;
	private Integer rank;
	private Integer prefNo;
	private boolean isAppeared;
	private boolean isAssigned;
	private boolean isCaste;
	private boolean isGeneral;
	private Integer chanceNo;
	private boolean isCancel;
	private boolean isSatisfied;
	private Integer chanceRank;
	private boolean isCommunity;
	private Boolean isAccept;
	private Boolean isDecline;
	private Boolean isUploaded;
	private boolean payonline;
	
	
	public boolean getIsSatisfied() {
		return isSatisfied;
	}



	public void setIsSatisfied(boolean isSatisfied) {
		this.isSatisfied = isSatisfied;
	}



	public boolean getIsCaste() {
		return isCaste;
	}



	public void setIsCaste(boolean isCaste) {
		this.isCaste = isCaste;
	}



	public boolean getIsGeneral() {
		return isGeneral;
	}



	public void setIsGeneral(boolean isGeneral) {
		this.isGeneral = isGeneral;
	}



	public boolean getIsAssigned() {
		return isAssigned;
	}



	public void setIsAssigned(boolean isAssigned) {
		this.isAssigned = isAssigned;
	}



	public StudentCourseChanceMemo() {
	}

	public Integer getPrefNo() {
		return prefNo;
	}



	public void setPrefNo(Integer prefNo) {
		this.prefNo = prefNo;
	}



	public Integer getRank() {
		return rank;
	}



	public void setRank(Integer rank) {
		this.rank = rank;
	}



	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public AdmAppln getAdmAppln() {
		return this.admAppln;
	}

	public void setAdmAppln(AdmAppln admAppln) {
		this.admAppln = admAppln;
	}


	public Double getIndexMark() {
		return indexMark;
	}

	public void setIndexMark(Double indexMark) {
		this.indexMark = indexMark;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	
	public String getCreatedBy() {
		return createdBy;
	}



	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}



	public String getModifiedBy() {
		return modifiedBy;
	}



	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}



	public Date getCreatedDate() {
		return createdDate;
	}



	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}



	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}



	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}



	public boolean getIsActive() {
		return isActive;
	}



	public void setActive(boolean isActive) {
		this.isActive = isActive;
	}





	public boolean getIsCancel() {
		return isCancel;
	}



	public void setIsCancel(boolean isCancel) {
		this.isCancel = isCancel;
	}



	public void setIsAppeared(boolean isAppeared) {
		this.isAppeared = isAppeared;
	}



	public boolean getIsAppeared() {
		return isAppeared;
	}



	public void setChanceNo(Integer chanceNo) {
		this.chanceNo = chanceNo;
	}



	public Integer getChanceNo() {
		return chanceNo;
	}



	public void setChanceRank(Integer chanceRank) {
		this.chanceRank = chanceRank;
	}



	public Integer getChanceRank() {
		return chanceRank;
	}



	public boolean getIsCommunity() {
		return isCommunity;
	}



	public void setIsCommunity(boolean isCommunity) {
		this.isCommunity = isCommunity;
	}



	public Boolean getIsAccept() {
		return isAccept;
	}



	public void setIsAccept(Boolean isAccept) {
		this.isAccept = isAccept;
	}



	public Boolean getIsDecline() {
		return isDecline;
	}



	public void setIsDecline(Boolean isDecline) {
		this.isDecline = isDecline;
	}



	public Boolean getIsUploaded() {
		return isUploaded;
	}



	public void setIsUploaded(Boolean isUploaded) {
		this.isUploaded = isUploaded;
	}



	public Boolean getPayonline() {
		return payonline;
	}



	public void setPayonline(Boolean payonline) {
		this.payonline = payonline;
	}
	
	
}
