package com.kp.cms.bo.admin;

// Generated Apr 20, 2009 4:50:12 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kp.cms.bo.exam.ExamStudentDetentionRejoinDetails;
import com.kp.cms.bo.exam.InternalMarkSupplementaryDetails;
import com.kp.cms.bo.exam.StudentFinalMarkDetails;
import com.kp.cms.bo.exam.StudentPreviousClassHistory;
import com.kp.cms.bo.exam.StudentSubjectGroupHistory;
import com.kp.cms.bo.exam.StudentSupplementaryImprovementApplication;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable,Comparable<Student> {

	private int id;
	private ClassSchemewise classSchemewise;
	private AdmAppln admAppln;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isAdmitted;
	private String rollNo;
	private String registerNo;
	private Boolean isCurrent;
	private Boolean isExamEligible;
	private int programTypeSlNo;
	private Boolean isActive;
	private Set<AttendanceStudent> attendanceStudents = new HashSet<AttendanceStudent>(
			0);
	private Set<LeaveDetails> leaveDetailses = new HashSet<LeaveDetails>(0);
	private Set<BatchStudent> batchStudents = new HashSet<BatchStudent>(0);
	private Set<StudentLogin> studentLogins = new HashSet<StudentLogin>(0);
	private Set<StudentSubjectgroup> studentSubjectgroups = new HashSet<StudentSubjectgroup>(
			0);
	private Set<FeePayment> feePayments = new HashSet<FeePayment>(0);
	private Set<StudentLeaveDetails> studentLeaveDetailses = new HashSet<StudentLeaveDetails>(
			0);
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<StudentRemarks> studentRemarkses = new HashSet<StudentRemarks>(
			0);
	private Set<PcReceipts> pcReceiptses = new HashSet<PcReceipts>(0);
	private Set<StuCocurrLeaveDetails> stuCocurrLeaveDetailses = new HashSet<StuCocurrLeaveDetails>(
			0);
	private Set<PrincipalRemarks> principalRemarkses = new HashSet<PrincipalRemarks>(
			0);
	private String examRegisterNo;
	private String studentNo;
	private Set<StudentTCDetails> studentTCDetails = new HashSet<StudentTCDetails>(0);
	private String tcNo;
	private String mcNo;
	private Date tcDate;
	private String slNo;
	private String bankAccNo;
	private Set<HonorsEntryBo> honorsSet=new HashSet<HonorsEntryBo>();
	private String tcType;
	private Set<ExamStudentDetentionRejoinDetails> examStudentDetentionRejoinDetails = new HashSet<ExamStudentDetentionRejoinDetails>();
	private Set<StudentPreviousClassHistory> studentPreviousClassesHistory=new HashSet<StudentPreviousClassHistory>();
	private Set<StudentSubjectGroupHistory> studentSubjectGroupHistory=new HashSet<StudentSubjectGroupHistory>();
	private Set<StudentSupplementaryImprovementApplication> studentSupplementaryImprovements=new HashSet<StudentSupplementaryImprovementApplication>();
	private Boolean isHide;
	private Date hidedetailsDate;
	private String hidedetailReasons;
	private Set<InternalMarkSupplementaryDetails> markSupplementaryDetails=new HashSet<InternalMarkSupplementaryDetails>();
	private Set<StudentFinalMarkDetails> finalMarkDetails=new HashSet<StudentFinalMarkDetails>();
	private Boolean proforma;
	private String collegeCode;
	private String yearOfPass;
	private String smartCardNo;
	private Boolean isSCDataGenerated;
	private Boolean isSCDataDelivered;
	private Boolean isInactive;
	private Date inactiveDate;
	private String inactiveReasons;
	
	private String subjectPassedCore;
	private String subjectsPassedComplimentary;
	private String examRegNo;	
	private String studentPhoto;
	private String recognitionDetails;
	
	private boolean isEgrand;

	public Student() {
	}

	public Student(int id) {
		this.id = id;
	}

	public Student(int id, ClassSchemewise classSchemewise, AdmAppln admAppln,
			String createdBy, Date createdDate, String modifiedBy,
			Date lastModifiedDate, Boolean isAdmitted, String rollNo,
			String registerNo, Boolean isCurrent, Boolean isExamEligible, Boolean isActive,
			Integer programTypeSlNo, Boolean isHide, Date hidedetailsDate, String hidedetailReasons,
			Set<AttendanceStudent> attendanceStudents,
			Set<LeaveDetails> leaveDetailses, Set<BatchStudent> batchStudents,
			Set<StudentLogin> studentLogins,Set<PcReceipts> pcReceiptses,
			Set<StudentSubjectgroup> studentSubjectgroups,
			Set<StudentRemarks> studentRemarkses,Set<FeePayment> feePayments,
			Set<StudentLeaveDetails> studentLeaveDetailses, Set<Users> userses,Set<StuCocurrLeaveDetails> stuCocurrLeaveDetailses,
			Set<PrincipalRemarks> principalRemarkses,String examRegisterNo,String studentNo,
			Set<StudentTCDetails> studentTCDetails,String tcNo,String mcNo,Date tcDate,String slNo,String bankAccNo,String tcType,
			Boolean proforma,String collegeCode,String yearOfPass,String smartCardNo,boolean isEgrand) {
		this.id = id;
		this.classSchemewise = classSchemewise;
		this.admAppln = admAppln;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isAdmitted = isAdmitted;
		this.rollNo = rollNo;
		this.registerNo = registerNo;
		this.isCurrent = isCurrent;
		this.isExamEligible = isExamEligible;
		this.programTypeSlNo = programTypeSlNo;
		this.attendanceStudents = attendanceStudents;
		this.leaveDetailses = leaveDetailses;
		this.batchStudents = batchStudents;
		this.studentLogins = studentLogins;
		this.studentRemarkses = studentRemarkses;
		this.studentSubjectgroups = studentSubjectgroups;
		this.studentLeaveDetailses = studentLeaveDetailses;
		this.userses = userses;
		this.isActive = isActive;
		this.feePayments = feePayments;
		this.stuCocurrLeaveDetailses = stuCocurrLeaveDetailses;
		this.principalRemarkses = principalRemarkses;
		this.studentNo=studentNo;
		this.examRegisterNo=examRegisterNo;
		this.stuCocurrLeaveDetailses=stuCocurrLeaveDetailses;
		this.tcNo=tcNo;
		this.mcNo=mcNo;
		this.tcDate=tcDate;
		this.slNo=slNo;
		this.bankAccNo=bankAccNo;
		this.tcType=tcType;
		this.hidedetailReasons=hidedetailReasons;
		this.hidedetailsDate=hidedetailsDate;
		this.isHide=isHide;
		this.proforma = proforma;
		this.collegeCode = collegeCode;
		this.yearOfPass = yearOfPass;
		this.smartCardNo = smartCardNo;
		this.isEgrand = isEgrand;
	}

	
	
	public Date getInactiveDate() {
		return inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

	public String getInactiveReasons() {
		return inactiveReasons;
	}

	public void setInactiveReasons(String inactiveReasons) {
		this.inactiveReasons = inactiveReasons;
	}

	public Boolean getIsInactive() {
		return isInactive;
	}

	public void setIsInactive(Boolean isInactive) {
		this.isInactive = isInactive;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ClassSchemewise getClassSchemewise() {
		return this.classSchemewise;
	}

	public void setClassSchemewise(ClassSchemewise classSchemewise) {
		this.classSchemewise = classSchemewise;
	}

	public AdmAppln getAdmAppln() {
		return this.admAppln;
	}

	public void setAdmAppln(AdmAppln admAppln) {
		this.admAppln = admAppln;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsAdmitted() {
		return this.isAdmitted;
	}

	public void setIsAdmitted(Boolean isAdmitted) {
		this.isAdmitted = isAdmitted;
	}

	public String getRollNo() {
		return this.rollNo;
	}

	public void setRollNo(String rollNo) {
		this.rollNo = rollNo;
	}

	public String getRegisterNo() {
		return this.registerNo;
	}

	public void setRegisterNo(String registerNo) {
		this.registerNo = registerNo;
	}

	public Boolean getIsCurrent() {
		return this.isCurrent;
	}

	public void setIsCurrent(Boolean isCurrent) {
		this.isCurrent = isCurrent;
	}

	public Boolean getIsExamEligible() {
		return this.isExamEligible;
	}

	public void setIsExamEligible(Boolean isExamEligible) {
		this.isExamEligible = isExamEligible;
	}

	public int getProgramTypeSlNo() {
		return programTypeSlNo;
	}

	public void setProgramTypeSlNo(int programTypeSlNo) {
		this.programTypeSlNo = programTypeSlNo;
	}

	public Set<AttendanceStudent> getAttendanceStudents() {
		return this.attendanceStudents;
	}

	public void setAttendanceStudents(Set<AttendanceStudent> attendanceStudents) {
		this.attendanceStudents = attendanceStudents;
	}

	public Set<BatchStudent> getBatchStudents() {
		return this.batchStudents;
	}

	public void setBatchStudents(Set<BatchStudent> batchStudents) {
		this.batchStudents = batchStudents;
	}

	public Set<StudentSubjectgroup> getStudentSubjectgroups() {
		return this.studentSubjectgroups;
	}

	public void setStudentSubjectgroups(
			Set<StudentSubjectgroup> studentSubjectgroups) {
		this.studentSubjectgroups = studentSubjectgroups;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	public Set<LeaveDetails> getLeaveDetailses() {
		return leaveDetailses;
	}

	public void setLeaveDetailses(Set<LeaveDetails> leaveDetailses) {
		this.leaveDetailses = leaveDetailses;
	}
	public Set<StudentRemarks> getStudentRemarkses() {
		return this.studentRemarkses;
	}

	public void setStudentRemarkses(Set<StudentRemarks> studentRemarkses) {
		this.studentRemarkses = studentRemarkses;
	}
	public Set<StudentLogin> getStudentLogins() {
		return studentLogins;
	}

	public void setStudentLogins(Set<StudentLogin> studentLogins) {
		this.studentLogins = studentLogins;
	}

	public Set<StudentLeaveDetails> getStudentLeaveDetailses() {
		return studentLeaveDetailses;
	}

	public void setStudentLeaveDetailses(
			Set<StudentLeaveDetails> studentLeaveDetailses) {
		this.studentLeaveDetailses = studentLeaveDetailses;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
	
	public Set<StuCocurrLeaveDetails> getStuCocurrLeaveDetailses() {
		return this.stuCocurrLeaveDetailses;
	}

	public void setStuCocurrLeaveDetailses(
			Set<StuCocurrLeaveDetails> stuCocurrLeaveDetailses) {
		this.stuCocurrLeaveDetailses = stuCocurrLeaveDetailses;
	}

	public Set<PcReceipts> getPcReceiptses() {
		return pcReceiptses;
	}

	public void setPcReceiptses(Set<PcReceipts> pcReceiptses) {
		this.pcReceiptses = pcReceiptses;
	}

	public Set<FeePayment> getFeePayments() {
		return feePayments;
	}

	public void setFeePayments(Set<FeePayment> feePayments) {
		this.feePayments = feePayments;
	}

	public Set<PrincipalRemarks> getPrincipalRemarkses() {
		return principalRemarkses;
	}

	public void setPrincipalRemarkses(Set<PrincipalRemarks> principalRemarkses) {
		this.principalRemarkses = principalRemarkses;
	}

	public String getExamRegisterNo() {
		return examRegisterNo;
	}

	public void setExamRegisterNo(String examRegisterNo) {
		this.examRegisterNo = examRegisterNo;
	}

	public String getStudentNo() {
		return studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public Set<StudentTCDetails> getStudentTCDetails() {
		return studentTCDetails;
	}

	public void setStudentTCDetails(Set<StudentTCDetails> studentTCDetails) {
		this.studentTCDetails = studentTCDetails;
	}

	public String getTcNo() {
		return tcNo;
	}

	public void setTcNo(String tcNo) {
		this.tcNo = tcNo;
	}

	public String getMcNo() {
		return mcNo;
	}

	public void setMcNo(String mcNo) {
		this.mcNo = mcNo;
	}

	public Date getTcDate() {
		return tcDate;
	}

	public void setTcDate(Date tcDate) {
		this.tcDate = tcDate;
	}

	public String getSlNo() {
		return slNo;
	}

	public void setSlNo(String slNo) {
		this.slNo = slNo;
	}

	public String getBankAccNo() {
		return bankAccNo;
	}

	public void setBankAccNo(String bankAccNo) {
		this.bankAccNo = bankAccNo;
	}

	public Set<HonorsEntryBo> getHonorsSet() {
		return honorsSet;
	}

	public void setHonorsSet(Set<HonorsEntryBo> honorsSet) {
		this.honorsSet = honorsSet;
	}

	public String getTcType() {
		return tcType;
	}

	public void setTcType(String tcType) {
		this.tcType = tcType;
	}

	public Set<ExamStudentDetentionRejoinDetails> getExamStudentDetentionRejoinDetails() {
		return examStudentDetentionRejoinDetails;
	}

	public void setExamStudentDetentionRejoinDetails(
			Set<ExamStudentDetentionRejoinDetails> examStudentDetentionRejoinDetails) {
		this.examStudentDetentionRejoinDetails = examStudentDetentionRejoinDetails;
	}

	public Set<StudentPreviousClassHistory> getStudentPreviousClassesHistory() {
		return studentPreviousClassesHistory;
	}

	public void setStudentPreviousClassesHistory(
			Set<StudentPreviousClassHistory> studentPreviousClassesHistory) {
		this.studentPreviousClassesHistory = studentPreviousClassesHistory;
	}

	public Set<StudentSubjectGroupHistory> getStudentSubjectGroupHistory() {
		return studentSubjectGroupHistory;
	}

	public void setStudentSubjectGroupHistory(
			Set<StudentSubjectGroupHistory> studentSubjectGroupHistory) {
		this.studentSubjectGroupHistory = studentSubjectGroupHistory;
	}

	public Set<StudentSupplementaryImprovementApplication> getStudentSupplementaryImprovements() {
		return studentSupplementaryImprovements;
	}

	public void setStudentSupplementaryImprovements(
			Set<StudentSupplementaryImprovementApplication> studentSupplementaryImprovements) {
		this.studentSupplementaryImprovements = studentSupplementaryImprovements;
	}

	

	

	public String getHidedetailReasons() {
		return hidedetailReasons;
	}

	public void setHidedetailReasons(String hidedetailReasons) {
		this.hidedetailReasons = hidedetailReasons;
	}

	

	public Boolean getIsHide() {
		return isHide;
	}

	public void setIsHide(Boolean isHide) {
		this.isHide = isHide;
	}

	public void setHidedetailsDate(Date hidedetailsDate) {
		this.hidedetailsDate = hidedetailsDate;
	}

	public Date getHidedetailsDate() {
		return hidedetailsDate;
	}

	public Set<InternalMarkSupplementaryDetails> getMarkSupplementaryDetails() {
		return markSupplementaryDetails;
	}

	public void setMarkSupplementaryDetails(
			Set<InternalMarkSupplementaryDetails> markSupplementaryDetails) {
		this.markSupplementaryDetails = markSupplementaryDetails;
	}

	public Set<StudentFinalMarkDetails> getFinalMarkDetails() {
		return finalMarkDetails;
	}

	public void setFinalMarkDetails(Set<StudentFinalMarkDetails> finalMarkDetails) {
		this.finalMarkDetails = finalMarkDetails;
	}

	public Boolean getProforma() {
		return proforma;
	}

	public void setProforma(Boolean proforma) {
		this.proforma = proforma;
	}

	public String getCollegeCode() {
		return collegeCode;
	}

	public void setCollegeCode(String collegeCode) {
		this.collegeCode = collegeCode;
	}

	public String getYearOfPass() {
		return yearOfPass;
	}

	public void setYearOfPass(String yearOfPass) {
		this.yearOfPass = yearOfPass;
	}

	public void setSmartCardNo(String smartCardNo) {
		this.smartCardNo = smartCardNo;
	}

	public String getSmartCardNo() {
		return smartCardNo;
	}

	public Boolean getIsSCDataGenerated() {
		return isSCDataGenerated;
	}

	public void setIsSCDataGenerated(Boolean isSCDataGenerated) {
		this.isSCDataGenerated = isSCDataGenerated;
	}

	public Boolean getIsSCDataDelivered() {
		return isSCDataDelivered;
	}

	public void setIsSCDataDelivered(Boolean isSCDataDelivered) {
		this.isSCDataDelivered = isSCDataDelivered;
	}

	
	public String getSubjectPassedCore() {
		return subjectPassedCore;
	}

	public void setSubjectPassedCore(String subjectPassedCore) {
		this.subjectPassedCore = subjectPassedCore;
	}

	public String getSubjectsPassedComplimentary() {
		return subjectsPassedComplimentary;
	}

	public void setSubjectsPassedComplimentary(String subjectsPassedComplimentary) {
		this.subjectsPassedComplimentary = subjectsPassedComplimentary;
	}

	public String getExamRegNo() {
		return examRegNo;
	}

	public void setExamRegNo(String examRegNo) {
		this.examRegNo = examRegNo;
	}

	@Override
	public int compareTo(Student arg0) {
		if(arg0!=null && this!=null && arg0.getRegisterNo()!=null
				 && this.getRegisterNo()!=null){
				return this.getRegisterNo().compareTo(arg0.getRegisterNo());
		}else
		return 0;
	}

	public String getStudentPhoto() {
		return studentPhoto;
	}

	public void setStudentPhoto(String studentPhoto) {
		this.studentPhoto = studentPhoto;
	}

	public boolean getIsEgrand() {
		return isEgrand;
	}

	public void setIsEgrand(boolean isEgrand) {
		this.isEgrand = isEgrand;
	}

	public String getRecognitionDetails() {
		return recognitionDetails;
	}

	public void setRecognitionDetails(String recognitionDetails) {
		this.recognitionDetails = recognitionDetails;
	}

}