package com.kp.cms.bo.admin;

// Generated Apr 20, 2009 4:50:12 PM by Hibernate Tools 3.2.0.b9

/**
 * StudentSubjectgroup generated by hbm2java
 */
public class StudentSubjectgroup implements java.io.Serializable {

	private int id;
	private Student student;
	private SubjectGroup subjectGroup;

	public StudentSubjectgroup() {
	}

	public StudentSubjectgroup(int id) {
		this.id = id;
	}

	public StudentSubjectgroup(int id, Student student,
			SubjectGroup subjectGroup) {
		this.id = id;
		this.student = student;
		this.subjectGroup = subjectGroup;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public SubjectGroup getSubjectGroup() {
		return this.subjectGroup;
	}

	public void setSubjectGroup(SubjectGroup subjectGroup) {
		this.subjectGroup = subjectGroup;
	}

}
