package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kp.cms.bo.exam.ConsolidatedSubjectStream;
import com.kp.cms.bo.exam.ExamMajorDepatmentCodeBO;
import com.kp.cms.bo.exam.ExamSubDefinitionCourseWiseBO;
import com.kp.cms.bo.exam.ExamSubjectRuleSettingsBO;

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private String code;
	private String name;
	private Date createdDate;
	private Date lastModifiedDate;
	private Integer totalMarks;
	private Integer passingMarks;
	private Boolean isSecondLanguage;
	private Boolean isOptionalSubject;
	private Boolean isActive;
	private Boolean questionbyrequired;
	private Integer hourpersem;
	
	private Set<AttendanceMarks> attendanceMarkses = new HashSet<AttendanceMarks>(0);
	private Set<Session> sessions = new HashSet<Session>(0);

	// Added by Shwetha 9Elements
	private int subjectTypeId;
	private String isTheoryPractical; // Theory - T, Practical - P, Both - B
	private String consldtdMarkCardSubName;
	private String subNamePrefix;
	private Integer majorDeptCodeId;
	private String universitySubjectCode;

	private SubjectType subjectType;
	private ExamMajorDepatmentCodeBO examMajorDepatmentCodeBO;
	private Boolean isCertificateCourse;
	private Set<ExamSubjectRuleSettingsBO> examSubjectRuleSettingsBOset;
	private Set<ExamSubDefinitionCourseWiseBO> examSubDefinitionCourseWiseBOSet;
//	private CertificateCourse certificateCourse;
	private Boolean isAdditionalSubject;
	private Set<CertificateCourse> certificateCourses;
	private Boolean coCurricularSubject;
	
	private Department department;
	private int schemeNo;
	private Course eligibleCourse;
	private SubjectCodeGroup subjectCodeGroup;
	
	private ConsolidatedSubjectStream consolidatedSubjectStream;
	private Boolean isCourseOptionalSubject;
	
	public Subject() {
	}

	public Subject(int id) {
		this.id = id;
	}

	public Subject(
			int id,String createdBy,String modifiedBy,
			String code,String name,Date createdDate,
			Date lastModifiedDate,Integer totalMarks,
			Integer passingMarks,Boolean isSecondLanguage,
			Boolean isOptionalSubject,Boolean isActive,
			Boolean questionbyrequired,Integer hourpersem,
			Set<AttendanceMarks> attendanceMarkses,
			Set<Session> sessions,int subjectTypeId,
			String isTheoryPractical,String consldtdMarkCardSubName,
			String subNamePrefix,Integer majorDeptCodeId,
			String universitySubjectCode,SubjectType subjectType,
			ExamMajorDepatmentCodeBO examMajorDepatmentCodeBO,
			Boolean isCertificateCourse,
			Set<ExamSubjectRuleSettingsBO> examSubjectRuleSettingsBOset,
			Set<ExamSubDefinitionCourseWiseBO> examSubDefinitionCourseWiseBOSet,
			Boolean isAdditionalSubject,Set<CertificateCourse> certificateCourses,
			Boolean coCurricularSubject, Department department, int schemeNo,
			Course eligibleCourse, SubjectCodeGroup subjectCodeGroup, ConsolidatedSubjectStream consolidatedSubjectStream,Boolean isCourseOptionalSubject) {
		super();
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.code = code;
		this.name = name;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.totalMarks = totalMarks;
		this.passingMarks = passingMarks;
		this.isSecondLanguage = isSecondLanguage;
		this.isOptionalSubject = isOptionalSubject;
		this.isActive = isActive;
		this.questionbyrequired = questionbyrequired;
		this.hourpersem = hourpersem;
		this.attendanceMarkses = attendanceMarkses;
		this.sessions = sessions;
		this.subjectTypeId = subjectTypeId;
		this.isTheoryPractical = isTheoryPractical;
		this.consldtdMarkCardSubName = consldtdMarkCardSubName;
		this.subNamePrefix = subNamePrefix;
		this.majorDeptCodeId = majorDeptCodeId;
		this.universitySubjectCode = universitySubjectCode;
		this.subjectType = subjectType;
		this.examMajorDepatmentCodeBO = examMajorDepatmentCodeBO;
		this.isCertificateCourse = isCertificateCourse;
		this.examSubjectRuleSettingsBOset = examSubjectRuleSettingsBOset;
		this.examSubDefinitionCourseWiseBOSet = examSubDefinitionCourseWiseBOSet;
		this.isAdditionalSubject = isAdditionalSubject;
		this.certificateCourses = certificateCourses;
		this.coCurricularSubject = coCurricularSubject;
		this.department = department;
		this.schemeNo = schemeNo;
		this.eligibleCourse = eligibleCourse;
		this.subjectCodeGroup = subjectCodeGroup;
		this.consolidatedSubjectStream = consolidatedSubjectStream;
		this.isCourseOptionalSubject = isCourseOptionalSubject;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Integer getTotalMarks() {
		return this.totalMarks;
	}

	public void setTotalMarks(Integer totalMarks) {
		this.totalMarks = totalMarks;
	}

	public Integer getPassingMarks() {
		return this.passingMarks;
	}

	public void setPassingMarks(Integer passingMarks) {
		this.passingMarks = passingMarks;
	}

	public Boolean getIsSecondLanguage() {
		return this.isSecondLanguage;
	}

	public void setIsSecondLanguage(Boolean isSecondLanguage) {
		this.isSecondLanguage = isSecondLanguage;
	}

	public Boolean getIsOptionalSubject() {
		return this.isOptionalSubject;
	}

	public void setIsOptionalSubject(Boolean isOptionalSubject) {
		this.isOptionalSubject = isOptionalSubject;
	}

	public Set<AttendanceMarks> getAttendanceMarkses() {
		return this.attendanceMarkses;
	}

	public void setAttendanceMarkses(Set<AttendanceMarks> attendanceMarkses) {
		this.attendanceMarkses = attendanceMarkses;
	}

	public Set<Session> getSessions() {
		return this.sessions;
	}

	public void setSessions(Set<Session> sessions) {
		this.sessions = sessions;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public int getSubjectTypeId() {
		return subjectTypeId;
	}

	public void setSubjectTypeId(int subjectTypeId) {
		this.subjectTypeId = subjectTypeId;
	}

	public void setSubjectTypeId(String subjectTypeId) {
		this.subjectTypeId = getInt(subjectTypeId);
	}

	private int getInt(String s) {
		try {
			return Integer.parseInt(s);
		} catch (Exception e) {
			return 0;
		}
	}

	public String getIsTheoryPractical() {
		return isTheoryPractical;
	}

	public void setIsTheoryPractical(String isTheoryPractical) {
		this.isTheoryPractical = isTheoryPractical;
	}

	public String getConsldtdMarkCardSubName() {
		return consldtdMarkCardSubName;
	}

	public void setConsldtdMarkCardSubName(String consldtdMarkCardSubName) {
		this.consldtdMarkCardSubName = consldtdMarkCardSubName;
	}

	public String getSubNamePrefix() {
		return subNamePrefix;
	}

	public void setSubNamePrefix(String subNamePrefix) {
		this.subNamePrefix = subNamePrefix;
	}

	public Integer getMajorDeptCodeId() {
		return majorDeptCodeId;
	}

	public void setMajorDeptCodeId(Integer majorDeptCodeId) {
		this.majorDeptCodeId = majorDeptCodeId;
	}

	public void setMajorDeptCodeId(String majorDeptCodeId) {
		this.majorDeptCodeId = getInt(majorDeptCodeId);
	}

	public SubjectType getSubjectType() {
		return subjectType;
	}

	public void setSubjectType(SubjectType subjectType) {
		this.subjectType = subjectType;
	}

	public ExamMajorDepatmentCodeBO getExamMajorDepatmentCodeBO() {
		return examMajorDepatmentCodeBO;
	}

	public void setExamMajorDepatmentCodeBO(
			ExamMajorDepatmentCodeBO examMajorDepatmentCodeBO) {
		this.examMajorDepatmentCodeBO = examMajorDepatmentCodeBO;
	}

	public String getUniversitySubjectCode() {
		return universitySubjectCode;
	}

	public void setUniversitySubjectCode(String universitySubjectCode) {
		this.universitySubjectCode = universitySubjectCode;
	}

	public Boolean getIsCertificateCourse() {
		return isCertificateCourse;
	}

	public void setIsCertificateCourse(Boolean isCertificateCourse) {
		this.isCertificateCourse = isCertificateCourse;
	}

	public Set<ExamSubjectRuleSettingsBO> getExamSubjectRuleSettingsBOset() {
		return examSubjectRuleSettingsBOset;
	}

	public void setExamSubjectRuleSettingsBOset(
			Set<ExamSubjectRuleSettingsBO> examSubjectRuleSettingsBOset) {
		this.examSubjectRuleSettingsBOset = examSubjectRuleSettingsBOset;
	}

	public Set<ExamSubDefinitionCourseWiseBO> getExamSubDefinitionCourseWiseBOSet() {
		return examSubDefinitionCourseWiseBOSet;
	}

	public void setExamSubDefinitionCourseWiseBOSet(
			Set<ExamSubDefinitionCourseWiseBO> examSubDefinitionCourseWiseBOSet) {
		this.examSubDefinitionCourseWiseBOSet = examSubDefinitionCourseWiseBOSet;
	}

//	public void setCertificateCourse(CertificateCourse certificateCourse) {
//		this.certificateCourse = certificateCourse;
//	}
//
//	public CertificateCourse getCertificateCourse() {
//		return certificateCourse;
//	}

	public void setIsAdditionalSubject(Boolean isAdditionalSubject) {
		this.isAdditionalSubject = isAdditionalSubject;
	}

	public Boolean getIsAdditionalSubject() {
		return isAdditionalSubject;
	}

	public Set<CertificateCourse> getCertificateCourses() {
		return certificateCourses;
	}

	public void setCertificateCourses(Set<CertificateCourse> certificateCourses) {
		this.certificateCourses = certificateCourses;
	}

	public Boolean getQuestionbyrequired() {
		return questionbyrequired;
	}

	public void setQuestionbyrequired(Boolean questionbyrequired) {
		this.questionbyrequired = questionbyrequired;
	}

	public Integer getHourpersem() {
		return hourpersem;
	}

	public void setHourpersem(Integer hourpersem) {
		this.hourpersem = hourpersem;
	}
	public int getSchemeNo() {
		return schemeNo;
	}

	public void setSchemeNo(int schemeNo) {
		this.schemeNo = schemeNo;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Boolean getCoCurricularSubject() {
		return coCurricularSubject;
	}

	public void setCoCurricularSubject(Boolean coCurricularSubject) {
		this.coCurricularSubject = coCurricularSubject;
	}

	public Course getEligibleCourse() {
		return eligibleCourse;
	}

	public void setEligibleCourse(Course eligibleCourse) {
		this.eligibleCourse = eligibleCourse;
	}

	public SubjectCodeGroup getSubjectCodeGroup() {
		return subjectCodeGroup;
	}

	public Boolean getIsCourseOptionalSubject() {
		return isCourseOptionalSubject;
	}

	public void setIsCourseOptionalSubject(Boolean isCourseOptionalSubject) {
		this.isCourseOptionalSubject = isCourseOptionalSubject;
	}

	public void setSubjectCodeGroup(SubjectCodeGroup subjectCodeGroup) {
		this.subjectCodeGroup = subjectCodeGroup;
	}

	public ConsolidatedSubjectStream getConsolidatedSubjectStream() {
		return consolidatedSubjectStream;
	}

	public void setConsolidatedSubjectStream(
			ConsolidatedSubjectStream consolidatedSubjectStream) {
		this.consolidatedSubjectStream = consolidatedSubjectStream;
	}
	
	
}