package com.kp.cms.bo.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kp.cms.bo.admin.ApplicantSubjectGroup;
import com.kp.cms.bo.exam.ExamSecondLanguageMasterBO;


/**
 * SubjectGroup generated by hbm2java
 */
public class SubjectGroup implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private Course course;
	private String name;
	private Date createdDate;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<CourseTermSubjectGroup> courseTermSubjectGroups = new HashSet<CourseTermSubjectGroup>(
			0);
	private Set<ClassStudent> classStudents = new HashSet<ClassStudent>(0);
	private Set<SubjectGroupSubjects> subjectGroupSubjectses = new HashSet<SubjectGroupSubjects>(
			0);
	private Set<Fee> fees = new HashSet<Fee>(0);
	private Set<FeeDetails> feeDetailses = new HashSet<FeeDetails>(0);
	private Set<CurriculumSchemeSubject> curriculumSchemeSubjects = new HashSet<CurriculumSchemeSubject>(
			0);

	private Set<ApplicantSubjectGroup> applicantSubjectGroups = new HashSet<ApplicantSubjectGroup>(
			0);
	
	// Addd by Swetha 9Elements
	private boolean isCommonSubGrp;
	private Integer secondLanguageId;
	
	private ExamSecondLanguageMasterBO examSecondLanguageMasterBO;
	
	public SubjectGroup() {
	}

	public SubjectGroup(int id) {
		this.id = id;
	}

	public SubjectGroup(int id, String createdBy,
			String modifiedBy, Course course, String name,
			Date createdDate, Date lastModifiedDate,Boolean isActive,
			Set<CourseTermSubjectGroup> courseTermSubjectGroups,
			Set<ClassStudent> classStudents,
			Set<SubjectGroupSubjects> subjectGroupSubjectses, Set<Fee> fees,
			Set<FeeDetails> feeDetailses,
			Set<CurriculumSchemeSubject> curriculumSchemeSubjects,Set<ApplicantSubjectGroup> applicantSubjectGroups) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.course = course;
		this.name = name;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.courseTermSubjectGroups = courseTermSubjectGroups;
		this.classStudents = classStudents;
		this.subjectGroupSubjectses = subjectGroupSubjectses;
		this.fees = fees;
		this.feeDetailses = feeDetailses;
		this.curriculumSchemeSubjects = curriculumSchemeSubjects;
		this.applicantSubjectGroups=applicantSubjectGroups;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<CourseTermSubjectGroup> getCourseTermSubjectGroups() {
		return this.courseTermSubjectGroups;
	}

	public void setCourseTermSubjectGroups(
			Set<CourseTermSubjectGroup> courseTermSubjectGroups) {
		this.courseTermSubjectGroups = courseTermSubjectGroups;
	}

	public Set<ClassStudent> getClassStudents() {
		return this.classStudents;
	}

	public void setClassStudents(Set<ClassStudent> classStudents) {
		this.classStudents = classStudents;
	}

	public Set<SubjectGroupSubjects> getSubjectGroupSubjectses() {
		return this.subjectGroupSubjectses;
	}

	public void setSubjectGroupSubjectses(
			Set<SubjectGroupSubjects> subjectGroupSubjectses) {
		this.subjectGroupSubjectses = subjectGroupSubjectses;
	}

	public Set<Fee> getFees() {
		return this.fees;
	}

	public void setFees(Set<Fee> fees) {
		this.fees = fees;
	}

	public Set<FeeDetails> getFeeDetailses() {
		return this.feeDetailses;
	}

	public void setFeeDetailses(Set<FeeDetails> feeDetailses) {
		this.feeDetailses = feeDetailses;
	}

	public Set<CurriculumSchemeSubject> getCurriculumSchemeSubjects() {
		return this.curriculumSchemeSubjects;
	}

	public void setCurriculumSchemeSubjects(
			Set<CurriculumSchemeSubject> curriculumSchemeSubjects) {
		this.curriculumSchemeSubjects = curriculumSchemeSubjects;
	}

	public Set<ApplicantSubjectGroup> getApplicantSubjectGroups() {
		return applicantSubjectGroups;
	}

	public void setApplicantSubjectGroups(
			Set<ApplicantSubjectGroup> applicantSubjectGroups) {
		this.applicantSubjectGroups = applicantSubjectGroups;
	}



	public Integer getSecondLanguageId() {
		return secondLanguageId;
	}

	public void setSecondLanguageId(Integer secondLanguageId) {
		this.secondLanguageId = secondLanguageId;
	}

	public ExamSecondLanguageMasterBO getExamSecondLanguageMasterBO() {
		return examSecondLanguageMasterBO;
	}

	public void setExamSecondLanguageMasterBO(
			ExamSecondLanguageMasterBO examSecondLanguageMasterBO) {
		this.examSecondLanguageMasterBO = examSecondLanguageMasterBO;
	}

	public boolean getIsCommonSubGrp() {
		return isCommonSubGrp;
	}

	public void setIsCommonSubGrp(boolean isCommonSubGrp) {
		this.isCommonSubGrp = isCommonSubGrp;
	}
	
	

}
