package com.kp.cms.bo.admin;

import java.util.Date;

// Generated May 18, 2010 7:07:11 AM by Hibernate Tools 3.2.4.GA

/**
 * TeacherClassSubject generated by hbm2java
 */
/**
 * @author jismy.t
 *
 */
public class TeacherClassSubject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1787196203263266641L;
	private int id;
	private String year;
	private Users teacherId;
	private ClassSchemewise classId;
	private Subject subject;
	private String numericCode;
	private Boolean isActive;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	public TeacherClassSubject() {
		
	}

	public TeacherClassSubject(int id, String year, Users teacherId,
			ClassSchemewise classId, Subject subject,String numericCode,Boolean isActive,String createdBy,Date createdDate,String modifiedBy, Date lastModifiedDate) {
		super();
		this.id = id;
		this.year = year;
		this.teacherId = teacherId;
		this.classId = classId;
		this.subject = subject;
		this.numericCode=numericCode;
		this.isActive=isActive;
		this.createdBy=createdBy;
		this.modifiedBy=modifiedBy;
		this.createdDate=createdDate;
		this.lastModifiedDate=lastModifiedDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public Users getTeacherId() {
		return teacherId;
	}

	public void setTeacherId(Users teacherId) {
		this.teacherId = teacherId;
	}

	public ClassSchemewise getClassId() {
		return classId;
	}

	public void setClassId(ClassSchemewise classId) {
		this.classId = classId;
	}

	public Subject getSubject() {
		return subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}
	public String getNumericCode() {
		return numericCode;
	}

	public void setNumericCode(String numericCode) {
		this.numericCode = numericCode;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof TeacherClassSubject))
			return false;
		TeacherClassSubject other = (TeacherClassSubject) obj;
		if (id != other.id)
			return false;
		return true;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	

}
