package com.kp.cms.bo.admin;

// Generated Mar 9, 2009 5:02:52 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kp.cms.bo.admin.Employee;
import com.kp.cms.bo.admin.Roles;
import com.kp.cms.bo.admin.Student;
import com.kp.cms.bo.employee.GuestFaculty;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int id;
	private Student student;
	private Roles roles;
	private GuestFaculty guest;
	private Employee employee;
	private String userName;
	private String pwd;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Integer noOfRetries;
	private Date lastLoggedIn;
	private String ipAddress;
	private Boolean isLocked;
	private Boolean isLoggedIn;
	private Boolean isTeachingStaff;
	private Boolean isAddRemarks;
	private Boolean isViewRemarks;
	private Boolean isRestrictedUser;
	private Department department;
	private String staffType;
	private Boolean multipleLoginAllow;
	private Date tillDate;

	private Set<AttendanceInstructor> attendanceInstructors = new HashSet<AttendanceInstructor>(
			0);
	private Set<PcReceipts> pcReceipts = new HashSet<PcReceipts>(
			0);
	private Boolean enableAttendanceEntry;
	private Boolean active;
	private String androidPwd;

	public Users() {
	}

	public Users(int id, String userName, String pwd) {
		this.id = id;
		this.userName = userName;
		this.pwd = pwd;
	}

	

	public Users(int id, Student student, Roles roles, GuestFaculty guest,
			Employee employee, String userName, String pwd, String createdBy,
			Date createdDate, String modifiedBy, Date lastModifiedDate,
			Boolean isActive, Integer noOfRetries, Date lastLoggedIn,
			String ipAddress, Boolean isLocked, Boolean isLoggedIn,
			Boolean isTeachingStaff, Boolean isAddRemarks,
			Boolean isViewRemarks, Boolean isRestrictedUser,
			Department department, String staffType,
			Boolean multipleLoginAllow,
			Set<AttendanceInstructor> attendanceInstructors,
			Set<PcReceipts> pcReceipts, Boolean enableAttendanceEntry,
			Boolean active, String androidPwd) {
		super();
		this.id = id;
		this.student = student;
		this.roles = roles;
		this.guest = guest;
		this.employee = employee;
		this.userName = userName;
		this.pwd = pwd;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.noOfRetries = noOfRetries;
		this.lastLoggedIn = lastLoggedIn;
		this.ipAddress = ipAddress;
		this.isLocked = isLocked;
		this.isLoggedIn = isLoggedIn;
		this.isTeachingStaff = isTeachingStaff;
		this.isAddRemarks = isAddRemarks;
		this.isViewRemarks = isViewRemarks;
		this.isRestrictedUser = isRestrictedUser;
		this.department = department;
		this.staffType = staffType;
		this.multipleLoginAllow = multipleLoginAllow;
		this.attendanceInstructors = attendanceInstructors;
		this.pcReceipts = pcReceipts;
		this.enableAttendanceEntry = enableAttendanceEntry;
		this.active = active;
		this.androidPwd = androidPwd;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Integer getNoOfRetries() {
		return this.noOfRetries;
	}

	public void setNoOfRetries(Integer noOfRetries) {
		this.noOfRetries = noOfRetries;
	}

	public Date getLastLoggedIn() {
		return this.lastLoggedIn;
	}

	public void setLastLoggedIn(Date lastLoggedIn) {
		this.lastLoggedIn = lastLoggedIn;
	}
	

	public String getIpAddress() {
		return ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public Boolean getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(Boolean isLocked) {
		this.isLocked = isLocked;
	}

	public Boolean getIsLoggedIn() {
		return this.isLoggedIn;
	}

	public void setIsLoggedIn(Boolean isLoggedIn) {
		this.isLoggedIn = isLoggedIn;
	}

	public Boolean getIsTeachingStaff() {
		return isTeachingStaff;
	}

	public void setIsTeachingStaff(Boolean isTeachingStaff) {
		this.isTeachingStaff = isTeachingStaff;
	}

	public Set<AttendanceInstructor> getAttendanceInstructors() {
		return attendanceInstructors;
	}

	public void setAttendanceInstructors(
			Set<AttendanceInstructor> attendanceInstructors) {
		this.attendanceInstructors = attendanceInstructors;
	}

	public Boolean getIsAddRemarks() {
		return isAddRemarks;
	}

	public Boolean getIsViewRemarks() {
		return isViewRemarks;
	}

	public void setIsAddRemarks(Boolean isAddRemarks) {
		this.isAddRemarks = isAddRemarks;
	}

	public void setIsViewRemarks(Boolean isViewRemarks) {
		this.isViewRemarks = isViewRemarks;
	}

	public Set<PcReceipts> getPcReceipts() {
		return pcReceipts;
	}

	public void setPcReceipts(Set<PcReceipts> pcReceipts) {
		this.pcReceipts = pcReceipts;
	}

	public void setIsRestrictedUser(Boolean isRestrictedUser) {
		this.isRestrictedUser = isRestrictedUser;
	}

	public Boolean getIsRestrictedUser() {
		return isRestrictedUser;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Boolean getEnableAttendanceEntry() {
		return enableAttendanceEntry;
	}

	public void setEnableAttendanceEntry(Boolean enableAttendanceEntry) {
		this.enableAttendanceEntry = enableAttendanceEntry;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public String getAndroidPwd() {
		return androidPwd;
	}

	public void setAndroidPwd(String androidPwd) {
		this.androidPwd = androidPwd;
	}

	public GuestFaculty getGuest() {
		return guest;
	}

	public void setGuest(GuestFaculty guest) {
		this.guest = guest;
	}

	public String getStaffType() {
		return staffType;
	}

	public void setStaffType(String staffType) {
		this.staffType = staffType;
	}

	public Boolean getMultipleLoginAllow() {
		return multipleLoginAllow;
	}

	public void setMultipleLoginAllow(Boolean multipleLoginAllow) {
		this.multipleLoginAllow = multipleLoginAllow;
	}

	public Date getTillDate() {
		return tillDate;
	}

	public void setTillDate(Date tillDate) {
		this.tillDate = tillDate;
	}

	
	
	
	
}