package com.kp.cms.bo.admission;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
	/**
	 * Prerequisite generated by hbm2java
	 */
	@SuppressWarnings("serial")
	public class PrerequisitsYearMonth implements java.io.Serializable {

		private int id;
		private Integer year;
		private Integer month;
		private String createdBy;;
		private String modifiedBy;
		private Date createdDate;
		private Boolean isActive;
		private Date lastModifiedDate;
		private String monthName;
		
		public PrerequisitsYearMonth() {
		}

		public PrerequisitsYearMonth(int id) {
			this.id = id;
		}

		public PrerequisitsYearMonth(int id, String createdBy,
				String modifiedBy, Integer year, Integer month, Date createdDate,
				Date lastModifiedDate,  Boolean isActive) {
			this.id = id;
			this.createdBy = createdBy;
			this.modifiedBy = modifiedBy;
			this.year = year;
			this.month = month;
			this.createdDate = createdDate;
			this.lastModifiedDate = lastModifiedDate;
			this.isActive= isActive;
			
		}

		public int getId() {
			return id;
		}

		public void setId(int id) {
			this.id = id;
		}

		public Integer getYear() {
			return year;
		}

		public void setYear(Integer year) {
			this.year = year;
		}

		public Integer getMonth() {
			return month;
		}

		public void setMonth(Integer month) {
			this.month = month;
		}

		public String getCreatedBy() {
			return createdBy;
		}

		public void setCreatedBy(String createdBy) {
			this.createdBy = createdBy;
		}

		public String getModifiedBy() {
			return modifiedBy;
		}

		public void setModifiedBy(String modifiedBy) {
			this.modifiedBy = modifiedBy;
		}

		public Date getCreatedDate() {
			return createdDate;
		}

		public void setCreatedDate(Date createdDate) {
			this.createdDate = createdDate;
		}

		public Boolean getIsActive() {
			return isActive;
		}

		public void setIsActive(Boolean isActive) {
			this.isActive = isActive;
		}

		public Date getLastModifiedDate() {
			return lastModifiedDate;
		}

		public void setLastModifiedDate(Date lastModifiedDate) {
			this.lastModifiedDate = lastModifiedDate;
		}

		public String getMonthName() {
			return monthName;
		}

		public void setMonthName(String monthName) {
			this.monthName = monthName;
		}

	

		

	}



