package com.kp.cms.bo.admission;

// Generated Jan 12, 2009 6:38:21 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

import com.kp.cms.bo.admin.Caste;
import com.kp.cms.bo.admin.Category;
import com.kp.cms.bo.admin.City;
import com.kp.cms.bo.admin.College;
import com.kp.cms.bo.admin.Country;
import com.kp.cms.bo.admin.Recommendor;
import com.kp.cms.bo.admin.Religion;
import com.kp.cms.bo.admin.University;

/**
 * WeightageDefinition generated by hbm2java
 */
public class WeightageDefinition implements java.io.Serializable {

	private int id;
	private College college;
	private Recommendor recommendor;
	private Country country;

	private Weightage weightage;
	private University university;
	private Caste caste;
	private Religion religion;
	private City city;
	private BigDecimal religionWeightage;
	private BigDecimal casteWeightage;
	private BigDecimal countryWeightage;
	private BigDecimal cityWeightage;
	private BigDecimal lastUniversityWeightage;
	private BigDecimal lastCollegeWeightage;

	private BigDecimal referredByWeightage;
	private String gender;
	private BigDecimal genderWeightage;

	public WeightageDefinition() {
	}

	public WeightageDefinition(int id) {
		this.id = id;
	}

	public WeightageDefinition(int id, College college,
			Recommendor recommendor, Country country, Category category,
			Weightage weightage, University university, Caste caste,
			Religion religion, City city, BigDecimal religionWeightage,
			BigDecimal casteWeightage, BigDecimal countryWeightage,
			BigDecimal cityWeightage, BigDecimal lastUniversityWeightage,
			BigDecimal lastCollegeWeightage, BigDecimal categoryWeightage,
			BigDecimal referredByWeightage, String gender,
			BigDecimal genderWeightage) {
		this.id = id;
		this.college = college;
		this.recommendor = recommendor;
		this.country = country;
		this.weightage = weightage;
		this.university = university;
		this.caste = caste;
		this.religion = religion;
		this.city = city;
		this.religionWeightage = religionWeightage;
		this.casteWeightage = casteWeightage;
		this.countryWeightage = countryWeightage;
		this.cityWeightage = cityWeightage;
		this.lastUniversityWeightage = lastUniversityWeightage;
		this.lastCollegeWeightage = lastCollegeWeightage;
		this.referredByWeightage = referredByWeightage;
		this.gender = gender;
		this.genderWeightage = genderWeightage;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public College getCollege() {
		return this.college;
	}

	public void setCollege(College college) {
		this.college = college;
	}

	public Recommendor getRecommendor() {
		return this.recommendor;
	}

	public void setRecommendor(Recommendor recommendor) {
		this.recommendor = recommendor;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public Weightage getWeightage() {
		return this.weightage;
	}

	public void setWeightage(Weightage weightage) {
		this.weightage = weightage;
	}

	public University getUniversity() {
		return this.university;
	}

	public void setUniversity(University university) {
		this.university = university;
	}

	public Caste getCaste() {
		return this.caste;
	}

	public void setCaste(Caste caste) {
		this.caste = caste;
	}

	public Religion getReligion() {
		return this.religion;
	}

	public void setReligion(Religion religion) {
		this.religion = religion;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public BigDecimal getReligionWeightage() {
		return this.religionWeightage;
	}

	public void setReligionWeightage(BigDecimal religionWeightage) {
		this.religionWeightage = religionWeightage;
	}

	public BigDecimal getCasteWeightage() {
		return this.casteWeightage;
	}

	public void setCasteWeightage(BigDecimal casteWeightage) {
		this.casteWeightage = casteWeightage;
	}

	public BigDecimal getCountryWeightage() {
		return this.countryWeightage;
	}

	public void setCountryWeightage(BigDecimal countryWeightage) {
		this.countryWeightage = countryWeightage;
	}

	public BigDecimal getCityWeightage() {
		return this.cityWeightage;
	}

	public void setCityWeightage(BigDecimal cityWeightage) {
		this.cityWeightage = cityWeightage;
	}

	public BigDecimal getLastUniversityWeightage() {
		return this.lastUniversityWeightage;
	}

	public void setLastUniversityWeightage(BigDecimal lastUniversityWeightage) {
		this.lastUniversityWeightage = lastUniversityWeightage;
	}

	public BigDecimal getLastCollegeWeightage() {
		return this.lastCollegeWeightage;
	}

	public void setLastCollegeWeightage(BigDecimal lastCollegeWeightage) {
		this.lastCollegeWeightage = lastCollegeWeightage;
	}

	public BigDecimal getReferredByWeightage() {
		return this.referredByWeightage;
	}

	public void setReferredByWeightage(BigDecimal referredByWeightage) {
		this.referredByWeightage = referredByWeightage;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public BigDecimal getGenderWeightage() {
		return this.genderWeightage;
	}

	public void setGenderWeightage(BigDecimal genderWeightage) {
		this.genderWeightage = genderWeightage;
	}

}
