package com.kp.cms.bo.exam;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kp.cms.bo.admin.EligibilityCriteria;
import com.kp.cms.bo.admin.EligibleSubjects;

/**
 * ExamType generated by hbm2java
 */
public class ExamType implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private String name;
	private Date createdDate;
	private Date lastModifiedDate;
	private Set<EligibleSubjects> eligibleSubjectses = new HashSet<EligibleSubjects>(
			0);
	private Set<EligibilityCriteria> eligibilityCriterias = new HashSet<EligibilityCriteria>(
			0);

	public ExamType() {
	}

	public ExamType(int id) {
		this.id = id;
	}

	public ExamType(int id, String createdBy,
			String modifiedBy, String name, Date createdDate,
			Date lastModifiedDate, Set<EligibleSubjects> eligibleSubjectses,
			Set<EligibilityCriteria> eligibilityCriterias) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.name = name;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.eligibleSubjectses = eligibleSubjectses;
		this.eligibilityCriterias = eligibilityCriterias;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<EligibleSubjects> getEligibleSubjectses() {
		return this.eligibleSubjectses;
	}

	public void setEligibleSubjectses(Set<EligibleSubjects> eligibleSubjectses) {
		this.eligibleSubjectses = eligibleSubjectses;
	}

	public Set<EligibilityCriteria> getEligibilityCriterias() {
		return this.eligibilityCriterias;
	}

	public void setEligibilityCriterias(
			Set<EligibilityCriteria> eligibilityCriterias) {
		this.eligibilityCriterias = eligibilityCriterias;
	}

}
