package com.kp.cms.bo.exam;
// Generated Feb 8, 2011 10:52:35 AM by Hibernate Tools 3.2.6.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import com.kp.cms.bo.admin.Course;
import com.kp.cms.bo.admin.Subject;

/**
 * ExamSubjectRuleSettings generated by hbm2java
 */
public class SubjectRuleSettings implements java.io.Serializable {

	private Integer id;
	private Integer academicYear;
//	private Integer courseId;
	private Integer schemeNo;
//	private Integer subjectId;
	private Subject subject;
	private Course course;
	private Integer selectBestOfTheoryInternal;
	private Boolean finalTheoryInternalIsSubInternal;
	private Boolean finalTheoryInternalIsAttendance;
	private Boolean finalTheoryInternalIsAssignment;
	private BigDecimal finalTheoryInternalMinimumMark;
	private BigDecimal finalTheoryInternalEnteredMaxMark;
	private BigDecimal finalTheoryInternalMaximumMark;
	private Integer selectBestOfPracticalInternal;
	private Boolean finalPracticalInternalIsSubInternal;
	private Boolean finalPracticalInternalIsAttendance;
	private Boolean finalPracticalInternalIsAssignment;
	private BigDecimal finalPracticalInternalMinimumMark;
	private BigDecimal finalPracticalInternalEnteredMaxMark;
	private BigDecimal finalPracticalInternalMaximumMark;
	private Boolean theoryEseIsRegular;
	private Boolean theoryEseIsMultipleAnswerScript;
	private Boolean theoryEseIsMultipleEvaluator;
	private BigDecimal theoryEseMinimumMark;
	private BigDecimal theoryEseEnteredMaxMark;
	private BigDecimal theoryEseMaximumMark;
	private BigDecimal theoryEseTheoryFinalMinimumMark;
	private BigDecimal theoryEseTheoryFinalMaximumMark;
	private Boolean practicalEseIsRegular;
	private Boolean practicalEseIsMultipleAnswerScript;
	private Boolean practicalEseIsMultipleEvaluator;
	private BigDecimal practicalEseMinimumMark;
	private BigDecimal practicalEseEnteredMaxMark;
	private BigDecimal practicalEseMaximumMark;
	private BigDecimal practicalEseTheoryFinalMinimumMark;
	private BigDecimal practicalEseTheoryFinalMaximumMark;
	private Boolean subjectFinalIsTheoryExam;
	private Boolean subjectFinalIsPracticalExam;
	private Boolean subjectFinalIsInternalExam;
	private Boolean subjectFinalIsAttendance;
	private BigDecimal subjectFinalMinimum;
	private BigDecimal subjectFinalMaximum;
	private BigDecimal subjectFinalValuated;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private BigDecimal theoryIntMinMarksTotal;
	private BigDecimal theoryIntMaxMarksTotal;
	private BigDecimal theoryIntEntryMaxMarksTotal;
	private BigDecimal practicalIntMinMarksTotal;
	private BigDecimal practicalIntMaxMarksTotal;
	private BigDecimal practicalIntEntryMaxMarksTotal;
	private Set<SubjectRuleSettingsMulAnsScript> examSubjectRuleSettingsMulAnsScripts;
	private Set<SubjectRuleSettingsSubInternal> examSubjectRuleSettingsSubInternals;
	private Set<SubjectRuleSettingsAttendance> examSubjectRuleSettingsAttendances;
	private Set<SubjectRuleSettingsMulEvaluator> examSubjectRuleSettingsMulEvaluators;
	private Set<SubjectRuleSettingsAssignment> examSubjectRuleSettingsAssignments;
	private BigDecimal theorySupplementaryMinMarksTotal;
	private BigDecimal theorySupplementaryMaxMarksTotal; 
	private BigDecimal practicalSupplementaryMinMarksTotal;
	private BigDecimal practicalSupplementaryMaxMarksTotal; 
	private Boolean theoryIsSupplementary;
	private Boolean practicalIsSupplementary;

	public SubjectRuleSettings() {
	}

	public SubjectRuleSettings(Integer academicYear, Course course,
			Integer schemeNo, Subject subject,
			Integer selectBestOfTheoryInternal,
			Boolean finalTheoryInternalIsSubInternal,
			Boolean finalTheoryInternalIsAttendance,
			Boolean finalTheoryInternalIsAssignment,
			BigDecimal finalTheoryInternalMinimumMark,
			BigDecimal finalTheoryInternalEnteredMaxMark,
			BigDecimal finalTheoryInternalMaximumMark,
			Integer selectBestOfPracticalInternal,
			Boolean finalPracticalInternalIsSubInternal,
			Boolean finalPracticalInternalIsAttendance,
			Boolean finalPracticalInternalIsAssignment,
			BigDecimal finalPracticalInternalMinimumMark,
			BigDecimal finalPracticalInternalEnteredMaxMark,
			BigDecimal finalPracticalInternalMaximumMark,
			Boolean theoryEseIsRegular,
			Boolean theoryEseIsMultipleAnswerScript,
			Boolean theoryEseIsMultipleEvaluator,
			BigDecimal theoryEseMinimumMark,
			BigDecimal theoryEseEnteredMaxMark,
			BigDecimal theoryEseMaximumMark,
			BigDecimal theoryEseTheoryFinalMinimumMark,
			BigDecimal theoryEseTheoryFinalMaximumMark,
			Boolean practicalEseIsRegular,
			Boolean practicalEseIsMultipleAnswerScript,
			Boolean practicalEseIsMultipleEvaluator,
			BigDecimal practicalEseMinimumMark,
			BigDecimal practicalEseEnteredMaxMark,
			BigDecimal practicalEseMaximumMark,
			BigDecimal practicalEseTheoryFinalMinimumMark,
			BigDecimal practicalEseTheoryFinalMaximumMark,
			Boolean subjectFinalIsTheoryExam,
			Boolean subjectFinalIsPracticalExam,
			Boolean subjectFinalIsInternalExam,
			Boolean subjectFinalIsAttendance, BigDecimal subjectFinalMinimum,
			BigDecimal subjectFinalMaximum, BigDecimal subjectFinalValuated,
			String createdBy, Date createdDate, String modifiedBy,
			Date lastModifiedDate, Boolean isActive,
			BigDecimal theoryIntMinMarksTotal,
			BigDecimal theoryIntMaxMarksTotal,
			BigDecimal theoryIntEntryMaxMarksTotal,
			BigDecimal practicalIntMinMarksTotal,
			BigDecimal practicalIntMaxMarksTotal,
			BigDecimal practicalIntEntryMaxMarksTotal,
			Set<SubjectRuleSettingsMulAnsScript> examSubjectRuleSettingsMulAnsScripts,
			Set<SubjectRuleSettingsSubInternal> examSubjectRuleSettingsSubInternals,
			Set<SubjectRuleSettingsAttendance> examSubjectRuleSettingsAttendances,
			Set<SubjectRuleSettingsMulEvaluator> examSubjectRuleSettingsMulEvaluators,
			Set<SubjectRuleSettingsAssignment> examSubjectRuleSettingsAssignments,BigDecimal theorySupplementaryMinMarksTotal,
			BigDecimal theorySupplementaryMaxMarksTotal,BigDecimal practicalSupplementaryMinMarksTotal,BigDecimal practicalSupplementaryMaxMarksTotal,Boolean theoryIsSupplementary,Boolean practicalIsSupplementary) {
		this.academicYear = academicYear;
		this.course = course;
		this.schemeNo = schemeNo;
		this.subject = subject;
		this.selectBestOfTheoryInternal = selectBestOfTheoryInternal;
		this.finalTheoryInternalIsSubInternal = finalTheoryInternalIsSubInternal;
		this.finalTheoryInternalIsAttendance = finalTheoryInternalIsAttendance;
		this.finalTheoryInternalIsAssignment = finalTheoryInternalIsAssignment;
		this.finalTheoryInternalMinimumMark = finalTheoryInternalMinimumMark;
		this.finalTheoryInternalEnteredMaxMark = finalTheoryInternalEnteredMaxMark;
		this.finalTheoryInternalMaximumMark = finalTheoryInternalMaximumMark;
		this.selectBestOfPracticalInternal = selectBestOfPracticalInternal;
		this.finalPracticalInternalIsSubInternal = finalPracticalInternalIsSubInternal;
		this.finalPracticalInternalIsAttendance = finalPracticalInternalIsAttendance;
		this.finalPracticalInternalIsAssignment = finalPracticalInternalIsAssignment;
		this.finalPracticalInternalMinimumMark = finalPracticalInternalMinimumMark;
		this.finalPracticalInternalEnteredMaxMark = finalPracticalInternalEnteredMaxMark;
		this.finalPracticalInternalMaximumMark = finalPracticalInternalMaximumMark;
		this.theoryEseIsRegular = theoryEseIsRegular;
		this.theoryEseIsMultipleAnswerScript = theoryEseIsMultipleAnswerScript;
		this.theoryEseIsMultipleEvaluator = theoryEseIsMultipleEvaluator;
		this.theoryEseMinimumMark = theoryEseMinimumMark;
		this.theoryEseEnteredMaxMark = theoryEseEnteredMaxMark;
		this.theoryEseMaximumMark = theoryEseMaximumMark;
		this.theoryEseTheoryFinalMinimumMark = theoryEseTheoryFinalMinimumMark;
		this.theoryEseTheoryFinalMaximumMark = theoryEseTheoryFinalMaximumMark;
		this.practicalEseIsRegular = practicalEseIsRegular;
		this.practicalEseIsMultipleAnswerScript = practicalEseIsMultipleAnswerScript;
		this.practicalEseIsMultipleEvaluator = practicalEseIsMultipleEvaluator;
		this.practicalEseMinimumMark = practicalEseMinimumMark;
		this.practicalEseEnteredMaxMark = practicalEseEnteredMaxMark;
		this.practicalEseMaximumMark = practicalEseMaximumMark;
		this.practicalEseTheoryFinalMinimumMark = practicalEseTheoryFinalMinimumMark;
		this.practicalEseTheoryFinalMaximumMark = practicalEseTheoryFinalMaximumMark;
		this.subjectFinalIsTheoryExam = subjectFinalIsTheoryExam;
		this.subjectFinalIsPracticalExam = subjectFinalIsPracticalExam;
		this.subjectFinalIsInternalExam = subjectFinalIsInternalExam;
		this.subjectFinalIsAttendance = subjectFinalIsAttendance;
		this.subjectFinalMinimum = subjectFinalMinimum;
		this.subjectFinalMaximum = subjectFinalMaximum;
		this.subjectFinalValuated = subjectFinalValuated;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.isActive = isActive;
		this.theoryIntMinMarksTotal = theoryIntMinMarksTotal;
		this.theoryIntMaxMarksTotal = theoryIntMaxMarksTotal;
		this.theoryIntEntryMaxMarksTotal = theoryIntEntryMaxMarksTotal;
		this.practicalIntMinMarksTotal = practicalIntMinMarksTotal;
		this.practicalIntMaxMarksTotal = practicalIntMaxMarksTotal;
		this.practicalIntEntryMaxMarksTotal = practicalIntEntryMaxMarksTotal;
		this.examSubjectRuleSettingsMulAnsScripts = examSubjectRuleSettingsMulAnsScripts;
		this.examSubjectRuleSettingsSubInternals = examSubjectRuleSettingsSubInternals;
		this.examSubjectRuleSettingsAttendances = examSubjectRuleSettingsAttendances;
		this.examSubjectRuleSettingsMulEvaluators = examSubjectRuleSettingsMulEvaluators;
		this.examSubjectRuleSettingsAssignments = examSubjectRuleSettingsAssignments;
		this.theorySupplementaryMinMarksTotal=theorySupplementaryMinMarksTotal;
		this.theorySupplementaryMaxMarksTotal=theorySupplementaryMaxMarksTotal; 
		this.practicalSupplementaryMinMarksTotal=practicalSupplementaryMinMarksTotal;
		this.practicalSupplementaryMaxMarksTotal=practicalSupplementaryMaxMarksTotal;
		this.practicalIsSupplementary=practicalIsSupplementary;
		this.theoryIsSupplementary=theoryIsSupplementary;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAcademicYear() {
		return this.academicYear;
	}

	public void setAcademicYear(Integer academicYear) {
		this.academicYear = academicYear;
	}


	public Integer getSchemeNo() {
		return this.schemeNo;
	}

	public void setSchemeNo(Integer schemeNo) {
		this.schemeNo = schemeNo;
	}

	public Integer getSelectBestOfTheoryInternal() {
		return this.selectBestOfTheoryInternal;
	}

	public void setSelectBestOfTheoryInternal(Integer selectBestOfTheoryInternal) {
		this.selectBestOfTheoryInternal = selectBestOfTheoryInternal;
	}

	public Boolean getFinalTheoryInternalIsSubInternal() {
		return this.finalTheoryInternalIsSubInternal;
	}

	public void setFinalTheoryInternalIsSubInternal(
			Boolean finalTheoryInternalIsSubInternal) {
		this.finalTheoryInternalIsSubInternal = finalTheoryInternalIsSubInternal;
	}

	public Boolean getFinalTheoryInternalIsAttendance() {
		return this.finalTheoryInternalIsAttendance;
	}

	public void setFinalTheoryInternalIsAttendance(
			Boolean finalTheoryInternalIsAttendance) {
		this.finalTheoryInternalIsAttendance = finalTheoryInternalIsAttendance;
	}

	public Boolean getFinalTheoryInternalIsAssignment() {
		return this.finalTheoryInternalIsAssignment;
	}

	public void setFinalTheoryInternalIsAssignment(
			Boolean finalTheoryInternalIsAssignment) {
		this.finalTheoryInternalIsAssignment = finalTheoryInternalIsAssignment;
	}

	public BigDecimal getFinalTheoryInternalMinimumMark() {
		return this.finalTheoryInternalMinimumMark;
	}

	public void setFinalTheoryInternalMinimumMark(
			BigDecimal finalTheoryInternalMinimumMark) {
		this.finalTheoryInternalMinimumMark = finalTheoryInternalMinimumMark;
	}

	public BigDecimal getFinalTheoryInternalEnteredMaxMark() {
		return this.finalTheoryInternalEnteredMaxMark;
	}

	public void setFinalTheoryInternalEnteredMaxMark(
			BigDecimal finalTheoryInternalEnteredMaxMark) {
		this.finalTheoryInternalEnteredMaxMark = finalTheoryInternalEnteredMaxMark;
	}

	public BigDecimal getFinalTheoryInternalMaximumMark() {
		return this.finalTheoryInternalMaximumMark;
	}

	public void setFinalTheoryInternalMaximumMark(
			BigDecimal finalTheoryInternalMaximumMark) {
		this.finalTheoryInternalMaximumMark = finalTheoryInternalMaximumMark;
	}

	public Integer getSelectBestOfPracticalInternal() {
		return this.selectBestOfPracticalInternal;
	}

	public void setSelectBestOfPracticalInternal(
			Integer selectBestOfPracticalInternal) {
		this.selectBestOfPracticalInternal = selectBestOfPracticalInternal;
	}

	public Boolean getFinalPracticalInternalIsSubInternal() {
		return this.finalPracticalInternalIsSubInternal;
	}

	public void setFinalPracticalInternalIsSubInternal(
			Boolean finalPracticalInternalIsSubInternal) {
		this.finalPracticalInternalIsSubInternal = finalPracticalInternalIsSubInternal;
	}

	public Boolean getFinalPracticalInternalIsAttendance() {
		return this.finalPracticalInternalIsAttendance;
	}

	public void setFinalPracticalInternalIsAttendance(
			Boolean finalPracticalInternalIsAttendance) {
		this.finalPracticalInternalIsAttendance = finalPracticalInternalIsAttendance;
	}

	public Boolean getFinalPracticalInternalIsAssignment() {
		return this.finalPracticalInternalIsAssignment;
	}

	public void setFinalPracticalInternalIsAssignment(
			Boolean finalPracticalInternalIsAssignment) {
		this.finalPracticalInternalIsAssignment = finalPracticalInternalIsAssignment;
	}

	public BigDecimal getFinalPracticalInternalMinimumMark() {
		return this.finalPracticalInternalMinimumMark;
	}

	public void setFinalPracticalInternalMinimumMark(
			BigDecimal finalPracticalInternalMinimumMark) {
		this.finalPracticalInternalMinimumMark = finalPracticalInternalMinimumMark;
	}

	public BigDecimal getFinalPracticalInternalEnteredMaxMark() {
		return this.finalPracticalInternalEnteredMaxMark;
	}

	public void setFinalPracticalInternalEnteredMaxMark(
			BigDecimal finalPracticalInternalEnteredMaxMark) {
		this.finalPracticalInternalEnteredMaxMark = finalPracticalInternalEnteredMaxMark;
	}

	public BigDecimal getFinalPracticalInternalMaximumMark() {
		return this.finalPracticalInternalMaximumMark;
	}

	public void setFinalPracticalInternalMaximumMark(
			BigDecimal finalPracticalInternalMaximumMark) {
		this.finalPracticalInternalMaximumMark = finalPracticalInternalMaximumMark;
	}

	public Boolean getTheoryEseIsRegular() {
		return this.theoryEseIsRegular;
	}

	public void setTheoryEseIsRegular(Boolean theoryEseIsRegular) {
		this.theoryEseIsRegular = theoryEseIsRegular;
	}

	public Boolean getTheoryEseIsMultipleAnswerScript() {
		return this.theoryEseIsMultipleAnswerScript;
	}

	public void setTheoryEseIsMultipleAnswerScript(
			Boolean theoryEseIsMultipleAnswerScript) {
		this.theoryEseIsMultipleAnswerScript = theoryEseIsMultipleAnswerScript;
	}

	public Boolean getTheoryEseIsMultipleEvaluator() {
		return this.theoryEseIsMultipleEvaluator;
	}

	public void setTheoryEseIsMultipleEvaluator(
			Boolean theoryEseIsMultipleEvaluator) {
		this.theoryEseIsMultipleEvaluator = theoryEseIsMultipleEvaluator;
	}

	public BigDecimal getTheoryEseMinimumMark() {
		return this.theoryEseMinimumMark;
	}

	public void setTheoryEseMinimumMark(BigDecimal theoryEseMinimumMark) {
		this.theoryEseMinimumMark = theoryEseMinimumMark;
	}

	public BigDecimal getTheoryEseEnteredMaxMark() {
		return this.theoryEseEnteredMaxMark;
	}

	public void setTheoryEseEnteredMaxMark(BigDecimal theoryEseEnteredMaxMark) {
		this.theoryEseEnteredMaxMark = theoryEseEnteredMaxMark;
	}

	public BigDecimal getTheoryEseMaximumMark() {
		return this.theoryEseMaximumMark;
	}

	public void setTheoryEseMaximumMark(BigDecimal theoryEseMaximumMark) {
		this.theoryEseMaximumMark = theoryEseMaximumMark;
	}

	public BigDecimal getTheoryEseTheoryFinalMinimumMark() {
		return this.theoryEseTheoryFinalMinimumMark;
	}

	public void setTheoryEseTheoryFinalMinimumMark(
			BigDecimal theoryEseTheoryFinalMinimumMark) {
		this.theoryEseTheoryFinalMinimumMark = theoryEseTheoryFinalMinimumMark;
	}

	public BigDecimal getTheoryEseTheoryFinalMaximumMark() {
		return this.theoryEseTheoryFinalMaximumMark;
	}

	public void setTheoryEseTheoryFinalMaximumMark(
			BigDecimal theoryEseTheoryFinalMaximumMark) {
		this.theoryEseTheoryFinalMaximumMark = theoryEseTheoryFinalMaximumMark;
	}

	public Boolean getPracticalEseIsRegular() {
		return this.practicalEseIsRegular;
	}

	public void setPracticalEseIsRegular(Boolean practicalEseIsRegular) {
		this.practicalEseIsRegular = practicalEseIsRegular;
	}

	public Boolean getPracticalEseIsMultipleAnswerScript() {
		return this.practicalEseIsMultipleAnswerScript;
	}

	public void setPracticalEseIsMultipleAnswerScript(
			Boolean practicalEseIsMultipleAnswerScript) {
		this.practicalEseIsMultipleAnswerScript = practicalEseIsMultipleAnswerScript;
	}

	public Boolean getPracticalEseIsMultipleEvaluator() {
		return this.practicalEseIsMultipleEvaluator;
	}

	public void setPracticalEseIsMultipleEvaluator(
			Boolean practicalEseIsMultipleEvaluator) {
		this.practicalEseIsMultipleEvaluator = practicalEseIsMultipleEvaluator;
	}

	public BigDecimal getPracticalEseMinimumMark() {
		return this.practicalEseMinimumMark;
	}

	public void setPracticalEseMinimumMark(BigDecimal practicalEseMinimumMark) {
		this.practicalEseMinimumMark = practicalEseMinimumMark;
	}

	public BigDecimal getPracticalEseEnteredMaxMark() {
		return this.practicalEseEnteredMaxMark;
	}

	public void setPracticalEseEnteredMaxMark(
			BigDecimal practicalEseEnteredMaxMark) {
		this.practicalEseEnteredMaxMark = practicalEseEnteredMaxMark;
	}

	public BigDecimal getPracticalEseMaximumMark() {
		return this.practicalEseMaximumMark;
	}

	public void setPracticalEseMaximumMark(BigDecimal practicalEseMaximumMark) {
		this.practicalEseMaximumMark = practicalEseMaximumMark;
	}

	public BigDecimal getPracticalEseTheoryFinalMinimumMark() {
		return this.practicalEseTheoryFinalMinimumMark;
	}

	public void setPracticalEseTheoryFinalMinimumMark(
			BigDecimal practicalEseTheoryFinalMinimumMark) {
		this.practicalEseTheoryFinalMinimumMark = practicalEseTheoryFinalMinimumMark;
	}

	public BigDecimal getPracticalEseTheoryFinalMaximumMark() {
		return this.practicalEseTheoryFinalMaximumMark;
	}

	public void setPracticalEseTheoryFinalMaximumMark(
			BigDecimal practicalEseTheoryFinalMaximumMark) {
		this.practicalEseTheoryFinalMaximumMark = practicalEseTheoryFinalMaximumMark;
	}

	public Boolean getSubjectFinalIsTheoryExam() {
		return this.subjectFinalIsTheoryExam;
	}

	public void setSubjectFinalIsTheoryExam(Boolean subjectFinalIsTheoryExam) {
		this.subjectFinalIsTheoryExam = subjectFinalIsTheoryExam;
	}

	public Boolean getSubjectFinalIsPracticalExam() {
		return this.subjectFinalIsPracticalExam;
	}

	public void setSubjectFinalIsPracticalExam(
			Boolean subjectFinalIsPracticalExam) {
		this.subjectFinalIsPracticalExam = subjectFinalIsPracticalExam;
	}

	public Boolean getSubjectFinalIsInternalExam() {
		return this.subjectFinalIsInternalExam;
	}

	public void setSubjectFinalIsInternalExam(Boolean subjectFinalIsInternalExam) {
		this.subjectFinalIsInternalExam = subjectFinalIsInternalExam;
	}

	public Boolean getSubjectFinalIsAttendance() {
		return this.subjectFinalIsAttendance;
	}

	public void setSubjectFinalIsAttendance(Boolean subjectFinalIsAttendance) {
		this.subjectFinalIsAttendance = subjectFinalIsAttendance;
	}

	public BigDecimal getSubjectFinalMinimum() {
		return this.subjectFinalMinimum;
	}

	public void setSubjectFinalMinimum(BigDecimal subjectFinalMinimum) {
		this.subjectFinalMinimum = subjectFinalMinimum;
	}

	public BigDecimal getSubjectFinalMaximum() {
		return this.subjectFinalMaximum;
	}

	public void setSubjectFinalMaximum(BigDecimal subjectFinalMaximum) {
		this.subjectFinalMaximum = subjectFinalMaximum;
	}

	public BigDecimal getSubjectFinalValuated() {
		return this.subjectFinalValuated;
	}

	public void setSubjectFinalValuated(BigDecimal subjectFinalValuated) {
		this.subjectFinalValuated = subjectFinalValuated;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public BigDecimal getTheoryIntMinMarksTotal() {
		return this.theoryIntMinMarksTotal;
	}

	public void setTheoryIntMinMarksTotal(BigDecimal theoryIntMinMarksTotal) {
		this.theoryIntMinMarksTotal = theoryIntMinMarksTotal;
	}

	public BigDecimal getTheoryIntMaxMarksTotal() {
		return this.theoryIntMaxMarksTotal;
	}

	public void setTheoryIntMaxMarksTotal(BigDecimal theoryIntMaxMarksTotal) {
		this.theoryIntMaxMarksTotal = theoryIntMaxMarksTotal;
	}

	public BigDecimal getTheoryIntEntryMaxMarksTotal() {
		return this.theoryIntEntryMaxMarksTotal;
	}

	public void setTheoryIntEntryMaxMarksTotal(
			BigDecimal theoryIntEntryMaxMarksTotal) {
		this.theoryIntEntryMaxMarksTotal = theoryIntEntryMaxMarksTotal;
	}

	public BigDecimal getPracticalIntMinMarksTotal() {
		return this.practicalIntMinMarksTotal;
	}

	public void setPracticalIntMinMarksTotal(
			BigDecimal practicalIntMinMarksTotal) {
		this.practicalIntMinMarksTotal = practicalIntMinMarksTotal;
	}

	public BigDecimal getPracticalIntMaxMarksTotal() {
		return this.practicalIntMaxMarksTotal;
	}

	public void setPracticalIntMaxMarksTotal(
			BigDecimal practicalIntMaxMarksTotal) {
		this.practicalIntMaxMarksTotal = practicalIntMaxMarksTotal;
	}

	public BigDecimal getPracticalIntEntryMaxMarksTotal() {
		return this.practicalIntEntryMaxMarksTotal;
	}

	public void setPracticalIntEntryMaxMarksTotal(
			BigDecimal practicalIntEntryMaxMarksTotal) {
		this.practicalIntEntryMaxMarksTotal = practicalIntEntryMaxMarksTotal;
	}

	public Set<SubjectRuleSettingsMulAnsScript> getExamSubjectRuleSettingsMulAnsScripts() {
		return examSubjectRuleSettingsMulAnsScripts;
	}

	public void setExamSubjectRuleSettingsMulAnsScripts(
			Set<SubjectRuleSettingsMulAnsScript> examSubjectRuleSettingsMulAnsScripts) {
		this.examSubjectRuleSettingsMulAnsScripts = examSubjectRuleSettingsMulAnsScripts;
	}

	public Set<SubjectRuleSettingsSubInternal> getExamSubjectRuleSettingsSubInternals() {
		return examSubjectRuleSettingsSubInternals;
	}

	public void setExamSubjectRuleSettingsSubInternals(
			Set<SubjectRuleSettingsSubInternal> examSubjectRuleSettingsSubInternals) {
		this.examSubjectRuleSettingsSubInternals = examSubjectRuleSettingsSubInternals;
	}

	public Set<SubjectRuleSettingsAttendance> getExamSubjectRuleSettingsAttendances() {
		return examSubjectRuleSettingsAttendances;
	}

	public void setExamSubjectRuleSettingsAttendances(
			Set<SubjectRuleSettingsAttendance> examSubjectRuleSettingsAttendances) {
		this.examSubjectRuleSettingsAttendances = examSubjectRuleSettingsAttendances;
	}

	public Set<SubjectRuleSettingsMulEvaluator> getExamSubjectRuleSettingsMulEvaluators() {
		return examSubjectRuleSettingsMulEvaluators;
	}

	public void setExamSubjectRuleSettingsMulEvaluators(
			Set<SubjectRuleSettingsMulEvaluator> examSubjectRuleSettingsMulEvaluators) {
		this.examSubjectRuleSettingsMulEvaluators = examSubjectRuleSettingsMulEvaluators;
	}

	public Set<SubjectRuleSettingsAssignment> getExamSubjectRuleSettingsAssignments() {
		return examSubjectRuleSettingsAssignments;
	}

	public void setExamSubjectRuleSettingsAssignments(
			Set<SubjectRuleSettingsAssignment> examSubjectRuleSettingsAssignments) {
		this.examSubjectRuleSettingsAssignments = examSubjectRuleSettingsAssignments;
	}

	public BigDecimal getTheorySupplementaryMinMarksTotal() {
		return theorySupplementaryMinMarksTotal;
	}

	public void setTheorySupplementaryMinMarksTotal(
			BigDecimal theorySupplementaryMinMarksTotal) {
		this.theorySupplementaryMinMarksTotal = theorySupplementaryMinMarksTotal;
	}

	public BigDecimal getTheorySupplementaryMaxMarksTotal() {
		return theorySupplementaryMaxMarksTotal;
	}

	public void setTheorySupplementaryMaxMarksTotal(
			BigDecimal theorySupplementaryMaxMarksTotal) {
		this.theorySupplementaryMaxMarksTotal = theorySupplementaryMaxMarksTotal;
	}

	public BigDecimal getPracticalSupplementaryMinMarksTotal() {
		return practicalSupplementaryMinMarksTotal;
	}

	public void setPracticalSupplementaryMinMarksTotal(
			BigDecimal practicalSupplementaryMinMarksTotal) {
		this.practicalSupplementaryMinMarksTotal = practicalSupplementaryMinMarksTotal;
	}

	public BigDecimal getPracticalSupplementaryMaxMarksTotal() {
		return practicalSupplementaryMaxMarksTotal;
	}

	public void setPracticalSupplementaryMaxMarksTotal(
			BigDecimal practicalSupplementaryMaxMarksTotal) {
		this.practicalSupplementaryMaxMarksTotal = practicalSupplementaryMaxMarksTotal;
	}

	public Boolean getTheoryIsSupplementary() {
		return theoryIsSupplementary;
	}

	public void setTheoryIsSupplementary(Boolean theoryIsSupplementary) {
		this.theoryIsSupplementary = theoryIsSupplementary;
	}

	public Boolean getPracticalIsSupplementary() {
		return practicalIsSupplementary;
	}

	public void setPracticalIsSupplementary(Boolean practicalIsSupplementary) {
		this.practicalIsSupplementary = practicalIsSupplementary;
	}

	public Subject getSubject() {
		return subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}
}
