package com.kp.cms.bo.exam;

import java.util.Date;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

/**
 * ApplicationNumber generated by hbm2java
 */
public class ValuationChallanNumber implements java.io.Serializable {

	private int id;
	private String billNoFrom;
	private String billNoTo;
	private String currentBillNo;
	private String externalBillNoFrom;
	private String externalCurrentBillNo;
	private Boolean isActive;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	
	public ValuationChallanNumber(){
		
	}
	
	public ValuationChallanNumber(int id, String billNoFrom, String billNoTo,
			Boolean isActive, String createdBy, Date createdDate,
			String modifiedBy, Date lastModifiedDate,String currentBillNo, 
			String externalBillNoFrom, String externalCurrentBillNo) {
		this.id = id;
		this.billNoFrom = billNoFrom;
		this.billNoTo = billNoTo;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.currentBillNo=currentBillNo;
		this.externalBillNoFrom= externalBillNoFrom;
		this.externalCurrentBillNo= externalCurrentBillNo;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getBillNoFrom() {
		return billNoFrom;
	}
	public void setBillNoFrom(String billNoFrom) {
		this.billNoFrom = billNoFrom;
	}
	public String getBillNoTo() {
		return billNoTo;
	}
	public void setBillNoTo(String billNoTo) {
		this.billNoTo = billNoTo;
	}
	public String getCurrentBillNo() {
		return currentBillNo;
	}

	public void setCurrentBillNo(String currentBillNo) {
		this.currentBillNo = currentBillNo;
	}

	public Boolean getIsActive() {
		return isActive;
	}
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public String getModifiedBy() {
		return modifiedBy;
	}
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}
	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public String getExternalBillNoFrom() {
		return externalBillNoFrom;
	}

	public void setExternalBillNoFrom(String externalBillNoFrom) {
		this.externalBillNoFrom = externalBillNoFrom;
	}

	public String getExternalCurrentBillNo() {
		return externalCurrentBillNo;
	}

	public void setExternalCurrentBillNo(String externalCurrentBillNo) {
		this.externalCurrentBillNo = externalCurrentBillNo;
	}

	
	
	
	
}
