package com.kp.cms.bo.phd;

// Generated Mar 9, 2009 5:02:52 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kp.cms.bo.admin.Nationality;
import com.kp.cms.bo.admin.Religion;
import com.kp.cms.bo.admin.Users;

/**
 * Employee generated by hbm2java
 */
public class PhdEmployee implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int id;
	private String name;
	private String gender;
	private String empanelmentNo;
	private Date dateOfBirth;
	private String placeOfBirth;
	private Nationality nationality;
	private Religion religion;
	private String bloodGroup;
	private String domicialStatus;
	private String passPortNo;
	private String panNo;
	private String email;
	private Date dateOfAward;
	private DisciplineBo subjectGuideship;
	private String noOfresearch;
	private String noOfBookAuthored;
	private String nameAddress;
	private String department;
	private String designation;
	private String yearOfExp;
	private String permanentAddress;
	private String pAddressPhonNo;
	private String contactAddress;
	private String cAddressPhonNo;
	private String bankAccNo;
	private String bankName;
	private String bankBranch;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date lastModifiedDate;
	private Boolean isActive;
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<PhdEmpEducationalDetails> educationalDetailsSet = new HashSet<PhdEmpEducationalDetails>();
	private Set<PhdEmployeeExperience> teachingExperience = new HashSet<PhdEmployeeExperience>();
	private Set<PhdEmpImages> empImages = new HashSet<PhdEmpImages>();
	private int noMphilScolars;
	private int noPhdScolars;
	private int noPhdScolarOutside;
	
	public PhdEmployee() {
	}

	public PhdEmployee(int id) {
		this.id = id;
	}


	public PhdEmployee(int id,String name,String gender,String empanelmentNo,Date dateOfBirth,String placeOfBirth,Nationality nationality,Religion religion,
	String bloodGroup,String domicialStatus,String passPortNo,String panNo,String email,Date dateOfAward,DisciplineBo subjectGuideship,String noOfresearch,
	String noOfBookAuthored,String nameAddress,String department,String designation,String yearOfExp,String permanentAddress,int noMphilScolars,int noPhdScolars,int noPhdScolarOutside,
	String pAddressPhonNo,String contactAddress,String cAddressPhonNo,String bankAccNo,String bankName,String bankBranch,String createdBy,
	Date createdDate,String modifiedBy,Date lastModifiedDate,Boolean isActive,Set<Users> userses,Set<PhdEmpEducationalDetails> educationalDetailsSet,Set<PhdEmpImages> empImages,
	Set<PhdEmployeeExperience> teachingExperience) {
		super();
		this.id=id;
		this.name=name;
		this.gender=gender;
		this.dateOfBirth=dateOfBirth;
		this.placeOfBirth=placeOfBirth;
		this.nationality=nationality;
		this.religion=religion;
		this.bloodGroup=bloodGroup;
		this.domicialStatus=domicialStatus;
		this.passPortNo=passPortNo;
		this.panNo=panNo;
		this.email=email;
		this.dateOfAward=dateOfAward;
		this.subjectGuideship=subjectGuideship;
		this.noOfresearch=noOfresearch;
		this.noOfBookAuthored=noOfBookAuthored;
		this.nameAddress=nameAddress;
		this.department=department;
		this.designation=designation;
		this.yearOfExp=yearOfExp;
		this.permanentAddress=permanentAddress;
		this.pAddressPhonNo=pAddressPhonNo;
		this.contactAddress=contactAddress;
		this.cAddressPhonNo=cAddressPhonNo;
		this.bankAccNo=bankAccNo;
		this.bankName=bankName;
		this.bankBranch=bankBranch;
		this.createdBy=createdBy;
		this.createdDate=createdDate;
		this.modifiedBy=modifiedBy;
		this.lastModifiedDate=lastModifiedDate;
		this.userses=userses;
		this.educationalDetailsSet=educationalDetailsSet;
		this.empImages=empImages;
		this.teachingExperience=teachingExperience;
		this.empanelmentNo=empanelmentNo;
		this.noMphilScolars=noMphilScolars;
		this.noPhdScolars=noPhdScolars;
		this.noPhdScolarOutside=noPhdScolarOutside;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getEmpanelmentNo() {
		return empanelmentNo;
	}

	public void setEmpanelmentNo(String empanelmentNo) {
		this.empanelmentNo = empanelmentNo;
	}

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getPlaceOfBirth() {
		return placeOfBirth;
	}

	public void setPlaceOfBirth(String placeOfBirth) {
		this.placeOfBirth = placeOfBirth;
	}

	public Nationality getNationality() {
		return nationality;
	}

	public void setNationality(Nationality nationality) {
		this.nationality = nationality;
	}

	public Religion getReligion() {
		return religion;
	}

	public void setReligion(Religion religion) {
		this.religion = religion;
	}

	public String getBloodGroup() {
		return bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	public String getDomicialStatus() {
		return domicialStatus;
	}

	public void setDomicialStatus(String domicialStatus) {
		this.domicialStatus = domicialStatus;
	}

	public String getPassPortNo() {
		return passPortNo;
	}

	public void setPassPortNo(String passPortNo) {
		this.passPortNo = passPortNo;
	}

	public String getPanNo() {
		return panNo;
	}

	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDateOfAward() {
		return dateOfAward;
	}

	public void setDateOfAward(Date dateOfAward) {
		this.dateOfAward = dateOfAward;
	}

	public DisciplineBo getSubjectGuideship() {
		return subjectGuideship;
	}

	public void setSubjectGuideship(DisciplineBo subjectGuideship) {
		this.subjectGuideship = subjectGuideship;
	}

	public String getNoOfresearch() {
		return noOfresearch;
	}

	public void setNoOfresearch(String noOfresearch) {
		this.noOfresearch = noOfresearch;
	}

	public String getNoOfBookAuthored() {
		return noOfBookAuthored;
	}

	public void setNoOfBookAuthored(String noOfBookAuthored) {
		this.noOfBookAuthored = noOfBookAuthored;
	}

	public String getNameAddress() {
		return nameAddress;
	}

	public void setNameAddress(String nameAddress) {
		this.nameAddress = nameAddress;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getDesignation() {
		return designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getYearOfExp() {
		return yearOfExp;
	}

	public void setYearOfExp(String yearOfExp) {
		this.yearOfExp = yearOfExp;
	}

	public String getPermanentAddress() {
		return permanentAddress;
	}

	public void setPermanentAddress(String permanentAddress) {
		this.permanentAddress = permanentAddress;
	}

	public String getpAddressPhonNo() {
		return pAddressPhonNo;
	}

	public void setpAddressPhonNo(String pAddressPhonNo) {
		this.pAddressPhonNo = pAddressPhonNo;
	}

	public String getContactAddress() {
		return contactAddress;
	}

	public void setContactAddress(String contactAddress) {
		this.contactAddress = contactAddress;
	}

	public String getcAddressPhonNo() {
		return cAddressPhonNo;
	}

	public void setcAddressPhonNo(String cAddressPhonNo) {
		this.cAddressPhonNo = cAddressPhonNo;
	}

	public String getBankAccNo() {
		return bankAccNo;
	}

	public void setBankAccNo(String bankAccNo) {
		this.bankAccNo = bankAccNo;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankBranch() {
		return bankBranch;
	}

	public void setBankBranch(String bankBranch) {
		this.bankBranch = bankBranch;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<Users> getUserses() {
		return userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	public Set<PhdEmpEducationalDetails> getEducationalDetailsSet() {
		return educationalDetailsSet;
	}

	public void setEducationalDetailsSet(
			Set<PhdEmpEducationalDetails> educationalDetailsSet) {
		this.educationalDetailsSet = educationalDetailsSet;
	}

	public Set<PhdEmployeeExperience> getTeachingExperience() {
		return teachingExperience;
	}

	public void setTeachingExperience(Set<PhdEmployeeExperience> teachingExperience) {
		this.teachingExperience = teachingExperience;
	}

	public Set<PhdEmpImages> getEmpImages() {
		return empImages;
	}

	public void setEmpImages(Set<PhdEmpImages> empImages) {
		this.empImages = empImages;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public int getNoMphilScolars() {
		return noMphilScolars;
	}

	public void setNoMphilScolars(int noMphilScolars) {
		this.noMphilScolars = noMphilScolars;
	}

	public int getNoPhdScolars() {
		return noPhdScolars;
	}

	public void setNoPhdScolars(int noPhdScolars) {
		this.noPhdScolars = noPhdScolars;
	}

	public int getNoPhdScolarOutside() {
		return noPhdScolarOutside;
	}

	public void setNoPhdScolarOutside(int noPhdScolarOutside) {
		this.noPhdScolarOutside = noPhdScolarOutside;
	}

	
}
