package com.kp.cms.to.admin;

// Generated Jan 22, 2009 3:35:47 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import com.kp.cms.bo.admin.AdmSubjectForRank;
import com.kp.cms.bo.admin.EdnQualification;
import com.kp.cms.to.admission.AdmSubjectForRankTo;



/**
 * Course generated by hbm2java
 */
public class AdmSubjectMarkForRankTO implements java.io.Serializable {

	private int id;
	private String createdBy;;
	private String modifiedBy;
	private String maxmark;
	private String obtainedmark;
	private String conversionmark;
	private Boolean isActive;
	private Date createdDate;
	private Date lastModifiedDate;
	private String subid;
	Map<Integer,String> admSubjectMap;
	Map<Integer,String> admSubjectLangMap;
	private String totalobtainedmark;
	private String totalmaxmark;
	private AdmSubjectForRankTo admSubjectForRankTo;
	private EdnQualificationTO ednQualificationTO;
	private String subjectName;
	private String credit;
	private String admSubjectOther;
	private String groupname;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public String getModifiedBy() {
		return modifiedBy;
	}
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	
	public Boolean getIsActive() {
		return isActive;
	}
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}
	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}
	public String getMaxmark() {
		return maxmark;
	}
	public void setMaxmark(String maxmark) {
		this.maxmark = maxmark;
	}
	public String getObtainedmark() {
		return obtainedmark;
	}
	public void setObtainedmark(String obtainedmark) {
		this.obtainedmark = obtainedmark;
	}
	public String getConversionmark() {
		return conversionmark;
	}
	public void setConversionmark(String conversionmark) {
		this.conversionmark = conversionmark;
	}
	
	public String getSubid() {
		return subid;
	}
	public void setSubid(String subid) {
		this.subid = subid;
	}
	public Map<Integer, String> getAdmSubjectMap() {
		return admSubjectMap;
	}
	public void setAdmSubjectMap(Map<Integer, String> admSubjectMap) {
		this.admSubjectMap = admSubjectMap;
	}
	public Map<Integer, String> getAdmSubjectLangMap() {
		return admSubjectLangMap;
	}
	public void setAdmSubjectLangMap(Map<Integer, String> admSubjectLangMap) {
		this.admSubjectLangMap = admSubjectLangMap;
	}
	public String getTotalobtainedmark() {
		return totalobtainedmark;
	}
	public void setTotalobtainedmark(String totalobtainedmark) {
		this.totalobtainedmark = totalobtainedmark;
	}
	public String getTotalmaxmark() {
		return totalmaxmark;
	}
	public void setTotalmaxmark(String totalmaxmark) {
		this.totalmaxmark = totalmaxmark;
	}
	public AdmSubjectForRankTo getAdmSubjectForRankTo() {
		return admSubjectForRankTo;
	}
	public void setAdmSubjectForRankTo(AdmSubjectForRankTo admSubjectForRankTo) {
		this.admSubjectForRankTo = admSubjectForRankTo;
	}
	public EdnQualificationTO getEdnQualificationTO() {
		return ednQualificationTO;
	}
	public void setEdnQualificationTO(EdnQualificationTO ednQualificationTO) {
		this.ednQualificationTO = ednQualificationTO;
	}
	public String getSubjectName() {
		return subjectName;
	}
	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}
	public String getCredit() {
		return credit;
	}
	public void setCredit(String credit) {
		this.credit = credit;
	}
	public String getAdmSubjectOther() {
		return admSubjectOther;
	}
	public void setAdmSubjectOther(String admSubjectOther) {
		this.admSubjectOther = admSubjectOther;
	}
	public String getGroupname() {
		return groupname;
	}
	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}
	
	

}
	
	