package com.kp.cms.to.admin;

// Generated Feb 10, 2009 3:07:45 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * GuidelinesDoc generated by hbm2java
 */
public class DetailedSubjectsTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2290041995700412908L;
	private int id;
	private String createdBy;;
	private String modifiedBy;
	private CourseTO courseTo;
	private String subjectName;
	private Boolean isActive;
	private Date createdDate;
	private Date lastModifiedDate;
	private String cDate;
	private String lDate;
	
	private String active;
	
	public String getCDate() {
		return cDate;
	}

	public void setCDate(String date) {
		cDate = date;
	}

	public String getLDate() {
		return lDate;
	}

	public void setLDate(String date) {
		lDate = date;
	}

	/**
	 * @return the courseTo
	 */
	public CourseTO getCourseTo() {
		return courseTo;
	}

	/**
	 * @param courseTo the courseTo to set
	 */
	public void setCourseTo(CourseTO courseTo) {
		this.courseTo = courseTo;
	}
	

	public DetailedSubjectsTO() {
	}

	public DetailedSubjectsTO(int id) {
		this.id = id;
	}

	public DetailedSubjectsTO(int id, String createdBy,
			String modifiedBy, CourseTO courseTo,String subjectName,
			Boolean isActive, Date createdDate, Date lastModifiedDate) {
		this.id = id;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.courseTo = courseTo;
		this.subjectName = subjectName;
		this.isActive = isActive;
		this.createdDate = (Date)createdDate.clone();
		this.lastModifiedDate = (Date)lastModifiedDate.clone();
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)  {
		this.createdBy = createdBy;
	}

	public String getModifiedBy()  {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}


	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Date getCreatedDate() {
		return (Date)this.createdDate.clone();
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = (Date)createdDate.clone();
	}

	public Date getLastModifiedDate() {
		return (Date)this.lastModifiedDate.clone();
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = (Date)lastModifiedDate.clone();
	}

	/**
	 * @return the subjectName
	 */
	public String getSubjectName() {
		return subjectName;
	}

	/**
	 * @param subjectName the subjectName to set
	 */
	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public String getActive() {
		return active;
	}

	public void setActive(String active) {
		this.active = active;
	}
	
	
}